-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `locales_achievement_reward` SET `subject_loc11`='Per l\'Alleanza!' WHERE `entry`=614;
UPDATE `locales_achievement_reward` SET `subject_loc11`='Avanti tutta, Ammiraglio!' WHERE `entry`=871;
UPDATE `locales_achievement_reward` SET `subject_loc11`='Il Diplomatico' WHERE `entry`=942;
UPDATE `locales_achievement_reward` SET `subject_loc11`='Il Diplomatico' WHERE `entry`=943;

SET NAMES 'latin1';
