-- File generated by Mangos Online Translation Editor (MOTE) v3.03
SET NAMES 'utf8';
UPDATE `locales_achievement_reward` SET `subject_loc7`='Maestro de batalla' WHERE `entry`=230;
UPDATE `locales_achievement_reward` SET `subject_loc7`='¡Por la Alianza!' WHERE `entry`=614;
UPDATE `locales_achievement_reward` SET `subject_loc7`='¡Por la Horda!' WHERE `entry`=619;
UPDATE `locales_achievement_reward` SET `subject_loc7`='¡Adelante, almirante!' WHERE `entry`=871;
UPDATE `locales_achievement_reward` SET `subject_loc7`='La Diplomática' WHERE `entry`=942;
UPDATE `locales_achievement_reward` SET `subject_loc7`='La Diplomática' WHERE `entry`=943;
UPDATE `locales_achievement_reward` SET `subject_loc7`='Maestro de batalla' WHERE `entry`=1175;

SET NAMES 'latin1';
