-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `locales_achievement_reward` SET `subject_loc4`='战场军官' WHERE `entry`=230;
UPDATE `locales_achievement_reward` SET `subject_loc4`='为了联盟！' WHERE `entry`=614;
UPDATE `locales_achievement_reward` SET `subject_loc4`='为了部落！！' WHERE `entry`=619;
UPDATE `locales_achievement_reward` SET `subject_loc4`='敬礼，舰队司令！' WHERE `entry`=871;
UPDATE `locales_achievement_reward` SET `subject_loc4`='外交专用佩枪' WHERE `entry`=942;
UPDATE `locales_achievement_reward` SET `subject_loc4`='外交专用佩枪' WHERE `entry`=943;
UPDATE `locales_achievement_reward` SET `subject_loc4`='战场军官' WHERE `entry`=1175;

SET NAMES 'latin1';
