-- ----------------------------------------------------------------
-- This is an attempt to create a full transactional MaNGOS update
-- Now compatible with newer MySql Databases (v1.5)
-- ----------------------------------------------------------------
DROP PROCEDURE IF EXISTS `update_mangos`; 

DELIMITER $$

-- CREATE DEFINER=`root`@`localhost` PROCEDURE `update_mangos`()
CREATE PROCEDURE `update_mangos`()
BEGIN
    DECLARE bRollback BOOL  DEFAULT FALSE ;
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET `bRollback` = TRUE;

    -- Current Values (TODO - must be a better way to do this)
    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cCurStructure := (SELECT `structure` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cCurContent := (SELECT `content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);

    -- Expected Values
    SET @cOldVersion = '22'; 
    SET @cOldStructure = '04'; 
    SET @cOldContent = '031';

    -- New Values
    SET @cNewVersion = '22';
    SET @cNewStructure = '04';
    SET @cNewContent = '032';
                            -- DESCRIPTION IS 30 Characters MAX    
    SET @cNewDescription = 'Fix_Loot_Startup_errors';

                        -- COMMENT is 150 Characters MAX
    SET @cNewComment = 'Fix_Loot_Startup_errors: (item entry needs ITEM_FLAG_LOOTABLE)';

    -- Evaluate all settings
    SET @cCurResult := (SELECT `description` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
    SET @cOldResult := (SELECT `description` FROM `db_version` WHERE `version`=@cOldVersion AND `structure`=@cOldStructure AND `content`=@cOldContent);
    SET @cNewResult := (SELECT `description` FROM `db_version` WHERE `version`=@cNewVersion AND `structure`=@cNewStructure AND `content`=@cNewContent);

    IF (@cCurResult = @cOldResult) THEN    -- Does the current version match the expected version
        -- APPLY UPDATE
        START TRANSACTION;
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
        -- -- PLACE UPDATE SQL BELOW -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -

UPDATE `item_template` set flags=flags^4 where entry= 3746; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 4573; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 5857; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 5858; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 6644; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 6646; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 7868; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 8502; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 8503; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 8504; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 8505; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 8506; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 8507; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 9529; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 9532; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 9537; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 10594; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 10595; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13247; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13642; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13643; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13644; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13645; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13646; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13647; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13648; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13649; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13650; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13651; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13652; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13653; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13654; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13655; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13656; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13657; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13658; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13659; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13660; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13661; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13662; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13663; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13664; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13665; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13666; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13667; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13668; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13669; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13670; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13671; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13672; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13673; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13674; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13675; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13676; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13677; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13678; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13679; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13680; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13681; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13682; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13683; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13684; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13685; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13686; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13687; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13688; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13689; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13690; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13691; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13692; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13693; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13694; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13695; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13696; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 13697; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16068; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16069; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16070; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16071; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16074; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16075; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16076; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16077; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16078; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16079; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16080; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16081; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16109; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16173; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16174; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16175; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16176; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16177; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16178; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16179; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16180; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16181; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16182; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16183; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16184; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16185; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16186; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16187; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 16188; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17824; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17825; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17826; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17831; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17832; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17833; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17834; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17835; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17836; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17837; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17838; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17839; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17840; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17841; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17842; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17843; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17844; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17845; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17846; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17847; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17848; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17851; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17852; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17853; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17854; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17855; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17856; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17857; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17858; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17859; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17860; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17861; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17862; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17910; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 17911; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 18636; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 20364; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 20367; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21131; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21163; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21274; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21628; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21629; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21630; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21631; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21632; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21633; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21634; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21636; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21637; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21638; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21641; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21642; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21643; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21644; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21646; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21649; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21653; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21655; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21656; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21657; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21658; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21659; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21660; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21661; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21662; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 21930; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 22045; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 22152; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 23224; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 23271; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 23895; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27316; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27318; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27319; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27320; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27321; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27322; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27323; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27324; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27325; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27326; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27327; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27328; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27329; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27330; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27331; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27332; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27333; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27334; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27335; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27336; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27337; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27338; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27339; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27340; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27341; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27342; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27343; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27344; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27345; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27346; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27347; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27348; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27349; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27350; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27351; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27352; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27353; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27354; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27355; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27356; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27358; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27359; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27360; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27361; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27362; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27363; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27364; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27365; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27366; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27367; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27368; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27369; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27370; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27371; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27372; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27373; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27374; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27375; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27376; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27377; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27378; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27379; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27380; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27381; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27382; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27383; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27384; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27385; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27386; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27387; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27391; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27392; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27393; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27394; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27395; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27396; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27397; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27554; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27555; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27556; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27557; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27558; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27559; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27560; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27561; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27562; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27563; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27564; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27565; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27566; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27567; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27568; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27569; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27570; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27571; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27572; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27573; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27574; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27575; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27576; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27577; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27578; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27579; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27580; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27581; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27582; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27583; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27584; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27585; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27586; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27587; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27588; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27589; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27590; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27591; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27592; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27593; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27594; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27595; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27596; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27597; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27598; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27599; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27600; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27601; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27602; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27603; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27604; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27605; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27606; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27607; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27608; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27609; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27610; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27611; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27612; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27613; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27614; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27615; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27616; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27617; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27618; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27619; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27620; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27621; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27622; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27623; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27624; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27625; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27626; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27627; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27628; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27629; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 27630; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28076; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28077; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28078; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28079; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28080; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28081; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28082; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28083; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28084; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28085; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28086; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28088; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28089; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28090; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28091; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28092; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28093; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28094; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28095; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28096; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28097; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28098; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 28135; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 29208; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 29886; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 29887; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32543; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32544; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32545; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32546; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32547; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32548; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32549; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32550; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32551; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32552; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32553; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32554; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32555; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32556; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32557; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32558; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32559; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32560; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 32561; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 34156; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 34503; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 34548; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 35745; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 37605; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 38539; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 39014; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 39904; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 39913; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 40308; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 42953; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 46358; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 49369; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 49532; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 49612; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 49926; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 50409; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 52331; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 54467; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 67250; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 68133; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 68598; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 68798; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 68799; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 68800; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 68801; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 68802; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 68803; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 68804; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 68805; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 69856; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 70931; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 70938; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 73204; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 78904; -- (item entry needs ITEM_FLAG_LOOTABLE)
UPDATE `item_template` set flags=flags^4 where entry= 78910; -- (item entry needs ITEM_FLAG_LOOTABLE)

        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
        -- -- PLACE UPDATE SQL ABOVE -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -

        -- If we get here ok, commit the changes
        IF bRollback = TRUE THEN
            ROLLBACK;
            SHOW ERRORS;
            SELECT '* UPDATE FAILED *' AS `===== Status =====`,@cCurResult AS `===== DB is on Version: =====`;
        ELSE
            COMMIT;
            -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
            -- UPDATE THE DB VERSION
            -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
            INSERT INTO `db_version` VALUES (@cNewVersion, @cNewStructure, @cNewContent, @cNewDescription, @cNewComment);
            SET @cNewResult := (SELECT `description` FROM `db_version` WHERE `version`=@cNewVersion AND `structure`=@cNewStructure AND `content`=@cNewContent);

            SELECT '* UPDATE COMPLETE *' AS `===== Status =====`,@cNewResult AS `===== DB is now on Version =====`;
        END IF;
    ELSE    -- Current version is not the expected version
        IF (@cCurResult = @cNewResult) THEN    -- Does the current version match the new version
            SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cCurResult AS `===== DB is already on Version =====`;
        ELSE    -- Current version is not one related to this update
            IF(@cCurResult IS NULL) THEN    -- Something has gone wrong
                SELECT '* UPDATE FAILED *' AS `===== Status =====`,'Unable to locate DB Version Information' AS `============= Error Message =============`;
            ELSE
                IF(@cOldResult IS NULL) THEN    -- Something has gone wrong
                    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurStructure := (SELECT `STRUCTURE` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurContent := (SELECT `Content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurOutput = CONCAT(@cCurVersion, '_', @cCurStructure, '_', @cCurContent, ' - ',@cCurResult);
                    SET @cOldResult = CONCAT('Rel',@cOldVersion, '_', @cOldStructure, '_', @cOldContent, ' - ','IS NOT APPLIED');
                    SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cOldResult AS `=== Expected ===`,@cCurOutput AS `===== Found Version =====`;
                ELSE
                    SET @cCurVersion := (SELECT `version` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurStructure := (SELECT `STRUCTURE` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurContent := (SELECT `Content` FROM `db_version` ORDER BY `version` DESC, `STRUCTURE` DESC, `CONTENT` DESC LIMIT 0,1);
                    SET @cCurOutput = CONCAT(@cCurVersion, '_', @cCurStructure, '_', @cCurContent, ' - ',@cCurResult);
                    SELECT '* UPDATE SKIPPED *' AS `===== Status =====`,@cOldResult AS `=== Expected ===`,@cCurOutput AS `===== Found Version =====`;
                END IF;
            END IF;
        END IF;
    END IF;
END $$

DELIMITER ;

-- Execute the procedure
CALL update_mangos();

-- Drop the procedure
DROP PROCEDURE IF EXISTS `update_mangos`;


