-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc5`=' He captured an Aspect!$B$BAnd just as easily, he took my mate.' WHERE `word_id` = 8688; -- db_script_string - content : entry=2000000117
UPDATE `trans_words` SET `content_loc5`=' Oh, these are sticky! I wonder how they shoot the webbing?' WHERE `word_id` = 8355; -- db_script_string - content : entry=2000001047
UPDATE `trans_words` SET `content_loc5`='$N versus the ferocious clefthoof, Brokentoe!' WHERE `word_id` = 7594; -- db_script_string - content : entry=2000000102
UPDATE `trans_words` SET `content_loc5`='$N, look, please, Vylestem Vines, which I brought from the caves, so you\'d know what to look for...' WHERE `word_id` = 8780; -- db_script_string - content : entry=2000001238
UPDATE `trans_words` SET `content_loc5`='$R, do you know who Kolphis Darkscale is?' WHERE `word_id` = 7725; -- db_script_string - content : entry=2000000445
UPDATE `trans_words` SET `content_loc5`='%s appeals to the mighty armies of the Scourge!' WHERE `word_id` = 8717; -- db_script_string - content : entry=2000000037
UPDATE `trans_words` SET `content_loc5`='%s becomes energized with arcane magic.' WHERE `word_id` = 8432; -- db_script_string - content : entry=2000000683
UPDATE `trans_words` SET `content_loc5`='%s flies up over trees, having released from Terokk\'s influence.' WHERE `word_id` = 8406; -- db_script_string - content : entry=2000000796
UPDATE `trans_words` SET `content_loc5`='%s is chasing you!' WHERE `word_id` = 4035; -- db_script_string - content : entry=2000000887
UPDATE `trans_words` SET `content_loc5`='%s points to a pile of books...' WHERE `word_id` = 8778; -- db_script_string - content : entry=2000001236
UPDATE `trans_words` SET `content_loc5`='%s takes big swig of ale.' WHERE `word_id` = 6997; -- db_script_string - content : entry=2000000281
UPDATE `trans_words` SET `content_loc5`='...on an open fire....' WHERE `word_id` = 8363; -- db_script_string - content : entry=2000001032
UPDATE `trans_words` SET `content_loc5`='...receive 50 percent of the clothes deserters? What is this rubbish?' WHERE `word_id` = 8775; -- db_script_string - content : entry=2000001233
UPDATE `trans_words` SET `content_loc5`='[PH] Greetings, $N.' WHERE `word_id` = 8690; -- db_script_string - content : entry=2000000107
UPDATE `trans_words` SET `content_loc5`='\'We like trees, Fenrick. They provide cover.\' They won\'t let me chop them down, either.' WHERE `word_id` = 8518; -- db_script_string - content : entry=2000000468
UPDATE `trans_words` SET `content_loc5`='<Harry looks up at you.>' WHERE `word_id` = 8511; -- db_script_string - content : entry=2000000484
UPDATE `trans_words` SET `content_loc5`='<Harry takes the crystal from you and gently pats it.>' WHERE `word_id` = 8512; -- db_script_string - content : entry=2000000482
UPDATE `trans_words` SET `content_loc5`='A stone dam was saved! The triple "Hurray!" you, $N!' WHERE `word_id` = 8779; -- db_script_string - content : entry=2000001237
UPDATE `trans_words` SET `content_loc5`='AAAAHHH!' WHERE `word_id` = 8602; -- db_script_string - content : entry=2000000346
UPDATE `trans_words` SET `content_loc5`='About, the spirit of a tiger, $N appeals to you! Have put on us the force and help us to find answers to our questions!' WHERE `word_id` = 8781; -- db_script_string - content : entry=2000001239
UPDATE `trans_words` SET `content_loc5`='Access to the Archivum granted. Intrusion protection mechanisms suspended.' WHERE `word_id` = 8561; -- db_script_string - content : entry=2000000394
UPDATE `trans_words` SET `content_loc5`='Ah, I see it now in your mind. This is the work of one of my former students... Mehlar Dawnblade. It is sad to know that his heart has turned so dark.' WHERE `word_id` = 7810; -- db_script_string - content : entry=2000000814
UPDATE `trans_words` SET `content_loc5`='Ah, yes. Loken I know well.' WHERE `word_id` = 8709; -- db_script_string - content : entry=2000000078
UPDATE `trans_words` SET `content_loc5`='Ah... Soldier guard. He was the more cheerful... not yet lost the throat during a raid on Bleeding Hollow...' WHERE `word_id` = 8750; -- db_script_string - content : entry=2000001097
UPDATE `trans_words` SET `content_loc5`='Ahh, much appreciated, Corbett. We\'ll get these on the racks immediately.' WHERE `word_id` = 7019; -- db_script_string - content : entry=2000000332
UPDATE `trans_words` SET `content_loc5`='Algalon diagnostics assess danger of systemic Old God corruption in planetary vital functions. Calculating chance of Omega Reply-code...' WHERE `word_id` = 8555; -- db_script_string - content : entry=2000000400
UPDATE `trans_words` SET `content_loc5`='All ... enough for today!' WHERE `word_id` = 8357; -- db_script_string - content : entry=2000001040
UPDATE `trans_words` SET `content_loc5`='Allies imprisoned in the field of battle are likely to provide synergies and minimize combat duration.' WHERE `word_id` = 8582; -- db_script_string - content : entry=2000000373
UPDATE `trans_words` SET `content_loc5`='Aman dissipates before your eyes.' WHERE `word_id` = 7998; -- db_script_string - content : entry=2000000728
UPDATE `trans_words` SET `content_loc5`='Amazing! I feel re-born. To force me to come back!' WHERE `word_id` = 8386; -- db_script_string - content : entry=2000001007
UPDATE `trans_words` SET `content_loc5`='Among the skulls no Yenniku, $N. This is great for easing me.' WHERE `word_id` = 8387; -- db_script_string - content : entry=2000001005
UPDATE `trans_words` SET `content_loc5`='An Avatar of Terokk! To arms!' WHERE `word_id` = 7599; -- db_script_string - content : entry=2000000121
UPDATE `trans_words` SET `content_loc5`='Analyzing Elder Brightleaf enhancement. Persistent area defenses powered by solar amplification.' WHERE `word_id` = 8590; -- db_script_string - content : entry=2000000365
UPDATE `trans_words` SET `content_loc5`='Analyzing watchers status. Please wait.' WHERE `word_id` = 8544; -- db_script_string - content : entry=2000000410
UPDATE `trans_words` SET `content_loc5`='Anaya\'s soft voice trails away into the mists. "Know that I love you always..."' WHERE `word_id` = 7428; -- db_script_string - content : entry=2000000655
UPDATE `trans_words` SET `content_loc5`='And even more!' WHERE `word_id` = 7598; -- db_script_string - content : entry=2000000118
UPDATE `trans_words` SET `content_loc5`='And now I will fill this luminous crystal, so that we can discard all the lies and deceit.' WHERE `word_id` = 8349; -- db_script_string - content : entry=2000001053
UPDATE `trans_words` SET `content_loc5`='And that\'s how Lother killed thirty six orcs with his bare hands!' WHERE `word_id` = 7099; -- db_script_string - content : entry=2000000172
UPDATE `trans_words` SET `content_loc5`='And who do we have here? No doubt th... crzzzk ...ade this communication I give you greetings fro... psshzzzk... Azure Watch.' WHERE `word_id` = 8722; -- db_script_string - content : entry=2000000030
UPDATE `trans_words` SET `content_loc5`='And you - Spirit Gnomregan!' WHERE `word_id` = 8769; -- db_script_string - content : entry=2000001224
UPDATE `trans_words` SET `content_loc5`='Approach, buy.' WHERE `word_id` = 8642; -- db_script_string - content : entry=2000000221
UPDATE `trans_words` SET `content_loc5`='Approach, newbie!' WHERE `word_id` = 8715; -- db_script_string - content : entry=2000000054
UPDATE `trans_words` SET `content_loc5`='Are you sure that ours is not followed? I have a bad premonition...' WHERE `word_id` = 8377; -- db_script_string - content : entry=2000001018
UPDATE `trans_words` SET `content_loc5`='As soon as the neutralizing agent is mixed with the waters of the lake, water, contaminated crystal, seems to have cleared.' WHERE `word_id` = 8443; -- db_script_string - content : entry=2000000605
UPDATE `trans_words` SET `content_loc5`='Ask me how you can get a free drink at the Blue Recluse!' WHERE `word_id` = 7149; -- db_script_string - content : entry=2000005191
UPDATE `trans_words` SET `content_loc5`='At least we would not be around to have to clean it up.' WHERE `word_id` = 7523; -- db_script_string - content : entry=2000005149
UPDATE `trans_words` SET `content_loc5`='AYYYIEEE!' WHERE `word_id` = 8604; -- db_script_string - content : entry=2000000345
UPDATE `trans_words` SET `content_loc5`='Back to the topic... we should focus our attention on these manaforges. We need to learn what the enemy is doing with them and why.' WHERE `word_id` = 7971; -- db_script_string - content : entry=2000005276
UPDATE `trans_words` SET `content_loc5`='Be on guard!' WHERE `word_id` = 8375; -- db_script_string - content : entry=2000001019
UPDATE `trans_words` SET `content_loc5`='Be patient $N. The torch is almost complete.' WHERE `word_id` = 6948; -- db_script_string - content : entry=2000000072
UPDATE `trans_words` SET `content_loc5`='Be sure to enter the sanctuary and come out through the southern pass. $N. You know pass where the battle is on to protect them from the abomination ... keep them away.' WHERE `word_id` = 8367; -- db_script_string - content : entry=2000001030
UPDATE `trans_words` SET `content_loc5`='Be sure to read over the notes in my journal. You will find them to be invaluable in overcoming the tower\'s defenses' WHERE `word_id` = 8711; -- db_script_string - content : entry=2000000067
UPDATE `trans_words` SET `content_loc5`='Beer! The usual beer!' WHERE `word_id` = 8340; -- db_script_string - content : entry=2000001062
UPDATE `trans_words` SET `content_loc5`='Beginning analysis...' WHERE `word_id` = 8629; -- db_script_string - content : entry=2000000304
UPDATE `trans_words` SET `content_loc5`='begins to read the spell over the hearts and tongues.' WHERE `word_id` = 8736; -- db_script_string - content : entry=2000001082
UPDATE `trans_words` SET `content_loc5`='belches loudly...' WHERE `word_id` = 8364; -- db_script_string - content : entry=2000001033
UPDATE `trans_words` SET `content_loc5`='Beware $N! Look to the west!' WHERE `word_id` = 724; -- db_script_string - content : entry=2000000472
UPDATE `trans_words` SET `content_loc5`='Billy says that formerly Fizzle was a large wizard. But it was transformed into rabbit because of a spell which went wrong.' WHERE `word_id` = 8651; -- db_script_string - content : entry=2000000190
UPDATE `trans_words` SET `content_loc5`='Blue with red ... I thought so ...' WHERE `word_id` = 8379; -- db_script_string - content : entry=2000001015
UPDATE `trans_words` SET `content_loc5`='Bogling rises from the soil!' WHERE `word_id` = 7695; -- db_script_string - content : entry=2000000720
UPDATE `trans_words` SET `content_loc5`='Brann writes that he worked on a guide for those runic symbols, when attacked by the giants with their allies.' WHERE `word_id` = 8764; -- db_script_string - content : entry=2000001219
UPDATE `trans_words` SET `content_loc5`='Brood of Onyxia!' WHERE `word_id` = 8737; -- db_script_string - content : entry=2000001083
UPDATE `trans_words` SET `content_loc5`='But isn\'t that what caused the initial problems with Adept Syleria\'s magical formula?' WHERE `word_id` = 7121; -- db_script_string - content : entry=2000005155
UPDATE `trans_words` SET `content_loc5`='But wouldn`t that mean crossing the streams? Isn`t that really bad?' WHERE `word_id` = 7526; -- db_script_string - content : entry=2000005160
UPDATE `trans_words` SET `content_loc5`='By the beard of Magni, we need to recreate the key, which he used to read the words on the stove. We could go right on his heels!' WHERE `word_id` = 8766; -- db_script_string - content : entry=2000001221
UPDATE `trans_words` SET `content_loc5`='Come to my lair, whelp! Come to me and pay for your insolecne!' WHERE `word_id` = 8010; -- db_script_string - content : entry=2000000841
UPDATE `trans_words` SET `content_loc5`='considers the talisman which gave him $N.' WHERE `word_id` = 8749; -- db_script_string - content : entry=2000001096
UPDATE `trans_words` SET `content_loc5`='Corbett, dear. Harlan needs a load of knitted shirts and pants as soon as we can manage.' WHERE `word_id` = 7010; -- db_script_string - content : entry=2000000323
UPDATE `trans_words` SET `content_loc5`='Curse withdrawn! \'ll Have to look for another way.' WHERE `word_id` = 8742; -- db_script_string - content : entry=2000001088
UPDATE `trans_words` SET `content_loc5`='Damn you vile Fel orcs! Let your mind absorb the evil that you worship!' WHERE `word_id` = 8752; -- db_script_string - content : entry=2000001099
UPDATE `trans_words` SET `content_loc5`='Damnit. How are we ever going to make it through their security measures?' WHERE `word_id` = 8003; -- db_script_string - content : entry=2000000812
UPDATE `trans_words` SET `content_loc5`='Darnassus is under reliable protection!' WHERE `word_id` = 8678; -- db_script_string - content : entry=2000000140
UPDATE `trans_words` SET `content_loc5`='Deja vu. For a moment, I thought I was back home... before the plague' WHERE `word_id` = 8658; -- db_script_string - content : entry=2000000163
UPDATE `trans_words` SET `content_loc5`='Denalan hurries to his planter.' WHERE `word_id` = 7696; -- db_script_string - content : entry=2000000721
UPDATE `trans_words` SET `content_loc5`='Denalan plants fruit seeds.' WHERE `word_id` = 7694; -- db_script_string - content : entry=2000000719
UPDATE `trans_words` SET `content_loc5`='Denalan removes the seeds from the Glowing Fruit...' WHERE `word_id` = 7692; -- db_script_string - content : entry=2000000717
UPDATE `trans_words` SET `content_loc5`='Derived from cutting edge Shattered Hand Offensive military technology, it blasts away stubborn stains with ease!' WHERE `word_id` = 7532; -- db_script_string - content : entry=2000000213
UPDATE `trans_words` SET `content_loc5`='Destruction of Elder servants will result in lost of enhancements of Watcher Freya. However permanent damage to Freya\'s person and possessions including her Watcher sigil highly probable.' WHERE `word_id` = 8586; -- db_script_string - content : entry=2000000369
UPDATE `trans_words` SET `content_loc5`='Do come to an end this foolish farce ... Arthas, give me strength!' WHERE `word_id` = 8600; -- db_script_string - content : entry=2000000351
UPDATE `trans_words` SET `content_loc5`='Do not do anything that would the incite Horde. $N. The Warchief has agreed to see us on good faith.' WHERE `word_id` = 8532; -- db_script_string - content : entry=2000000423
UPDATE `trans_words` SET `content_loc5`='Do not go too far down the corridor, $N. Stay with the captain and his men ... dead you have to anything.' WHERE `word_id` = 8759; -- db_script_string - content : entry=2000001213
UPDATE `trans_words` SET `content_loc5`='Do not taint these ruins, mortal.' WHERE `word_id` = 8408; -- db_script_string - content : entry=2000000790
UPDATE `trans_words` SET `content_loc5`='Do not worry, buddy. Rokhan take care of everything. Nowhere it is no getting away.' WHERE `word_id` = 8353; -- db_script_string - content : entry=2000001049
UPDATE `trans_words` SET `content_loc5`='Easier than I expected ... sign Thoradin intact.' WHERE `word_id` = 8735; -- db_script_string - content : entry=2000001081
UPDATE `trans_words` SET `content_loc5`='Elder Ironbranch scans have uncovered plant based immobilization mechanisms.' WHERE `word_id` = 8588; -- db_script_string - content : entry=2000000367
UPDATE `trans_words` SET `content_loc5`='Even you must admit that your information from defectors is outdated and unreliable. Let us make calculated attacks on these manaforges and gather what information we can.' WHERE `word_id` = 7974; -- db_script_string - content : entry=2000005279
UPDATE `trans_words` SET `content_loc5`='Excellent $N! This is something that we should! And now - for the work.' WHERE `word_id` = 8358; -- db_script_string - content : entry=2000001039
UPDATE `trans_words` SET `content_loc5`='Excellent horn! It would be difficult to choose the best...' WHERE `word_id` = 8361; -- db_script_string - content : entry=2000001036
UPDATE `trans_words` SET `content_loc5`='Excellent, $N, here she is: masking orc Warsong clan, with power of illusion and supplemented by a premonition!' WHERE `word_id` = 8757; -- db_script_string - content : entry=2000001211
UPDATE `trans_words` SET `content_loc5`='Farunn walks the lands north of what your people call the Bittertide Falls. You will find him alone, but you will see her requires no defenders.' WHERE `word_id` = 8453; -- db_script_string - content : entry=2000000589
UPDATE `trans_words` SET `content_loc5`='Fear not! All fortunes can be discerned for those who know the way.' WHERE `word_id` = 7535; -- db_script_string - content : entry=2000000230
UPDATE `trans_words` SET `content_loc5`='Fezzix, I think, we have decided your little problem with the engine.' WHERE `word_id` = 8730; -- db_script_string - content : entry=2000001076
UPDATE `trans_words` SET `content_loc5`='Filth! Filth everywhere! The forests must be Cleansed' WHERE `word_id` = 8647; -- db_script_string - content : entry=2000000197
UPDATE `trans_words` SET `content_loc5`='Finally we have the parts to repair the Spirit of Gnomeregan.' WHERE `word_id` = 8767; -- db_script_string - content : entry=2000001222
UPDATE `trans_words` SET `content_loc5`='Follow me, good $C. I\'ll have your barding done faster than I could down a Dwarven stout. Mmmm... stout.' WHERE `word_id` = 6975; -- db_script_string - content : entry=2000000012
UPDATE `trans_words` SET `content_loc5`='Follow, $N. I will soon begin the summoning...' WHERE `word_id` = 6954; -- db_script_string - content : entry=2000000062
UPDATE `trans_words` SET `content_loc5`='Fools. Obsidion! Rise, and destroy the interlopers!' WHERE `word_id` = 8396; -- db_script_string - content : entry=2000000803
UPDATE `trans_words` SET `content_loc5`='For God\'s sake, you killed Joe lame and took away the meat! How do you know where we look for?' WHERE `word_id` = 8337; -- db_script_string - content : entry=2000001069
UPDATE `trans_words` SET `content_loc5`='From his hiding place he watched the preparations for a war whose purpose was the destruction of stone giants.' WHERE `word_id` = 8707; -- db_script_string - content : entry=2000000081
UPDATE `trans_words` SET `content_loc5`='From your description, I\'m certain the book I loaned our visitor could allow you to easily identify the weapon.' WHERE `word_id` = 8703; -- db_script_string - content : entry=2000000085
UPDATE `trans_words` SET `content_loc5`='Fuud!' WHERE `word_id` = 8675; -- db_script_string - content : entry=2000000141
UPDATE `trans_words` SET `content_loc5`='Glacial Falls in the east, brother. Bring here the best armor to find. Alliance do not even understand who they attacked.' WHERE `word_id` = 8344; -- db_script_string - content : entry=2000001057
UPDATE `trans_words` SET `content_loc5`='Glad to see you\'re doing so well, Harlan. And I hope to see you again soon:' WHERE `word_id` = 8607; -- db_script_string - content : entry=2000000333
UPDATE `trans_words` SET `content_loc5`='Glowing Soulgem bursts open!' WHERE `word_id` = 6967; -- db_script_string - content : entry=2000000256
UPDATE `trans_words` SET `content_loc5`='Go, my servant. Send word of Stonetalon to Apothecary Zamah.' WHERE `word_id` = 7051; -- db_script_string - content : entry=2000000543
UPDATE `trans_words` SET `content_loc5`='Gods of the past, we appeal to you. What we do? How can we save the gods of the land?' WHERE `word_id` = 8366; -- db_script_string - content : entry=2000001035
UPDATE `trans_words` SET `content_loc5`='Good day. Elling! Hullo Elaine! Let me have a wheel of blue cheese, eh?' WHERE `word_id` = 7024; -- db_script_string - content : entry=2000000337
UPDATE `trans_words` SET `content_loc5`='Greatings my soldier !!' WHERE `word_id` = 8667; -- db_script_string - content : entry=2000000152
UPDATE `trans_words` SET `content_loc5`='Greatmother Hawkwind gestures to the pitcher of water sitting on the edge of the well.' WHERE `word_id` = 7687; -- db_script_string - content : entry=2000000254
UPDATE `trans_words` SET `content_loc5`='Greet $N, the new king of ogres!!!' WHERE `word_id` = 8739; -- db_script_string - content : entry=2000001085
UPDATE `trans_words` SET `content_loc5`='Grimclaw begins to moan and roar at Terenthis while stomping his paws on the ground.' WHERE `word_id` = 7191; -- db_script_string - content : entry=2000000827
UPDATE `trans_words` SET `content_loc5`='Grimclaw roars at Terenthis more, but this time the druid seems to understand the bear.' WHERE `word_id` = 7187; -- db_script_string - content : entry=2000000831
UPDATE `trans_words` SET `content_loc5`='Grimclaw roars at Terenthis to get his attention.' WHERE `word_id` = 7194; -- db_script_string - content : entry=2000000825
UPDATE `trans_words` SET `content_loc5`='Grimclaw roars in acknowledgement at Terenthis.' WHERE `word_id` = 7185; -- db_script_string - content : entry=2000000833
UPDATE `trans_words` SET `content_loc5`='Ha! $N, I did not move from their seats!' WHERE `word_id` = 8383; -- db_script_string - content : entry=2000001010
UPDATE `trans_words` SET `content_loc5`='He cannot be defeated.' WHERE `word_id` = 8409; -- db_script_string - content : entry=2000000788
UPDATE `trans_words` SET `content_loc5`='He deciphers aloud part of the inscriptions on rune plate, but it seems that he wrote his translation.' WHERE `word_id` = 8765; -- db_script_string - content : entry=2000001220
UPDATE `trans_words` SET `content_loc5`='He wants me to grab! If I were in your place was here cautious traveler. You never know for how a tree he is hiding!' WHERE `word_id` = 8705; -- db_script_string - content : entry=2000000083
UPDATE `trans_words` SET `content_loc5`='He... he kept it? All this time, he kept it!' WHERE `word_id` = 8502; -- db_script_string - content : entry=2000000498
UPDATE `trans_words` SET `content_loc5`='Hear that lads? It\'s only the end of the world! Well, what are ye waiting for, ye rusty machine? Initiate Reply-code Alpha, all is well! Pints are on me!' WHERE `word_id` = 8566; -- db_script_string - content : entry=2000000390
UPDATE `trans_words` SET `content_loc5`='Hear ye, denizens of Tanaris! Let it be known $N is an exalted member of the Mithril Order. A blacksmith of honor, dedication, and infinite patience. Three cheers for $N!' WHERE `word_id` = 6979; -- db_script_string - content : entry=2000000041
UPDATE `trans_words` SET `content_loc5`='Hello Grimclaw' WHERE `word_id` = 6938; -- db_script_string - content : entry=2000000076
UPDATE `trans_words` SET `content_loc5`='Hello, Charys. Here my list, can you find me all that, and especially the last ingredient?' WHERE `word_id` = 8657; -- db_script_string - content : entry=2000000184
UPDATE `trans_words` SET `content_loc5`='Help us, outsider.' WHERE `word_id` = 8404; -- db_script_string - content : entry=2000000794
UPDATE `trans_words` SET `content_loc5`='Here it is, $N! Finally, I understand!' WHERE `word_id` = 8378; -- db_script_string - content : entry=2000001016
UPDATE `trans_words` SET `content_loc5`='Here, girl. Can you last feed before we kill the killer lame Joe!' WHERE `word_id` = 8336; -- db_script_string - content : entry=2000001071
UPDATE `trans_words` SET `content_loc5`='Here\'s a beacon, $N. Keep it to yourself, if you\'re gonna find mutilated things that we need.' WHERE `word_id` = 7059; -- db_script_string - content : entry=2000000056
UPDATE `trans_words` SET `content_loc5`='Hey there, Belm! Give me a mug of Thunder Ale, and one for my good friend!' WHERE `word_id` = 8699; -- db_script_string - content : entry=2000000092
UPDATE `trans_words` SET `content_loc5`='Hey, I hope you help me!' WHERE `word_id` = 8700; -- db_script_string - content : entry=2000000088
UPDATE `trans_words` SET `content_loc5`='Hey, you! Just try to spill the beans about Grick! You hear?' WHERE `word_id` = 8342; -- db_script_string - content : entry=2000001064
UPDATE `trans_words` SET `content_loc5`='Hi Corbett! Here, you go! I trust business is faring well at your clothier shop...?' WHERE `word_id` = 7026; -- db_script_string - content : entry=2000000339
UPDATE `trans_words` SET `content_loc5`='hits the twisted claws.' WHERE `word_id` = 8393; -- db_script_string - content : entry=2000000999
UPDATE `trans_words` SET `content_loc5`='Hm.. I filing you, come and fight !!' WHERE `word_id` = 8665; -- db_script_string - content : entry=2000000154
UPDATE `trans_words` SET `content_loc5`='Hm...You are not too bad!' WHERE `word_id` = 8716; -- db_script_string - content : entry=2000000055
UPDATE `trans_words` SET `content_loc5`='Hold your tongue, knave! Do not dare use that tone with a priestess of the Light!' WHERE `word_id` = 7968; -- db_script_string - content : entry=2000005273
UPDATE `trans_words` SET `content_loc5`='Hot meal' WHERE `word_id` = 8643; -- db_script_string - content : entry=2000000222
UPDATE `trans_words` SET `content_loc5`='How can anyone live like this!?' WHERE `word_id` = 8674; -- db_script_string - content : entry=2000000143
UPDATE `trans_words` SET `content_loc5`='How could you kill poor old Joe? And why did you bring the meat back?' WHERE `word_id` = 8332; -- db_script_string - content : entry=2000001072
UPDATE `trans_words` SET `content_loc5`='How dare you take my eye! I will crush your soul and feed it to my blind and wimpering imps!' WHERE `word_id` = 8009; -- db_script_string - content : entry=2000000840
UPDATE `trans_words` SET `content_loc5`='How dare you trifle with my playthings!' WHERE `word_id` = 6543; -- db_script_string - content : entry=2000000968
UPDATE `trans_words` SET `content_loc5`='Hullo, Trias clan! A ball of your smoked mozzarella, if you please!' WHERE `word_id` = 7023; -- db_script_string - content : entry=2000000336
UPDATE `trans_words` SET `content_loc5`='I AM A GOD OF DEMONS' WHERE `word_id` = 8669; -- db_script_string - content : entry=2000000147
UPDATE `trans_words` SET `content_loc5`='I am free! I ask the spirit of fire back to us so that my people have found the courage to fight with the owners! Thank you, $R.' WHERE `word_id` = 8754; -- db_script_string - content : entry=2000001202
UPDATE `trans_words` SET `content_loc5`='I am free! Spirit of the water back to my people. It will bring us the wisdom that is necessary for survival in this harsh land. I am in your duty, $N.' WHERE `word_id` = 8753; -- db_script_string - content : entry=2000001201
UPDATE `trans_words` SET `content_loc5`='I believe the Forsaken are misleading the allies of the Horde... wait... I feel so... dizzy...' WHERE `word_id` = 6995; -- db_script_string - content : entry=2000000283
UPDATE `trans_words` SET `content_loc5`='I built a few control panels below the slope. Quickly borrow one and take control Fel Reaver! You have a little time.' WHERE `word_id` = 8734; -- db_script_string - content : entry=2000001080
UPDATE `trans_words` SET `content_loc5`='I can\'t belive you imbeciles went to school for this! Does anybody here know what they\'re doing?' WHERE `word_id` = 7976; -- db_script_string - content : entry=2000000745
UPDATE `trans_words` SET `content_loc5`='I cut the horn, but before you put on it the traditional carving, make sure it works. You will help me test it?' WHERE `word_id` = 8359; -- db_script_string - content : entry=2000001038
UPDATE `trans_words` SET `content_loc5`='I FEEL DEATH ALONGSIDE' WHERE `word_id` = 7546; -- db_script_string - content : entry=2000000236
UPDATE `trans_words` SET `content_loc5`='I FEEL THE FRIED MEAT' WHERE `word_id` = 8639; -- db_script_string - content : entry=2000000227
UPDATE `trans_words` SET `content_loc5`='I guess I\'ll go find the athorities. If I\'m lucky they\'ll tell me it\'s the plague and that we\'re all going to die.' WHERE `word_id` = 8190; -- db_script_string - content : entry=2000001161
UPDATE `trans_words` SET `content_loc5`='I had arranged for a secret summit between Warchief Thrall and King Wyrnn, here in Theramore.' WHERE `word_id` = 8394; -- db_script_string - content : entry=2000001000
UPDATE `trans_words` SET `content_loc5`='I have created the totem. You, $N, must cleanse the well.' WHERE `word_id` = 7711; -- db_script_string - content : entry=2000000425
UPDATE `trans_words` SET `content_loc5`='I knew!' WHERE `word_id` = 8500; -- db_script_string - content : entry=2000000499
UPDATE `trans_words` SET `content_loc5`='I know you are there, rougue, Leave my home or join the others at the bottom of the world tree.' WHERE `word_id` = 8648; -- db_script_string - content : entry=2000000196
UPDATE `trans_words` SET `content_loc5`='I need to consult Noram and Horatio.' WHERE `word_id` = 6950; -- db_script_string - content : entry=2000000070
UPDATE `trans_words` SET `content_loc5`='I raise my brew and hope to be rid of the likes of you! Cheers, you no good scoundrel, $N!' WHERE `word_id` = 7690; -- db_script_string - content : entry=2000000247
UPDATE `trans_words` SET `content_loc5`='I shall use this time wisely, milord. Thank you.' WHERE `word_id` = 7235; -- db_script_string - content : entry=2000000990
UPDATE `trans_words` SET `content_loc5`='I swear, people have actualy seen them. Pandaren really do exist!!' WHERE `word_id` = 7096; -- db_script_string - content : entry=2000000169
UPDATE `trans_words` SET `content_loc5`='I thank you, $N. And my brother thanks you.' WHERE `word_id` = 8280; -- db_script_string - content : entry=2000000886
UPDATE `trans_words` SET `content_loc5`='I think I hear that he was already in progress.' WHERE `word_id` = 8738; -- db_script_string - content : entry=2000001084
UPDATE `trans_words` SET `content_loc5`='I think, I\'ll be able to get to Brackenwall. The cargo they carried to the top of the towers. Be careful!' WHERE `word_id` = 8726; -- db_script_string - content : entry=2000000022
UPDATE `trans_words` SET `content_loc5`='I want to see the Tower of the mages' WHERE `word_id` = 8650; -- db_script_string - content : entry=2000000191
UPDATE `trans_words` SET `content_loc5`='I WICKED OGR' WHERE `word_id` = 7545; -- db_script_string - content : entry=2000000235
UPDATE `trans_words` SET `content_loc5`='I WILL DESTROY ALL' WHERE `word_id` = 7483; -- db_script_string - content : entry=2000000149
UPDATE `trans_words` SET `content_loc5`='I WILL DESTROY YOU ALL' WHERE `word_id` = 8638; -- db_script_string - content : entry=2000000238
UPDATE `trans_words` SET `content_loc5`='I will do my best to take care of the children, Grandmother.' WHERE `word_id` = 7481; -- db_script_string - content : entry=2000000203
UPDATE `trans_words` SET `content_loc5`='I will send word that you have discovered the link to the Defias. $B$BI was a fool to think them broken with the defeat of Edwin Vancleef, and King Wrynn will want to make an example of all who remain."' WHERE `word_id` = 268229; -- db_script_string - content : entry=2000001004
UPDATE `trans_words` SET `content_loc5`='I WILL TAKE ALL LIFES' WHERE `word_id` = 8640; -- db_script_string - content : entry=2000000226
UPDATE `trans_words` SET `content_loc5`='I wonder how many reinforcements need to suffer injury before they allows us to chop down these idiotic trees. They\'re costing us a fortune in bats. Maybe I\'ll rig a harness or two...' WHERE `word_id` = 8519; -- db_script_string - content : entry=2000000469
UPDATE `trans_words` SET `content_loc5`='I, of course, can find application of the mixture...' WHERE `word_id` = 8385; -- db_script_string - content : entry=2000001009
UPDATE `trans_words` SET `content_loc5`='I... We are powerless. Illidan found and delivered unto the Dragonmaw their leader - Zuluhed. This orc was the one responsible for the capture and incarceration of Alexstrasza. How could we fight against such power?' WHERE `word_id` = 8689; -- db_script_string - content : entry=2000000116
UPDATE `trans_words` SET `content_loc5`='I\'m listening..' WHERE `word_id` = 8030; -- db_script_string - content : entry=2000000936
UPDATE `trans_words` SET `content_loc5`='I\'m surrounded by idiots.' WHERE `word_id` = 7969; -- db_script_string - content : entry=2000005274
UPDATE `trans_words` SET `content_loc5`='If\'n it weren\'t fer me, that lot wouldn\'t know what water looks like.' WHERE `word_id` = 8659; -- db_script_string - content : entry=2000000162
UPDATE `trans_words` SET `content_loc5`='In addition, my analysis links each Elder to an increase in Freya spell-casting, physical or summoning capabilities.' WHERE `word_id` = 8589; -- db_script_string - content : entry=2000000368
UPDATE `trans_words` SET `content_loc5`='Information that you\'re looking for ... I can not make them just so. Prove that we have common enemies.' WHERE `word_id` = 8370; -- db_script_string - content : entry=2000001024
UPDATE `trans_words` SET `content_loc5`='Ironforge is under reliable protection!' WHERE `word_id` = 8676; -- db_script_string - content : entry=2000000142
UPDATE `trans_words` SET `content_loc5`='Is it done yet? What is talking so damned long?' WHERE `word_id` = 7977; -- db_script_string - content : entry=2000000746
UPDATE `trans_words` SET `content_loc5`='Iskalder? You fool! Have you no idea who that is? He\'s only the greatest vrykul warrior who ever lived!' WHERE `word_id` = 6921; -- db_script_string - content : entry=2000000629
UPDATE `trans_words` SET `content_loc5`='It is time to force your final challenge young warriors! Prepare for your hardest fight yet.' WHERE `word_id` = 7559; -- db_script_string - content : entry=2000000703
UPDATE `trans_words` SET `content_loc5`='It was he who commanded the children of iron in their war against us.' WHERE `word_id` = 8708; -- db_script_string - content : entry=2000000080
UPDATE `trans_words` SET `content_loc5`='It\'s 428,000 degrees Kraklenheit... What\'s happening, hot stuff?' WHERE `word_id` = 8787; -- db_script_string - content : entry=2000001117
UPDATE `trans_words` SET `content_loc5`='It\'s all here... how the raven\'s followers captured and subdued the sprints of rivals, trapping them forever within stone statues! The tablet even mentions the raven god\'s name -- Anzu. I\'d thought it was lost to history!' WHERE `word_id` = 7581; -- db_script_string - content : entry=2000000003
UPDATE `trans_words` SET `content_loc5`='It\'s good that I managed to make copies of the Felsworn Gas Mask...' WHERE `word_id` = 7804; -- db_script_string - content : entry=2000001204
UPDATE `trans_words` SET `content_loc5`='Keep moving!' WHERE `word_id` = 7608; -- db_script_string - content : entry=2000000132
UPDATE `trans_words` SET `content_loc5`='Kill them all, $N!' WHERE `word_id` = 8348; -- db_script_string - content : entry=2000001052
UPDATE `trans_words` SET `content_loc5`='Leave me.' WHERE `word_id` = 8491; -- db_script_string - content : entry=2000000508
UPDATE `trans_words` SET `content_loc5`='Let us learn the truth. If between us hides a murderer, and indicate the correct direction for searches.' WHERE `word_id` = 8350; -- db_script_string - content : entry=2000001054
UPDATE `trans_words` SET `content_loc5`='Listen, the death knight ... attend to the voice of his master! He is calling you!' WHERE `word_id` = 8345; -- db_script_string - content : entry=2000001058
UPDATE `trans_words` SET `content_loc5`='listens to the report $N...' WHERE `word_id` = 8347; -- db_script_string - content : entry=2000001055
UPDATE `trans_words` SET `content_loc5`='Look around, $N. Maybe you\'ll see something that I missed.' WHERE `word_id` = 8777; -- db_script_string - content : entry=2000001235
UPDATE `trans_words` SET `content_loc5`='look at Fort Bleeding Hollow Zet\'gor...' WHERE `word_id` = 8751; -- db_script_string - content : entry=2000001098
UPDATE `trans_words` SET `content_loc5`='Look out! More are coming!' WHERE `word_id` = 7597; -- db_script_string - content : entry=2000000119
UPDATE `trans_words` SET `content_loc5`='Look! Minions of Terokk are approaching!' WHERE `word_id` = 7596; -- db_script_string - content : entry=2000000120
UPDATE `trans_words` SET `content_loc5`='Lovely song, ain\'t it?' WHERE `word_id` = 8725; -- db_script_string - content : entry=2000000021
UPDATE `trans_words` SET `content_loc5`='Meal, drinks!' WHERE `word_id` = 8677; -- db_script_string - content : entry=2000000139
UPDATE `trans_words` SET `content_loc5`='Measuring by Kraklenheit, it is 428,000 dewgrees! That\'s Krakley!' WHERE `word_id` = 8788; -- db_script_string - content : entry=2000001118
UPDATE `trans_words` SET `content_loc5`='Mental interference from this presence dangerously close from triggering partial memory damage.' WHERE `word_id` = 8572; -- db_script_string - content : entry=2000000382
UPDATE `trans_words` SET `content_loc5`='Metal lost its magic. I could make out his weapon, but it will not differ from the conventional blade.' WHERE `word_id` = 8371; -- db_script_string - content : entry=2000001023
UPDATE `trans_words` SET `content_loc5`='My blade - Orcs head down !!' WHERE `word_id` = 8666; -- db_script_string - content : entry=2000000153
UPDATE `trans_words` SET `content_loc5`='My feet hurt badly.' WHERE `word_id` = 8649; -- db_script_string - content : entry=2000000193
UPDATE `trans_words` SET `content_loc5`='My gratitude knows no bounds, $N. Finally I was able to leave the tower and freed from the shackles of bad magic, Kael!' WHERE `word_id` = 8740; -- db_script_string - content : entry=2000001086
UPDATE `trans_words` SET `content_loc5`='My pleasure, sugar drop. I\'ll be back soon:' WHERE `word_id` = 8608; -- db_script_string - content : entry=2000000325
UPDATE `trans_words` SET `content_loc5`='nervously look.' WHERE `word_id` = 8376; -- db_script_string - content : entry=2000001017
UPDATE `trans_words` SET `content_loc5`='No! As the ritual could be broken?' WHERE `word_id` = 8741; -- db_script_string - content : entry=2000001087
UPDATE `trans_words` SET `content_loc5`='No! Get away from me! Help!' WHERE `word_id` = 8782; -- db_script_string - content : entry=2000000098
UPDATE `trans_words` SET `content_loc5`='No, take that, $N! My will is already so weakened because of his dark power. Take it and kill it Varedis!' WHERE `word_id` = 8733; -- db_script_string - content : entry=2000001079
UPDATE `trans_words` SET `content_loc5`='No,not so.What happened here?' WHERE `word_id` = 8372; -- db_script_string - content : entry=2000001022
UPDATE `trans_words` SET `content_loc5`='NOBODY WILL GET THROUGH ME' WHERE `word_id` = 7548; -- db_script_string - content : entry=2000000239
UPDATE `trans_words` SET `content_loc5`='Not a challenge at all it seems. Let us see how hou handle your second test. Lysta, bring forth the minions of the Lich King.' WHERE `word_id` = 7561; -- db_script_string - content : entry=2000000701
UPDATE `trans_words` SET `content_loc5`='Now for that snack:' WHERE `word_id` = 8606; -- db_script_string - content : entry=2000000335
UPDATE `trans_words` SET `content_loc5`='Now get out of my way, it\'s time to send the Burning Legion back to the nether!' WHERE `word_id` = 7504; -- db_script_string - content : entry=2000000863
UPDATE `trans_words` SET `content_loc5`='Of course, Brann: We will have the shield down momentarily.' WHERE `word_id` = 8142; -- db_script_string - content : entry=2000001106
UPDATE `trans_words` SET `content_loc5`='Of course, Paige. But be nice.' WHERE `word_id` = 8656; -- db_script_string - content : entry=2000000185
UPDATE `trans_words` SET `content_loc5`='Ograbisi needs new hat.' WHERE `word_id` = 7360; -- db_script_string - content : entry=2000000807
UPDATE `trans_words` SET `content_loc5`='Oh my precious! Did the big, mean whale hurt you? It\'ll be ok. I\'ll never let you out of my sight again!' WHERE `word_id` = 8513; -- db_script_string - content : entry=2000000483
UPDATE `trans_words` SET `content_loc5`='Oh no! Here they come!' WHERE `word_id` = 7207; -- db_script_string - content : entry=2000000955
UPDATE `trans_words` SET `content_loc5`='Oh sweet, delicious, spotted eggs - you will be mine...' WHERE `word_id` = 7573; -- db_script_string - content : entry=2000000684
UPDATE `trans_words` SET `content_loc5`='Oh, no ... not worked! Somehow I feel ... easier.' WHERE `word_id` = 8756; -- db_script_string - content : entry=2000001210
UPDATE `trans_words` SET `content_loc5`='OK, $N, begin. Fingers crossed arms, legs, eyes, and that you are there you can still cross!...' WHERE `word_id` = 8755; -- db_script_string - content : entry=2000001209
UPDATE `trans_words` SET `content_loc5`='Ok, let\'s get started!' WHERE `word_id` = 7422; -- db_script_string - content : entry=2000000266
UPDATE `trans_words` SET `content_loc5`='Okay! Let\'s move out. Get into your machines; I\'ll speak to you from here via the radio.' WHERE `word_id` = 8143; -- db_script_string - content : entry=2000001107
UPDATE `trans_words` SET `content_loc5`='Only if we did not follow the proper initialization procedures.' WHERE `word_id` = 7524; -- db_script_string - content : entry=2000005150
UPDATE `trans_words` SET `content_loc5`='Onu is struck by unleashed magic!' WHERE `word_id` = 6982; -- db_script_string - content : entry=2000000250
UPDATE `trans_words` SET `content_loc5`='Onu studies the parchment from the Twilight Tome...' WHERE `word_id` = 6983; -- db_script_string - content : entry=2000000249
UPDATE `trans_words` SET `content_loc5`='Pentarus, you heard the man. Have your mages release the shield and let these brave souls through!' WHERE `word_id` = 8141; -- db_script_string - content : entry=2000001105
UPDATE `trans_words` SET `content_loc5`='People of Stormwind! Citizens Alliance! Listen to your king!' WHERE `word_id` = 8745; -- db_script_string - content : entry=2000001091
UPDATE `trans_words` SET `content_loc5`='Perhaps I choose this horn. Now you only have to cut it properly! Maybe it will not be easy. Because I did not even know how to grab the female yeti!' WHERE `word_id` = 8360; -- db_script_string - content : entry=2000001037
UPDATE `trans_words` SET `content_loc5`='Perry Gatner! What an act! The cantina is open all night long, so please, stay and enjoy yourselves!' WHERE `word_id` = 7550; -- db_script_string - content : entry=2000000457
UPDATE `trans_words` SET `content_loc5`='Please! I must feed on something soon... A mana crystal... a shard... anything! The pain is unbearable!' WHERE `word_id` = 7476; -- db_script_string - content : entry=2000000218
UPDATE `trans_words` SET `content_loc5`='Please, mortal, speak with Arcanist Tubalin in Dalaran. He may be able to negotiate with the Sunreavers for access to the book.' WHERE `word_id` = 8714; -- db_script_string - content : entry=2000000057
UPDATE `trans_words` SET `content_loc5`='Prime Desigate? Where have I \'eard that before? By my grandfather\'s beard, Loken is Azeroth\'s Prime Designate. Loken\'s death triggered this!' WHERE `word_id` = 8568; -- db_script_string - content : entry=2000000388
UPDATE `trans_words` SET `content_loc5`='Prizes! Get your prizes right here! Get over here and turn in your Darkmoon Faire Prize Tickets for valuable prizes!' WHERE `word_id` = 7471; -- db_script_string - content : entry=2000000157
UPDATE `trans_words` SET `content_loc5`='Probability of successful repair by ordinary means available in this world is close to nil. Please hold while theoretical means analyzed.' WHERE `word_id` = 8594; -- db_script_string - content : entry=2000000361
UPDATE `trans_words` SET `content_loc5`='read the latest entry in the Brann journal.' WHERE `word_id` = 8762; -- db_script_string - content : entry=2000001217
UPDATE `trans_words` SET `content_loc5`='Release me immediatley or face my wrath!' WHERE `word_id` = 8059; -- db_script_string - content : entry=2000000890
UPDATE `trans_words` SET `content_loc5`='Remember, $N, bloodspore powder can be used to weaken all magnataurs in Gammothra.' WHERE `word_id` = 8369; -- db_script_string - content : entry=2000001025
UPDATE `trans_words` SET `content_loc5`='Remember, $N, this is not the sprint. This verification of the hunter - is a test of endurance for a long expedition.' WHERE `word_id` = 8356; -- db_script_string - content : entry=2000001041
UPDATE `trans_words` SET `content_loc5`='Request denied. Reply-codes built into Algalon observer entity. He is both messenger and message.' WHERE `word_id` = 8556; -- db_script_string - content : entry=2000000399
UPDATE `trans_words` SET `content_loc5`='Rest now, Adaris. You need to recover your strength.' WHERE `word_id` = 7728; -- db_script_string - content : entry=2000000448
UPDATE `trans_words` SET `content_loc5`='Return to him. Return to Mehlor and tell him that I forgive him and that I understand why he believes what he does.' WHERE `word_id` = 7811; -- db_script_string - content : entry=2000000815
UPDATE `trans_words` SET `content_loc5`='Right. We just busted our tails to haul all of this stuff up here, and you want us to work more?' WHERE `word_id` = 7494; -- db_script_string - content : entry=2000000207
UPDATE `trans_words` SET `content_loc5`='Rise, Sindragosa! Rise and lead the Frostbrood into war!' WHERE `word_id` = 8523; -- db_script_string - content : entry=2000000452
UPDATE `trans_words` SET `content_loc5`='Sarath fades into the mist...' WHERE `word_id` = 7427; -- db_script_string - content : entry=2000000258
UPDATE `trans_words` SET `content_loc5`='shown on The Mind\'s Eye and Singing Crystals...' WHERE `word_id` = 8381; -- db_script_string - content : entry=2000001012
UPDATE `trans_words` SET `content_loc5`='Sniff... That\'s the spirit soldier... I only wish we had more soldiers like you in this army. Now go out there and give \'em hell!' WHERE `word_id` = 7503; -- db_script_string - content : entry=2000000864
UPDATE `trans_words` SET `content_loc5`='So, we\'ll see ... If I am not mistaken, it ... Hmm ...' WHERE `word_id` = 8710; -- db_script_string - content : entry=2000000077
UPDATE `trans_words` SET `content_loc5`='So, where were we?' WHERE `word_id` = 8510; -- db_script_string - content : entry=2000000485
UPDATE `trans_words` SET `content_loc5`='Soaring construction vibrates.' WHERE `word_id` = 8434; -- db_script_string - content : entry=2000000667
UPDATE `trans_words` SET `content_loc5`='Soul Gems Yenniku ready, $N...' WHERE `word_id` = 8382; -- db_script_string - content : entry=2000001013
UPDATE `trans_words` SET `content_loc5`='Speak to the commander at your post, lad, and persuade him to abandon Vor\'takh\'s foolish plan.' WHERE `word_id` = 8609; -- db_script_string - content : entry=2000000320
UPDATE `trans_words` SET `content_loc5`='Spirits heard us! You feel, $N?' WHERE `word_id` = 8351; -- db_script_string - content : entry=2000001050
UPDATE `trans_words` SET `content_loc5`='Spirits of Water, I give you praise, and I beg of you a favour. You have heard $N\'s pleas, and I trust his inent is noble. Please, will you aid us?' WHERE `word_id` = 7572; -- db_script_string - content : entry=2000000026
UPDATE `trans_words` SET `content_loc5`='Stop...' WHERE `word_id` = 8338; -- db_script_string - content : entry=2000001060
UPDATE `trans_words` SET `content_loc5`='Stormwind City is under reliable protection!' WHERE `word_id` = 8681; -- db_script_string - content : entry=2000000133
UPDATE `trans_words` SET `content_loc5`='Strange. Very strange...' WHERE `word_id` = 7700; -- db_script_string - content : entry=2000000110
UPDATE `trans_words` SET `content_loc5`='Tactical analysis suggest approaching the arena from the front and splitting secondary force through a side passage at the ground level. This will maximize odds of reaching Thorim\'s outlook before mental domination by external presence is complete.' WHERE `word_id` = 8573; -- db_script_string - content : entry=2000000383
UPDATE `trans_words` SET `content_loc5`='Take a stone from the table. Presently You will need it for your quest.' WHERE `word_id` = 8718; -- db_script_string - content : entry=2000000036
UPDATE `trans_words` SET `content_loc5`='Tanaris is our lend !! ZZzzZZ' WHERE `word_id` = 8663; -- db_script_string - content : entry=2000000156
UPDATE `trans_words` SET `content_loc5`='Tell us! Where does you leader hide?' WHERE `word_id` = 7478; -- db_script_string - content : entry=2000000217
UPDATE `trans_words` SET `content_loc5`='Terenthis begins to cast a spell as you take the cloak from him.' WHERE `word_id` = 7067; -- db_script_string - content : entry=2000000252
UPDATE `trans_words` SET `content_loc5`='Terenthis begins to cast a spell on Grimclaw.' WHERE `word_id` = 7189; -- db_script_string - content : entry=2000000829
UPDATE `trans_words` SET `content_loc5`='Thank you again, $N. This rare earth will be very helpful in my experiments.' WHERE `word_id` = 6965; -- db_script_string - content : entry=2000000049
UPDATE `trans_words` SET `content_loc5`='Thank you for freeing us, mortals. Beware, the Blue Flight is alerted to your presence. Even now, Malygos sends Varos Cloudstrider and his ring guardians to defend the Oculus. You will need our help to stand a chance.' WHERE `word_id` = 8107; -- db_script_string - content : entry=2000000876
UPDATE `trans_words` SET `content_loc5`='Thank you great spirit. Thank you!' WHERE `word_id` = 6973; -- db_script_string - content : entry=2000000016
UPDATE `trans_words` SET `content_loc5`='Thank you! I could have not held out for much longer. A terrible thing has happened here.' WHERE `word_id` = 4071; -- db_script_string - content : entry=2000000868
UPDATE `trans_words` SET `content_loc5`='Thank you, $N. And luck to you.' WHERE `word_id` = 7184; -- db_script_string - content : entry=2000000657
UPDATE `trans_words` SET `content_loc5`='Thank you, Charys. Let us go Paige, my angel.' WHERE `word_id` = 8652; -- db_script_string - content : entry=2000000186
UPDATE `trans_words` SET `content_loc5`='Thank you, mortal, for freeing me from this curse. I beg you, take this blade' WHERE `word_id` = 8445; -- db_script_string - content : entry=2000000603
UPDATE `trans_words` SET `content_loc5`='Thank you. I thought I was going to die.' WHERE `word_id` = 7625; -- db_script_string - content : entry=2000000455
UPDATE `trans_words` SET `content_loc5`='That\'s interesting...' WHERE `word_id` = 6949; -- db_script_string - content : entry=2000000069
UPDATE `trans_words` SET `content_loc5`='The back walls are completely blown out!' WHERE `word_id` = 8644; -- db_script_string - content : entry=2000000223
UPDATE `trans_words` SET `content_loc5`='The boss wants all hands on high alert. The rusty anchor sinks tonight.' WHERE `word_id` = 7225; -- db_script_string - content : entry=2000000818
UPDATE `trans_words` SET `content_loc5`='The commander of the forces on the ground here is a cruel brute named Zarithrian. But I fear there are greater powers at work.' WHERE `word_id` = 4076; -- db_script_string - content : entry=2000000873
UPDATE `trans_words` SET `content_loc5`='The enemy won`t pass!' WHERE `word_id` = 8679; -- db_script_string - content : entry=2000000134
UPDATE `trans_words` SET `content_loc5`='The forest is located on the western side of the Wintergrasp. Search tractile heart shadow. No doubt they will be glad to your arrival ...' WHERE `word_id` = 8352; -- db_script_string - content : entry=2000001051
UPDATE `trans_words` SET `content_loc5`='The four watchers of Ulduar: Freya, Thorim, Hodir and Mimiron. The sigils are tied to their physical and mental integrity. All four sigils are required for access to the Celestial Planetarium.' WHERE `word_id` = 8546; -- db_script_string - content : entry=2000000409
UPDATE `trans_words` SET `content_loc5`='The introduction of the runes "Omega" is completed. Activation was successful.' WHERE `word_id` = 8729; -- db_script_string - content : entry=2000001075
UPDATE `trans_words` SET `content_loc5`='The Lorehammer ist reacting. This must be from Stormhoof\'s time.' WHERE `word_id` = 7787; -- db_script_string - content : entry=2000000614
UPDATE `trans_words` SET `content_loc5`='The mixture! It moves!' WHERE `word_id` = 7747; -- db_script_string - content : entry=2000000712
UPDATE `trans_words` SET `content_loc5`='The orcs in my citadel will drink your blood and dovour you!' WHERE `word_id` = 8034; -- db_script_string - content : entry=2000000969
UPDATE `trans_words` SET `content_loc5`='The ore used in this sample originated deep wihin the crust of Azeroth and was recently unearthed.' WHERE `word_id` = 8625; -- db_script_string - content : entry=2000000306
UPDATE `trans_words` SET `content_loc5`='The Portal will shift slightly. At this point if you cast a binding cantrip you will solidify it in place.' WHERE `word_id` = 7528; -- db_script_string - content : entry=2000005173
UPDATE `trans_words` SET `content_loc5`='The relic burns to nothing. The memories it held are now your own. This city was destroyed by a being not of this world.' WHERE `word_id` = 8410; -- db_script_string - content : entry=2000000789
UPDATE `trans_words` SET `content_loc5`='The relic crumbles to dust. A vision of eight Dark Iron dwarves performing some sort of ritual fills your head.' WHERE `word_id` = 8405; -- db_script_string - content : entry=2000000795
UPDATE `trans_words` SET `content_loc5`='The relic emits a white hot arc of flame. A memory has been gained: A lone Dark Iron dwarf is surrounded by seven corpses, kneeling before a monolith of flame.' WHERE `word_id` = 8403; -- db_script_string - content : entry=2000000793
UPDATE `trans_words` SET `content_loc5`='The Scourge are a blemish upon these pristine lands. By the might of my creators, I will crush every last one of their decrepit bones under my heel.$B$BI want to stop the Scourge as much as you do. How can I help?' WHERE `word_id` = 268232; -- db_script_string - content : entry=2000000241
UPDATE `trans_words` SET `content_loc5`='The sound of hurrying feet rang the cave.' WHERE `word_id` = 8428; -- db_script_string - content : entry=2000000769
UPDATE `trans_words` SET `content_loc5`='The titans did not create life overnight. The process was gradual and required a great deal of experimentation and iteration.$B$BIt is for that reason that highly protected places such as Sholazar Basin exist.$B$BTo ensure the safety of their experimentation sites, the titans created a defense mechanism. Its destructive force is unparalleled however, and I will reveal no more unless you swear your fealty to my cause.$B$BYou can trust me. I am no friend of the Lich King\'s.' WHERE `word_id` = 268231; -- db_script_string - content : entry=2000000242
UPDATE `trans_words` SET `content_loc5`='The warriors of the Scourge, hear my call! This day will bring death scarlet Order! Empty the land! Let permanently settled here death!' WHERE `word_id` = 8343; -- db_script_string - content : entry=2000001059
UPDATE `trans_words` SET `content_loc5`='There is nothing unusual.' WHERE `word_id` = 8341; -- db_script_string - content : entry=2000001063
UPDATE `trans_words` SET `content_loc5`='There we are, $N. The toxin is ready.' WHERE `word_id` = 6988; -- db_script_string - content : entry=2000000273
UPDATE `trans_words` SET `content_loc5`='There\'s something else here, too. After a discription of a bloody battle and the downfall of the raven, there\'s a prophecy. Anzu will haunt the dreams of his enemies, twisting them to affect a return to this world...' WHERE `word_id` = 7582; -- db_script_string - content : entry=2000000002
UPDATE `trans_words` SET `content_loc5`='They call that a weld!..' WHERE `word_id` = 8645; -- db_script_string - content : entry=2000000224
UPDATE `trans_words` SET `content_loc5`='Think of your younglings, Gul\'dan! You will destroy us all!' WHERE `word_id` = 8044; -- db_script_string - content : entry=2000000978
UPDATE `trans_words` SET `content_loc5`='This ... dark ... energy! How is this possible?' WHERE `word_id` = 8731; -- db_script_string - content : entry=2000001077
UPDATE `trans_words` SET `content_loc5`='This book would give me unlimited power over my enemies ... I would ... irresistible!' WHERE `word_id` = 8732; -- db_script_string - content : entry=2000001078
UPDATE `trans_words` SET `content_loc5`='This data will be quite usefull for Project Blue Book. Er, I mean this will be great for my new look. See if you can gather any more data.' WHERE `word_id` = 7541; -- db_script_string - content : entry=2000000234
UPDATE `trans_words` SET `content_loc5`='This is a shiney rock. I\'ll put it in my bucket. Ok, I just need a few more...' WHERE `word_id` = 7292; -- db_script_string - content : entry=2000000575
UPDATE `trans_words` SET `content_loc5`='This is great news! Your efforts have indeed saved us, $N!' WHERE `word_id` = 8633; -- db_script_string - content : entry=2000000298
UPDATE `trans_words` SET `content_loc5`='This is the last time that I buy second-hand equipment from ethereal' WHERE `word_id` = 7466; -- db_script_string - content : entry=2000000691
UPDATE `trans_words` SET `content_loc5`='This must be fixed!' WHERE `word_id` = 8673; -- db_script_string - content : entry=2000000144
UPDATE `trans_words` SET `content_loc5`='This must be fixed..' WHERE `word_id` = 8641; -- db_script_string - content : entry=2000000225
UPDATE `trans_words` SET `content_loc5`='This ore can only have been created by a powerful, malevolent force. Attempting to access databanks for more information...' WHERE `word_id` = 8623; -- db_script_string - content : entry=2000000308
UPDATE `trans_words` SET `content_loc5`='This will never do..' WHERE `word_id` = 8671; -- db_script_string - content : entry=2000000145
UPDATE `trans_words` SET `content_loc5`='This would be lame Joe did not ask! But - yes, I know Loken.' WHERE `word_id` = 8706; -- db_script_string - content : entry=2000000082
UPDATE `trans_words` SET `content_loc5`='Tickets! Redeem your Darkmoon Faire Prize Tickets here! Wondrous and exotic prizes are waiting for you!' WHERE `word_id` = 7534; -- db_script_string - content : entry=2000000229
UPDATE `trans_words` SET `content_loc5`='Time to get back to the shop:' WHERE `word_id` = 8605; -- db_script_string - content : entry=2000000342
UPDATE `trans_words` SET `content_loc5`='Time to hightail it! Thanks, friend!' WHERE `word_id` = 8426; -- db_script_string - content : entry=2000000773
UPDATE `trans_words` SET `content_loc5`='Today is the first of many defeats the Scourge! Death Knight, who once served as Lich King, broke out of its fatal grip and formed a new alliance to resist his tyranny!' WHERE `word_id` = 8746; -- db_script_string - content : entry=2000001092
UPDATE `trans_words` SET `content_loc5`='Tonga Runetotem inspects the snapjaw shells...' WHERE `word_id` = 7698; -- db_script_string - content : entry=2000000108
UPDATE `trans_words` SET `content_loc5`='tries to open the wooden leg Maury...' WHERE `word_id` = 8384; -- db_script_string - content : entry=2000001011
UPDATE `trans_words` SET `content_loc5`='Trigger for self-destruct mechanism is code named "Big Red Button". Mimiron\'s own creation.' WHERE `word_id` = 8578; -- db_script_string - content : entry=2000000377
UPDATE `trans_words` SET `content_loc5`='Uhh.. Nice girl !!' WHERE `word_id` = 8664; -- db_script_string - content : entry=2000000155
UPDATE `trans_words` SET `content_loc5`='Unbelievable! It says that Brann discovered a mysterious slab, covered with runes, in the depths of Thor Modan!' WHERE `word_id` = 8763; -- db_script_string - content : entry=2000001218
UPDATE `trans_words` SET `content_loc5`='US ALREADY ALL ANYMORE AND ANYMORE' WHERE `word_id` = 7484; -- db_script_string - content : entry=2000000150
UPDATE `trans_words` SET `content_loc5`='Volcor was gone?' WHERE `word_id` = 6940; -- db_script_string - content : entry=2000000052
UPDATE `trans_words` SET `content_loc5`='Watcher Mimiron\'s sigil is linked to a self-destruct mechanism connected to entirety of the Corridors of Ingenuity.' WHERE `word_id` = 8581; -- db_script_string - content : entry=2000000376
UPDATE `trans_words` SET `content_loc5`='Watcher\'s powers augmented by presence of Elder servants.' WHERE `word_id` = 8591; -- db_script_string - content : entry=2000000364
UPDATE `trans_words` SET `content_loc5`='We believed that the Sanctum was well fortified, but we were not prepareted for the nature of this assault.' WHERE `word_id` = 4072; -- db_script_string - content : entry=2000000869
UPDATE `trans_words` SET `content_loc5`='We did not stand a chance. As my brethren perished around me, I managed to retreat hear and bar the entrance.' WHERE `word_id` = 4074; -- db_script_string - content : entry=2000000871
UPDATE `trans_words` SET `content_loc5`='We have a winner! $N is the Master Angler!' WHERE `word_id` = 8627; -- db_script_string - content : entry=2000000302
UPDATE `trans_words` SET `content_loc5`='We have gone! Thanks!' WHERE `word_id` = 8702; -- db_script_string - content : entry=2000000087
UPDATE `trans_words` SET `content_loc5`='We will act when we know what we need, old friend. The druids have proven wise and capable of making their own decisions.' WHERE `word_id` = 7942; -- db_script_string - content : entry=2000005247
UPDATE `trans_words` SET `content_loc5`='Welcom to piratet Harbor !!' WHERE `word_id` = 8668; -- db_script_string - content : entry=2000000151
UPDATE `trans_words` SET `content_loc5`='Welcome one and all to the Darkmoon Faire, the greatest event in all the worlds! We have it all... delicious food, strong drinks, exotic artifacts, fortunes read, amazing prizes and excitement without end! Don\'t forget to turn in your Darkmoon Faire Prize Tickets to Gelvas Grimegate! All it takes is five or more and you\'re on your way to the most wondrous prizes in all of Outland. Everybody is a winner' WHERE `word_id` = 7475; -- db_script_string - content : entry=2000000199
UPDATE `trans_words` SET `content_loc5`='Welcome to Honor Hold, $N. It\'s good that you are with us!' WHERE `word_id` = 8748; -- db_script_string - content : entry=2000001095
UPDATE `trans_words` SET `content_loc5`='Well hand it overand let\'s see what you got!' WHERE `word_id` = 7490; -- db_script_string - content : entry=2000000204
UPDATE `trans_words` SET `content_loc5`='Well, a little tweak here, a little set up here ...' WHERE `word_id` = 8768; -- db_script_string - content : entry=2000001223
UPDATE `trans_words` SET `content_loc5`='Well, he will not stingy with the drink, if he really wants to see my people abandoned their studies and started working on the military!' WHERE `word_id` = 8761; -- db_script_string - content : entry=2000001216
UPDATE `trans_words` SET `content_loc5`='Well, I am off than. Take care, Harlan!' WHERE `word_id` = 7021; -- db_script_string - content : entry=2000000334
UPDATE `trans_words` SET `content_loc5`='Well, if you had come to kill me, you could at least wait until I feed Griselda? Poor girl had not eaten for several days.' WHERE `word_id` = 8335; -- db_script_string - content : entry=2000001070
UPDATE `trans_words` SET `content_loc5`='Well, ok. I am now sending people . We need find and help him.' WHERE `word_id` = 6942; -- db_script_string - content : entry=2000000050
UPDATE `trans_words` SET `content_loc5`='Well, that should do it. Come now, back to the shop to finish our business!' WHERE `word_id` = 6976; -- db_script_string - content : entry=2000000011
UPDATE `trans_words` SET `content_loc5`='Well, then how, yes? I will not surrender without a fight!' WHERE `word_id` = 8599; -- db_script_string - content : entry=2000000353
UPDATE `trans_words` SET `content_loc5`='What a crazy crowd! You really believe in this nonsense?' WHERE `word_id` = 8776; -- db_script_string - content : entry=2000001234
UPDATE `trans_words` SET `content_loc5`='What happens?' WHERE `word_id` = 6939; -- db_script_string - content : entry=2000000053
UPDATE `trans_words` SET `content_loc5`='What is the force passes through me? Maybe it is the power of shamanism, which talked about Tor\'gan? ..' WHERE `word_id` = 8388; -- db_script_string - content : entry=2000001006
UPDATE `trans_words` SET `content_loc5`='What? How dare you say that to me?!?' WHERE `word_id` = 7205; -- db_script_string - content : entry=2000000957
UPDATE `trans_words` SET `content_loc5`='What?! Flaming Blade extends the sphere of influence?! We need to explore what\'s what!' WHERE `word_id` = 8346; -- db_script_string - content : entry=2000001056
UPDATE `trans_words` SET `content_loc5`='What\'s this!' WHERE `word_id` = 8503; -- db_script_string - content : entry=2000000497
UPDATE `trans_words` SET `content_loc5`='When my change will come.. there is my wife and children...' WHERE `word_id` = 8680; -- db_script_string - content : entry=2000000138
UPDATE `trans_words` SET `content_loc5`='When we arrive ?' WHERE `word_id` = 8653; -- db_script_string - content : entry=2000000187
UPDATE `trans_words` SET `content_loc5`='Where do you think you are going soldier? Those are fatal wounds you\'ve got there. Now, get back in tent and let the nurse treat you!' WHERE `word_id` = 7505; -- db_script_string - content : entry=2000000862
UPDATE `trans_words` SET `content_loc5`='WHERE MY FORCES OF DEMONS' WHERE `word_id` = 8670; -- db_script_string - content : entry=2000000148
UPDATE `trans_words` SET `content_loc5`='Where we going ?' WHERE `word_id` = 8654; -- db_script_string - content : entry=2000000188
UPDATE `trans_words` SET `content_loc5`='Where\'s the water, Emma? Get the water, Emma?' WHERE `word_id` = 8661; -- db_script_string - content : entry=2000000161
UPDATE `trans_words` SET `content_loc5`='Who dares step into my domain! Come! Come, and be consumed!' WHERE `word_id` = 7203; -- db_script_string - content : entry=2000000960
UPDATE `trans_words` SET `content_loc5`='Who disturbs my slumber? That spear... I still carry the scar!' WHERE `word_id` = 8412; -- db_script_string - content : entry=2000000787
UPDATE `trans_words` SET `content_loc5`='Who? The Tauren Chieftains! What? A live performance. Where? The World\'s End Tavern! When? The top of the hour! BE THERE!' WHERE `word_id` = 7439; -- db_script_string - content : entry=2000000461
UPDATE `trans_words` SET `content_loc5`='Why do you do this? Did I somehow wrong you in life?' WHERE `word_id` = 7809; -- db_script_string - content : entry=2000000813
UPDATE `trans_words` SET `content_loc5`='Why we going by there ?' WHERE `word_id` = 8655; -- db_script_string - content : entry=2000000189
UPDATE `trans_words` SET `content_loc5`='With the return of the world starts looking for answers!' WHERE `word_id` = 8758; -- db_script_string - content : entry=2000001212
UPDATE `trans_words` SET `content_loc5`='Worm goes on the hook, hook goes in the water, Fish is in the water, our fish.' WHERE `word_id` = 7104; -- db_script_string - content : entry=2000000177
UPDATE `trans_words` SET `content_loc5`='Would never have thought that this oil will be mana! Oh, it is all you need, except the Grek, of course.' WHERE `word_id` = 8374; -- db_script_string - content : entry=2000001020
UPDATE `trans_words` SET `content_loc5`='Wow! $N, that dream dust is powerful stuff!' WHERE `word_id` = 7217; -- db_script_string - content : entry=2000000280
UPDATE `trans_words` SET `content_loc5`='Wow, all this for a love potion. Hope he is worth it.' WHERE `word_id` = 7527; -- db_script_string - content : entry=2000005171
UPDATE `trans_words` SET `content_loc5`='Yer wearin down, princess, I can sense it!' WHERE `word_id` = 7530; -- db_script_string - content : entry=2000000165
UPDATE `trans_words` SET `content_loc5`='Yes glorify $N! He saved the city from the Burning Legion!' WHERE `word_id` = 8743; -- db_script_string - content : entry=2000001089
UPDATE `trans_words` SET `content_loc5`='Yes, he\'s second-in-command of the wyrmcult at the Blackwing Coven to the west.' WHERE `word_id` = 7726; -- db_script_string - content : entry=2000000446
UPDATE `trans_words` SET `content_loc5`='You - a riddle, yes, a real mystery ... Here are ... I\'m not very fond of riddles.' WHERE `word_id` = 8333; -- db_script_string - content : entry=2000001073
UPDATE `trans_words` SET `content_loc5`='You are cordially accept these past heroes of the Alliance and will treat them with respect, that you would almost any ally of Stormwind!' WHERE `word_id` = 8747; -- db_script_string - content : entry=2000001093
UPDATE `trans_words` SET `content_loc5`='You are engulfed in a blinding flash of light. A creature composed entirely of flame is the only thing you can remember seeing.' WHERE `word_id` = 8407; -- db_script_string - content : entry=2000000791
UPDATE `trans_words` SET `content_loc5`='You better go away, while Griselda not wished you a dessert ...' WHERE `word_id` = 8334; -- db_script_string - content : entry=2000001074
UPDATE `trans_words` SET `content_loc5`='You can use it, but do not complain: after repair of the seats can stick teeth of a saw or something like that. What I had - all went to work.' WHERE `word_id` = 8770; -- db_script_string - content : entry=2000001225
UPDATE `trans_words` SET `content_loc5`='You do not know with whom you deal, $C! You play with death!' WHERE `word_id` = 8601; -- db_script_string - content : entry=2000000352
UPDATE `trans_words` SET `content_loc5`='You hear a low guttural growl somewhere.' WHERE `word_id` = 8435; -- db_script_string - content : entry=2000000668
UPDATE `trans_words` SET `content_loc5`='You know where he is?' WHERE `word_id` = 6941; -- db_script_string - content : entry=2000000051
UPDATE `trans_words` SET `content_loc5`='You know why Orcs eyes glow red? It\'s because they drink blood!' WHERE `word_id` = 7097; -- db_script_string - content : entry=2000000170
UPDATE `trans_words` SET `content_loc5`='You need to do what? All this science. I don\'t understand... Look, this is just my job, five days a week.' WHERE `word_id` = 7945; -- db_script_string - content : entry=2000005250
UPDATE `trans_words` SET `content_loc5`='YOU PRAY SERVANTS MY' WHERE `word_id` = 7539; -- db_script_string - content : entry=2000000228
UPDATE `trans_words` SET `content_loc5`='You want to go do the bounty off of this wanted poster after this shift is over?' WHERE `word_id` = 7487; -- db_script_string - content : entry=2000000211
UPDATE `trans_words` SET `content_loc5`='You were right to come. My wisdom will be yours.' WHERE `word_id` = 6986; -- db_script_string - content : entry=2000000271
UPDATE `trans_words` SET `content_loc5`='You will not harm the boy, Mor\'ghor! Quickly, $N, climb on my back!' WHERE `word_id` = 7996; -- db_script_string - content : entry=2000000744
UPDATE `trans_words` SET `content_loc5`='Your body is mine! Our fates are forever intertwined!' WHERE `word_id` = 7595; -- db_script_string - content : entry=2000000579
UPDATE `trans_words` SET `content_loc5`='Zarlman Two-Moons begins chanting as he mixes the well stones and ambercom before the Tribal Fire.' WHERE `word_id` = 7345; -- db_script_string - content : entry=2000000112

SET NAMES 'latin1';
