-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc5`='[PH] SD2 unknown text' WHERE `word_id` = 269446; -- gossip_texts - content : entry=-3000000
UPDATE `trans_words` SET `content_loc5`='<Check for pulse...>' WHERE `word_id` = 127748; -- gossip_texts - content : entry=-3000104
UPDATE `trans_words` SET `content_loc5`='Activate the crystals when we get in trouble, right?' WHERE `word_id` = 127778; -- gossip_texts - content : entry=-3608000
UPDATE `trans_words` SET `content_loc5`='Control Conjured Water Elemental' WHERE `word_id` = 127718; -- gossip_texts - content : entry=-3532014
UPDATE `trans_words` SET `content_loc5`='Control Human Charger' WHERE `word_id` = 127717; -- gossip_texts - content : entry=-3532013
UPDATE `trans_words` SET `content_loc5`='I am ready to travel to you village now.' WHERE `word_id` = 127747; -- gossip_texts - content : entry=-3000103
UPDATE `trans_words` SET `content_loc5`='I\'m ready - let\'s get out of here.' WHERE `word_id` = 127749; -- gossip_texts - content : entry=-3000112
UPDATE `trans_words` SET `content_loc5`='Lead the way, Prince Arthas' WHERE `word_id` = 127800; -- gossip_texts - content : entry=-3595010
UPDATE `trans_words` SET `content_loc5`='Let\'s move Brann, enough of the history lessons!' WHERE `word_id` = 127762; -- gossip_texts - content : entry=-3599001
UPDATE `trans_words` SET `content_loc5`='Taruk send me to collect what you owe.' WHERE `word_id` = 127745; -- gossip_texts - content : entry=-3000101
UPDATE `trans_words` SET `content_loc5`='Teleport me to the Guardian\'s Library' WHERE `word_id` = 127704; -- gossip_texts - content : entry=-3532000
UPDATE `trans_words` SET `content_loc5`='We\'ll get you out. Taretha. Don\'t worry. I doubt the wizard would wander too far away.' WHERE `word_id` = 127736; -- gossip_texts - content : entry=-3560006
UPDATE `trans_words` SET `content_loc5`='We\'ll just have to improve our teamwork to match the two of them.' WHERE `word_id` = 127808; -- gossip_texts - content : entry=-3649016
UPDATE `trans_words` SET `content_loc5`='What phat lewtz you have grandmother?' WHERE `word_id` = 127752; -- gossip_texts - content : entry=-3532005

SET NAMES 'latin1';
