-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc5`='[PH] Get E.C.A.C.' WHERE `word_id`=128451; -- locales_gossip_menu_option - option_text : menu_id=524-id=0
UPDATE `trans_words` SET `content_loc5`='[PH] Get Thieves\' Tools' WHERE `word_id`=128154; -- locales_gossip_menu_option - option_text : menu_id=524-id=1
UPDATE `trans_words` SET `content_loc5`='[PH] I want to deliver prisoner.' WHERE `word_id`=129166; -- locales_gossip_menu_option - option_text : menu_id=9184-id=0
UPDATE `trans_words` SET `content_loc5`='[PH] Learn Ultrasafe Transporter.' WHERE `word_id`=128976; -- locales_gossip_menu_option - option_text : menu_id=8306-id=0
UPDATE `trans_words` SET `content_loc5`='|cFF0008E8NEW|r: Reforging' WHERE `word_id`=129186; -- locales_gossip_menu_option - option_text : menu_id=11969-id=0
UPDATE `trans_words` SET `content_loc5`='|cFF0008E8NEW|r: Transmogrification' WHERE `word_id`=129187; -- locales_gossip_menu_option - option_text : menu_id=11969-id=1
UPDATE `trans_words` SET `content_loc5`='|cFF0008E8NEW|r: Void Storage' WHERE `word_id`=129188; -- locales_gossip_menu_option - option_text : menu_id=11969-id=2
UPDATE `trans_words` SET `content_loc5`='<Call forth Terrok.>' WHERE `word_id`=129073; -- locales_gossip_menu_option - option_text : menu_id=8687-id=0
UPDATE `trans_words` SET `content_loc5`='<Fly to the Dragonhawk in Sun\'s Reach.>' WHERE `word_id`=129401; -- locales_gossip_menu_option - option_text : menu_id=9143-id=0
UPDATE `trans_words` SET `content_loc5`='<listen more>' WHERE `word_id`=129341; -- locales_gossip_menu_option - option_text : menu_id=8090-id=0
UPDATE `trans_words` SET `content_loc5`='<Nod>' WHERE `word_id`=128168; -- locales_gossip_menu_option - option_text : menu_id=5702-id=0
UPDATE `trans_words` SET `content_loc5`='<Pay 10 000 gold.>' WHERE `word_id`=130013; -- locales_gossip_menu_option - option_text : menu_id=57800-id=0
UPDATE `trans_words` SET `content_loc5`='<Put your hand on the sphere.>' WHERE `word_id`=127945; -- locales_gossip_menu_option - option_text : menu_id=6001-id=0
UPDATE `trans_words` SET `content_loc5`='<Remove the bomb from the distributor.>' WHERE `word_id`=129555; -- locales_gossip_menu_option - option_text : menu_id=10211-id=0
UPDATE `trans_words` SET `content_loc5`='<Take control Eidolon Watcher with the Eye of Dominion.>' WHERE `word_id`=129518; -- locales_gossip_menu_option - option_text : menu_id=10028-id=0
UPDATE `trans_words` SET `content_loc5`='<Take control Lithe Stalker through the Eye of Dominion.>' WHERE `word_id`=129537; -- locales_gossip_menu_option - option_text : menu_id=10111-id=0
UPDATE `trans_words` SET `content_loc5`='<Take the letter>' WHERE `word_id`=128038; -- locales_gossip_menu_option - option_text : menu_id=141-id=4
UPDATE `trans_words` SET `content_loc5`='<To feed the worm rocky falcon>' WHERE `word_id`=129393; -- locales_gossip_menu_option - option_text : menu_id=9007-id=0
UPDATE `trans_words` SET `content_loc5`='Acqulre high level data card.' WHERE `word_id`=129177; -- locales_gossip_menu_option - option_text : menu_id=1050-id=0
UPDATE `trans_words` SET `content_loc5`='Acqulre Higher Level Access Card' WHERE `word_id`=129176; -- locales_gossip_menu_option - option_text : menu_id=1045-id=0
UPDATE `trans_words` SET `content_loc5`='Advisor, what are the latest news?' WHERE `word_id`=129320; -- locales_gossip_menu_option - option_text : menu_id=7760-id=0
UPDATE `trans_words` SET `content_loc5`='Alas, my Kor\'kron Flare Gun was lost. You can take both?' WHERE `word_id`=129359; -- locales_gossip_menu_option - option_text : menu_id=8443-id=0
UPDATE `trans_words` SET `content_loc5`='Alchemist, I was covered with samples of the plague!' WHERE `word_id`=129647; -- locales_gossip_menu_option - option_text : menu_id=11032-id=0
UPDATE `trans_words` SET `content_loc5`='Amazing! L\'ve never spoken to a ghost. I wish to learn!' WHERE `word_id`=129182; -- locales_gossip_menu_option - option_text : menu_id=1663-id=0
UPDATE `trans_words` SET `content_loc5`='And so often you earn one?' WHERE `word_id`=129398; -- locales_gossip_menu_option - option_text : menu_id=9084-id=1
UPDATE `trans_words` SET `content_loc5`='And we\'reare going to to disturb them .' WHERE `word_id`=129606; -- locales_gossip_menu_option - option_text : menu_id=10646-id=0
UPDATE `trans_words` SET `content_loc5`='And what is your purpose?' WHERE `word_id`=129343; -- locales_gossip_menu_option - option_text : menu_id=8122-id=0
UPDATE `trans_words` SET `content_loc5`='Any help will be invaluable, the priestess.' WHERE `word_id`=129315; -- locales_gossip_menu_option - option_text : menu_id=7706-id=0
UPDATE `trans_words` SET `content_loc5`='Any idea where they keep the Deathguard Schneider?' WHERE `word_id`=129450; -- locales_gossip_menu_option - option_text : menu_id=9509-id=3
UPDATE `trans_words` SET `content_loc5`='Arcanist Tubalin said you might be able to lend me a certain tabard.' WHERE `word_id`=129620; -- locales_gossip_menu_option - option_text : menu_id=10854-id=0
UPDATE `trans_words` SET `content_loc5`='Arcanist Vandril that here makes these Forsaken?' WHERE `word_id`=129288; -- locales_gossip_menu_option - option_text : menu_id=7153-id=0
UPDATE `trans_words` SET `content_loc5`='Are you sure you wish to purchase a Dual Talent Specialization?' WHERE `word_id` = 129156; -- locales_gossip_menu_option - box_text : menu_id=10371-id=0
UPDATE `trans_words` SET `content_loc5`='Armour' WHERE `word_id`=129544; -- locales_gossip_menu_option - option_text : menu_id=10173-id=0
UPDATE `trans_words` SET `content_loc5`='Ask about the orphan.' WHERE `word_id`=129590; -- locales_gossip_menu_option - option_text : menu_id=10502-id=0
UPDATE `trans_words` SET `content_loc5`='Auction!' WHERE `word_id`=129170; -- locales_gossip_menu_option - option_text : menu_id=0-id=11
UPDATE `trans_words` SET `content_loc5`='Azure Templar! I hold your signet! Heed my call!' WHERE `word_id`=128380; -- locales_gossip_menu_option - option_text : menu_id=6540-id=4
UPDATE `trans_words` SET `content_loc5`='Balandar sent me to get you out of here and pick up his cargo. He is waiting for you in the Brackenwall.' WHERE `word_id`=129297; -- locales_gossip_menu_option - option_text : menu_id=7371-id=0
UPDATE `trans_words` SET `content_loc5`='Baron Kazum! I hold your signet! Heed my call!' WHERE `word_id`=128388; -- locales_gossip_menu_option - option_text : menu_id=6543-id=2
UPDATE `trans_words` SET `content_loc5`='Big?' WHERE `word_id`=129345; -- locales_gossip_menu_option - option_text : menu_id=8172-id=0
UPDATE `trans_words` SET `content_loc5`='Blood gladiators' WHERE `word_id`=129419; -- locales_gossip_menu_option - option_text : menu_id=9197-id=7
UPDATE `trans_words` SET `content_loc5`='Blue tabards' WHERE `word_id`=129411; -- locales_gossip_menu_option - option_text : menu_id=9193-id=0
UPDATE `trans_words` SET `content_loc5`='Bring me back to life' WHERE `word_id`=129168; -- locales_gossip_menu_option - option_text : menu_id=0-id=4
UPDATE `trans_words` SET `content_loc5`='But I have brought here my drilling machine...' WHERE `word_id`=129473; -- locales_gossip_menu_option - option_text : menu_id=9666-id=0
UPDATE `trans_words` SET `content_loc5`='Calm down, I want to ask you about the Iron Dwarves and Loken.' WHERE `word_id`=129088; -- locales_gossip_menu_option - option_text : menu_id=9484-id=2
UPDATE `trans_words` SET `content_loc5`='Can you send me to Theramore? I have an urgent message to Lady Jaina from King Wrynn.' WHERE `word_id`=128748; -- locales_gossip_menu_option - option_text : menu_id=8846-id=0
UPDATE `trans_words` SET `content_loc5`='Can you tell me about this shard?' WHERE `word_id`=127827; -- locales_gossip_menu_option - option_text : menu_id=21-id=1
UPDATE `trans_words` SET `content_loc5`='Captain, I am waiting for your report about the situation.' WHERE `word_id`=129429; -- locales_gossip_menu_option - option_text : menu_id=9285-id=0
UPDATE `trans_words` SET `content_loc5`='Captain, I lost the insignia...' WHERE `word_id`=129387; -- locales_gossip_menu_option - option_text : menu_id=8852-id=0
UPDATE `trans_words` SET `content_loc5`='Cemetary' WHERE `word_id`=129534; -- locales_gossip_menu_option - option_text : menu_id=10056-id=10
UPDATE `trans_words` SET `content_loc5`='Chieftain Ashtotem, I lost the emblem...' WHERE `word_id`=129390; -- locales_gossip_menu_option - option_text : menu_id=8898-id=0
UPDATE `trans_words` SET `content_loc5`='Children\'s Week is not over yet... Can I have one child draenei whistle' WHERE `word_id`=129370; -- locales_gossip_menu_option - option_text : menu_id=8568-id=2
UPDATE `trans_words` SET `content_loc5`='Children\'s Week is not over yet... Can I have one child elf whistle' WHERE `word_id`=129369; -- locales_gossip_menu_option - option_text : menu_id=8568-id=1
UPDATE `trans_words` SET `content_loc5`='Cloth Armor & Clothing' WHERE `word_id`=129543; -- locales_gossip_menu_option - option_text : menu_id=10170-id=0
UPDATE `trans_words` SET `content_loc5`='Cookies for a pet' WHERE `word_id`=129409; -- locales_gossip_menu_option - option_text : menu_id=9191-id=1
UPDATE `trans_words` SET `content_loc5`='Craftsman, I need another banner Warsong Clan' WHERE `word_id`=129405; -- locales_gossip_menu_option - option_text : menu_id=9165-id=0
UPDATE `trans_words` SET `content_loc5`='Crimson Templar! I hold your signet! Heed my call!' WHERE `word_id`=128377; -- locales_gossip_menu_option - option_text : menu_id=6540-id=1
UPDATE `trans_words` SET `content_loc5`='Dalaran Eastern Sewer Entrance' WHERE `word_id`=127382; -- locales_gossip_menu_option - option_text : menu_id=10055-id=0
UPDATE `trans_words` SET `content_loc5`='Dalaran Western Sewer Entrance' WHERE `word_id`=127383; -- locales_gossip_menu_option - option_text : menu_id=10055-id=1
UPDATE `trans_words` SET `content_loc5`='Di17249o Ball' WHERE `word_id`=129470; -- locales_gossip_menu_option - option_text : menu_id=9629-id=1
UPDATE `trans_words` SET `content_loc5`='Do you know where I can find Half Pendant of Aquatic Agility?' WHERE `word_id`=127921; -- locales_gossip_menu_option - option_text : menu_id=4041-id=1
UPDATE `trans_words` SET `content_loc5`='Do you know where I can find Half Pendant of Aquatic Endurance?' WHERE `word_id`=128016; -- locales_gossip_menu_option - option_text : menu_id=4042-id=1
UPDATE `trans_words` SET `content_loc5`='Do you really want to unlearn your alchemy specialty and lose all associated recipes?' WHERE `word_id` = 129015; -- locales_gossip_menu_option - box_text : menu_id=7571-id=1
UPDATE `trans_words` SET `content_loc5`='Do you really want to unlearn your engineer specialty and lose all associated recipes?' WHERE `word_id` = 129278; -- locales_gossip_menu_option - box_text : menu_id=7058-id=2
UPDATE `trans_words` SET `content_loc5`='Do you really want to unlearn your tailoring specialty and lose all associated recipes?' WHERE `word_id` = 129062; -- locales_gossip_menu_option - box_text : menu_id=8530-id=2
UPDATE `trans_words` SET `content_loc5`='Do you really want to unlearn your weaponsmith specialty and lose all associated recipes?' WHERE `word_id` = 129256; -- locales_gossip_menu_option - box_text : menu_id=6089-id=1
UPDATE `trans_words` SET `content_loc5`='Do you want to pay?' WHERE `word_id` = 130014; -- locales_gossip_menu_option - box_text : menu_id=57800-id=0
UPDATE `trans_words` SET `content_loc5`='Drains' WHERE `word_id`=129532; -- locales_gossip_menu_option - option_text : menu_id=10056-id=4
UPDATE `trans_words` SET `content_loc5`='Drakkari Chieftain captured! What else can I help you?' WHERE `word_id`=129485; -- locales_gossip_menu_option - option_text : menu_id=9731-id=4
UPDATE `trans_words` SET `content_loc5`='Duke of Cynders! I hold your signet! Heed my call' WHERE `word_id`=128382; -- locales_gossip_menu_option - option_text : menu_id=6542-id=1
UPDATE `trans_words` SET `content_loc5`='Earthen Templar! I hold your signet! Heed my call!' WHERE `word_id`=128378; -- locales_gossip_menu_option - option_text : menu_id=6540-id=2
UPDATE `trans_words` SET `content_loc5`='East Zeppelin Tower' WHERE `word_id`=129483; -- locales_gossip_menu_option - option_text : menu_id=9727-id=0
UPDATE `trans_words` SET `content_loc5`='East.' WHERE `word_id`=129313; -- locales_gossip_menu_option - option_text : menu_id=7639-id=1
UPDATE `trans_words` SET `content_loc5`='Emilune, I sent Admiral Keller. Please send me To Westguard Keep!' WHERE `word_id`=129466; -- locales_gossip_menu_option - option_text : menu_id=9618-id=0
UPDATE `trans_words` SET `content_loc5`='Eventide' WHERE `word_id`=129533; -- locales_gossip_menu_option - option_text : menu_id=10056-id=9
UPDATE `trans_words` SET `content_loc5`='Exalted' WHERE `word_id`=4408; -- locales_gossip_menu_option - option_text : menu_id=7208-id=3
UPDATE `trans_words` SET `content_loc5`='Explain to me how to train with a dummy for a rapid attack.' WHERE `word_id`=129583; -- locales_gossip_menu_option - option_text : menu_id=10399-id=0
UPDATE `trans_words` SET `content_loc5`='Explain to me how to train with a dummy for the melee.' WHERE `word_id`=129581; -- locales_gossip_menu_option - option_text : menu_id=10397-id=0
UPDATE `trans_words` SET `content_loc5`='Explain to me how to train with a target for long-range combat.' WHERE `word_id`=129585; -- locales_gossip_menu_option - option_text : menu_id=10401-id=0
UPDATE `trans_words` SET `content_loc5`='Felsworn Gas Mask broken. You do not have another?' WHERE `word_id`=129059; -- locales_gossip_menu_option - option_text : menu_id=8523-id=0
UPDATE `trans_words` SET `content_loc5`='Fires Outland' WHERE `word_id`=129415; -- locales_gossip_menu_option - option_text : menu_id=9197-id=2
UPDATE `trans_words` SET `content_loc5`='Flying Machine?' WHERE `word_id`=129397; -- locales_gossip_menu_option - option_text : menu_id=9084-id=0
UPDATE `trans_words` SET `content_loc5`='Follow me, Your Highness.' WHERE `word_id`=129772; -- locales_gossip_menu_option - option_text : menu_id=11874-id=0
UPDATE `trans_words` SET `content_loc5`='General & Trade Store' WHERE `word_id`=129545; -- locales_gossip_menu_option - option_text : menu_id=10173-id=11
UPDATE `trans_words` SET `content_loc5`='Get in the Flying Machine.' WHERE `word_id`=129662; -- locales_gossip_menu_option - option_text : menu_id=11211-id=0
UPDATE `trans_words` SET `content_loc5`='Get me up into the skies, Sassy.' WHERE `word_id`=129655; -- locales_gossip_menu_option - option_text : menu_id=11146-id=0
UPDATE `trans_words` SET `content_loc5`='Give me an orange.' WHERE `word_id`=129482; -- locales_gossip_menu_option - option_text : menu_id=9724-id=2
UPDATE `trans_words` SET `content_loc5`='Go and collect samples.' WHERE `word_id`=130010; -- locales_gossip_menu_option - option_text : menu_id=50014-id=0
UPDATE `trans_words` SET `content_loc5`='Go on all of Trenton.' WHERE `word_id`=129178; -- locales_gossip_menu_option - option_text : menu_id=1142-id=0
UPDATE `trans_words` SET `content_loc5`='Go on, I\'m listening.' WHERE `word_id`=129334; -- locales_gossip_menu_option - option_text : menu_id=8009-id=0
UPDATE `trans_words` SET `content_loc5`='Gorebag showed me the empire Drakkar. I am ready to help you win it!' WHERE `word_id`=129107; -- locales_gossip_menu_option - option_text : menu_id=9731-id=1
UPDATE `trans_words` SET `content_loc5`='Great and powerful Har\'koa, please, call one of his children, so he could secretly referred me to the altar Quetz\'lun.' WHERE `word_id`=129477; -- locales_gossip_menu_option - option_text : menu_id=9687-id=0
UPDATE `trans_words` SET `content_loc5`='Greatmother, I never had the honor. Durotan died long before my time, but his heroics are known to all on my world. The orcs of Azeroth reside in a place known as Durotar, named after your son. And... (You take a moment to breathe and think through what you are about to tell the Greatmother.)' WHERE `word_id`=129032; -- locales_gossip_menu_option - option_text : menu_id=7978-id=0
UPDATE `trans_words` SET `content_loc5`='Guide me back to the Alliance landing camp.' WHERE `word_id`=5466; -- locales_gossip_menu_option - option_text : menu_id=10128-id=5
UPDATE `trans_words` SET `content_loc5`='Guide me back to the Horde landing camp.' WHERE `word_id`=5465; -- locales_gossip_menu_option - option_text : menu_id=10129-id=5
UPDATE `trans_words` SET `content_loc5`='Gymer that I need to know? I never went to the giant.' WHERE `word_id`=129497; -- locales_gossip_menu_option - option_text : menu_id=9852-id=2
UPDATE `trans_words` SET `content_loc5`='Gymer, where Algar,Navarius and Thrym?' WHERE `word_id`=129496; -- locales_gossip_menu_option - option_text : menu_id=9852-id=1
UPDATE `trans_words` SET `content_loc5`='Harry said I could use his bomber to Bael\'gun\'s. I\'m ready to go!' WHERE `word_id`=129469; -- locales_gossip_menu_option - option_text : menu_id=9621-id=0
UPDATE `trans_words` SET `content_loc5`='Have gone!' WHERE `word_id`=129374; -- locales_gossip_menu_option - option_text : menu_id=8662-id=0
UPDATE `trans_words` SET `content_loc5`='Hearthglen? But...' WHERE `word_id`=127883; -- locales_gossip_menu_option - option_text : menu_id=2904-id=0
UPDATE `trans_words` SET `content_loc5`='Hemet Nesingwary, what are you doing here, in Outland' WHERE `word_id`=129306; -- locales_gossip_menu_option - option_text : menu_id=7579-id=0
UPDATE `trans_words` SET `content_loc5`='Here\'s to you. Dread Captain! Make me a pirate of the day.' WHERE `word_id`=129471; -- locales_gossip_menu_option - option_text : menu_id=9647-id=0
UPDATE `trans_words` SET `content_loc5`='High Marshal Whirlaxis! I hold your signet! Heed my call!' WHERE `word_id`=128389; -- locales_gossip_menu_option - option_text : menu_id=6543-id=3
UPDATE `trans_words` SET `content_loc5`='Hildagard, I need a pair of goggles.' WHERE `word_id`=129353; -- locales_gossip_menu_option - option_text : menu_id=8383-id=0
UPDATE `trans_words` SET `content_loc5`='Hmm, well ... I think the safety of passengers - your main concern. Give me the accelerator.' WHERE `word_id`=129628; -- locales_gossip_menu_option - option_text : menu_id=10885-id=0
UPDATE `trans_words` SET `content_loc5`='Hoary Templar! I hold your signet! Heed my call!' WHERE `word_id`=128379; -- locales_gossip_menu_option - option_text : menu_id=6540-id=3
UPDATE `trans_words` SET `content_loc5`='Hold on friend. Tell me what happened here.' WHERE `word_id`=129519; -- locales_gossip_menu_option - option_text : menu_id=10036-id=0
UPDATE `trans_words` SET `content_loc5`='Hold out a little more, my friend. I must know what happened.' WHERE `word_id`=129520; -- locales_gossip_menu_option - option_text : menu_id=10040-id=0
UPDATE `trans_words` SET `content_loc5`='Honored' WHERE `word_id`=4406; -- locales_gossip_menu_option - option_text : menu_id=7208-id=1
UPDATE `trans_words` SET `content_loc5`='How about furbolg Winterfall?' WHERE `word_id`=129200; -- locales_gossip_menu_option - option_text : menu_id=3624-id=0
UPDATE `trans_words` SET `content_loc5`='How is the screening of ore?' WHERE `word_id`=129372; -- locales_gossip_menu_option - option_text : menu_id=8646-id=1
UPDATE `trans_words` SET `content_loc5`='How long do you work on the Cult of the Damned?' WHERE `word_id`=129427; -- locales_gossip_menu_option - option_text : menu_id=9219-id=0
UPDATE `trans_words` SET `content_loc5`='How to me to bring up my pet?' WHERE `word_id`=129216; -- locales_gossip_menu_option - option_text : menu_id=4783-id=0
UPDATE `trans_words` SET `content_loc5`='I am absolutely certain that i want to learn Gnomish engineer.' WHERE `word_id`=129275; -- locales_gossip_menu_option - option_text : menu_id=7058-id=0
UPDATE `trans_words` SET `content_loc5`='I am absolutely certain that i want to learn Goblin engineer.' WHERE `word_id`=129276; -- locales_gossip_menu_option - option_text : menu_id=7058-id=1
UPDATE `trans_words` SET `content_loc5`='I am no cultist, you monster! Come to me and face your destruction!' WHERE `word_id`=128376; -- locales_gossip_menu_option - option_text : menu_id=6540-id=0
UPDATE `trans_words` SET `content_loc5`='I am ready to meet with Anachronos, Ziradormi.' WHERE `word_id`=129927; -- locales_gossip_menu_option - option_text : menu_id=12760-id=0
UPDATE `trans_words` SET `content_loc5`='I am ready, lets get you out of here.' WHERE `word_id`=129502; -- locales_gossip_menu_option - option_text : menu_id=9859-id=0
UPDATE `trans_words` SET `content_loc5`='I can not Vaelastrasz ! Surely there must be some way to heal you!' WHERE `word_id`=128456; -- locales_gossip_menu_option - option_text : menu_id=6021-id=0
UPDATE `trans_words` SET `content_loc5`='I challenge you to a duel, spawn Scarlet!' WHERE `word_id`=129504; -- locales_gossip_menu_option - option_text : menu_id=9869-id=0
UPDATE `trans_words` SET `content_loc5`='I do not understand. What are you, Ameer?' WHERE `word_id`=129344; -- locales_gossip_menu_option - option_text : menu_id=8123-id=0
UPDATE `trans_words` SET `content_loc5`='I go with you, Drakuru.' WHERE `word_id`=129111; -- locales_gossip_menu_option - option_text : menu_id=9731-id=6
UPDATE `trans_words` SET `content_loc5`='I have a book that might interest you. Would you like to take a book?' WHERE `word_id`=129556; -- locales_gossip_menu_option - option_text : menu_id=10212-id=1
UPDATE `trans_words` SET `content_loc5`='I have bad news for you,$B$BOnu\'zun: I\'m going to put an end to your dreams!' WHERE `word_id`=269455; -- locales_gossip_menu_option - option_text : menu_id=9878-id=0
UPDATE `trans_words` SET `content_loc5`='I have heard that women vrykul not know how to fight. Try to dissuade me, if you want.' WHERE `word_id`=129505; -- locales_gossip_menu_option - option_text : menu_id=9870-id=0
UPDATE `trans_words` SET `content_loc5`='I have one more question.' WHERE `word_id`=129290; -- locales_gossip_menu_option - option_text : menu_id=7209-id=0
UPDATE `trans_words` SET `content_loc5`='I have reason to believe your involvement in the activities of cultists.' WHERE `word_id`=129426; -- locales_gossip_menu_option - option_text : menu_id=9218-id=0
UPDATE `trans_words` SET `content_loc5`='I help you?' WHERE `word_id`=129286; -- locales_gossip_menu_option - option_text : menu_id=7143-id=0
UPDATE `trans_words` SET `content_loc5`='I killed Darmuk! What are future directions?' WHERE `word_id`=129109; -- locales_gossip_menu_option - option_text : menu_id=9731-id=3
UPDATE `trans_words` SET `content_loc5`='I know this is rather silly but a young ward who is a bit shy would like your hoofprint.' WHERE `word_id`=127943; -- locales_gossip_menu_option - option_text : menu_id=5851-id=0
UPDATE `trans_words` SET `content_loc5`='I lost my ring.' WHERE `word_id`=129638; -- locales_gossip_menu_option - option_text : menu_id=10996-id=2
UPDATE `trans_words` SET `content_loc5`='I lost Spectral Essence.' WHERE `word_id`=129199; -- locales_gossip_menu_option - option_text : menu_id=3310-id=1
UPDATE `trans_words` SET `content_loc5`='I need one more Wildhammer Flare Gun, Thane.' WHERE `word_id`=129364; -- locales_gossip_menu_option - option_text : menu_id=8457-id=0
UPDATE `trans_words` SET `content_loc5`='I need to find Dajik, you have to chalk?' WHERE `word_id`=129487; -- locales_gossip_menu_option - option_text : menu_id=9741-id=1
UPDATE `trans_words` SET `content_loc5`='I need to find Goregek, you have to shackles?' WHERE `word_id`=129488; -- locales_gossip_menu_option - option_text : menu_id=9741-id=3
UPDATE `trans_words` SET `content_loc5`='I need to find Jaloot, you have his Favorite Crystal?' WHERE `word_id`=129491; -- locales_gossip_menu_option - option_text : menu_id=9742-id=3
UPDATE `trans_words` SET `content_loc5`='I need to find Lafoo, you have his Bug Bag?' WHERE `word_id`=129490; -- locales_gossip_menu_option - option_text : menu_id=9742-id=1
UPDATE `trans_words` SET `content_loc5`='I need to find Moodle, you have his Stress Ball?' WHERE `word_id`=129492; -- locales_gossip_menu_option - option_text : menu_id=9742-id=4
UPDATE `trans_words` SET `content_loc5`='I need to find Zepik, you have to Hunting Horn?' WHERE `word_id`=129489; -- locales_gossip_menu_option - option_text : menu_id=9741-id=4
UPDATE `trans_words` SET `content_loc5`='I need to fly to the Windrunner. Official Business!' WHERE `word_id`=129081; -- locales_gossip_menu_option - option_text : menu_id=8894-id=0
UPDATE `trans_words` SET `content_loc5`='I need to get on the ship.' WHERE `word_id`=129140; -- locales_gossip_menu_option - option_text : menu_id=10026-id=0
UPDATE `trans_words` SET `content_loc5`='I need to know where the princess are, Kharan!' WHERE `word_id`=128457; -- locales_gossip_menu_option - option_text : menu_id=1822-id=0
UPDATE `trans_words` SET `content_loc5`='I should return to the world of shades, Koltira. Send me back.' WHERE `word_id`=129441; -- locales_gossip_menu_option - option_text : menu_id=9456-id=0
UPDATE `trans_words` SET `content_loc5`='I took off the worg mask.' WHERE `word_id`=129392; -- locales_gossip_menu_option - option_text : menu_id=8918-id=0
UPDATE `trans_words` SET `content_loc5`='I want to ask you something else.' WHERE `word_id`=129438; -- locales_gossip_menu_option - option_text : menu_id=9307-id=0
UPDATE `trans_words` SET `content_loc5`='I want to breath underwater, Garren' WHERE `word_id`=129493; -- locales_gossip_menu_option - option_text : menu_id=9761-id=0
UPDATE `trans_words` SET `content_loc5`='I want to browse your goods' WHERE `word_id`=128444; -- locales_gossip_menu_option - option_text : menu_id=0-id=13
UPDATE `trans_words` SET `content_loc5`='I want to buy more seeds of Tarlendris.' WHERE `word_id`=129183; -- locales_gossip_menu_option - option_text : menu_id=1701-id=0
UPDATE `trans_words` SET `content_loc5`='I was just wondering what you knew about the gnolls to the south. Someone has been giving them supplies to practice necromancy.' WHERE `word_id`=129775; -- locales_gossip_menu_option - option_text : menu_id=11942-id=0
UPDATE `trans_words` SET `content_loc5`='I watched your brilliant operation, Drakuru. When start to act?' WHERE `word_id`=129110; -- locales_gossip_menu_option - option_text : menu_id=9731-id=5
UPDATE `trans_words` SET `content_loc5`='I wish to know about Dual Talent Specialization.' WHERE `word_id`=128991; -- locales_gossip_menu_option - option_text : menu_id=10027-id=2
UPDATE `trans_words` SET `content_loc5`='I wish to unlearn Dragonscale Leatherworking.' WHERE `word_id`=129193; -- locales_gossip_menu_option - option_text : menu_id=3067-id=2
UPDATE `trans_words` SET `content_loc5`='I wish to unlearn Elemental Leatherworking.' WHERE `word_id`=129196; -- locales_gossip_menu_option - option_text : menu_id=3070-id=2
UPDATE `trans_words` SET `content_loc5`='I wish to unlearn Gnomish engineer.' WHERE `word_id`=129277; -- locales_gossip_menu_option - option_text : menu_id=7058-id=2
UPDATE `trans_words` SET `content_loc5`='I wish to unlearn Goblin engineer.' WHERE `word_id`=129279; -- locales_gossip_menu_option - option_text : menu_id=7058-id=3
UPDATE `trans_words` SET `content_loc5`='I wish to unlearn my pet\'s skills.' WHERE `word_id`=127826; -- locales_gossip_menu_option - option_text : menu_id=0-id=15
UPDATE `trans_words` SET `content_loc5`='I wish to unlearn Tribal Leatherworking.' WHERE `word_id`=129198; -- locales_gossip_menu_option - option_text : menu_id=3072-id=2
UPDATE `trans_words` SET `content_loc5`='I would have want to get a new invitation to the Lunar Festival.' WHERE `word_id`=129271; -- locales_gossip_menu_option - option_text : menu_id=6918-id=0
UPDATE `trans_words` SET `content_loc5`='I would like to build a catapult.' WHERE `word_id`=129512; -- locales_gossip_menu_option - option_text : menu_id=9904-id=0
UPDATE `trans_words` SET `content_loc5`='I would like to build a demolisher.' WHERE `word_id`=129513; -- locales_gossip_menu_option - option_text : menu_id=9904-id=1
UPDATE `trans_words` SET `content_loc5`='I would like to build a siege engine.' WHERE `word_id`=129514; -- locales_gossip_menu_option - option_text : menu_id=9904-id=2
UPDATE `trans_words` SET `content_loc5`='I would like to fly back to Silvermoon City...' WHERE `word_id`=129287; -- locales_gossip_menu_option - option_text : menu_id=7147-id=0
UPDATE `trans_words` SET `content_loc5`='I would like to inform the secret code to get a pet, murloc.' WHERE `word_id`=129273; -- locales_gossip_menu_option - option_text : menu_id=7034-id=0
UPDATE `trans_words` SET `content_loc5`='I would like to take a flight to the ground, Lord Of Afrasastrasz?' WHERE `word_id`=129460; -- locales_gossip_menu_option - option_text : menu_id=9563-id=1
UPDATE `trans_words` SET `content_loc5`='I would speak against my brother joining the order, rushing a permanent breech in our relationship. He would be a danger to himself and those around him, and that is too great a risk hoping he would improve over time.' WHERE `word_id`=128210; -- locales_gossip_menu_option - option_text : menu_id=6209-id=0
UPDATE `trans_words` SET `content_loc5`='I\'d like you to make me a new Cache of Mau\'ari please' WHERE `word_id`=129191; -- locales_gossip_menu_option - option_text : menu_id=2703-id=2
UPDATE `trans_words` SET `content_loc5`='I\'m cool-stands this Blight Geists!' WHERE `word_id`=129108; -- locales_gossip_menu_option - option_text : menu_id=9731-id=2
UPDATE `trans_words` SET `content_loc5`='I\'m fine, thanks. Are you searching for me?' WHERE `word_id`=129357; -- locales_gossip_menu_option - option_text : menu_id=8436-id=0
UPDATE `trans_words` SET `content_loc5`='I\'m ready for the battle for the Echo Isles. Send me to a place of gathering!' WHERE `word_id`=129678; -- locales_gossip_menu_option - option_text : menu_id=11345-id=1
UPDATE `trans_words` SET `content_loc5`='I\'m ready to deliver the tome, Arcanist Tybalin.' WHERE `word_id`=129624; -- locales_gossip_menu_option - option_text : menu_id=10858-id=1
UPDATE `trans_words` SET `content_loc5`='I\'m ready to go to Stormwind.' WHERE `word_id`=129190; -- locales_gossip_menu_option - option_text : menu_id=2465-id=0
UPDATE `trans_words` SET `content_loc5`='I\'m ready to go to the Storm Peaks.' WHERE `word_id`=129515; -- locales_gossip_menu_option - option_text : menu_id=9917-id=1
UPDATE `trans_words` SET `content_loc5`='I\'m ready to see the fate Krolmir.' WHERE `word_id`=129510; -- locales_gossip_menu_option - option_text : menu_id=9899-id=0
UPDATE `trans_words` SET `content_loc5`='I\'m ready to take part of the ceremony, Hallegosa.' WHERE `word_id`=130011; -- locales_gossip_menu_option - option_text : menu_id=53371-id=0
UPDATE `trans_words` SET `content_loc5`='I\'m ready, Akama!' WHERE `word_id`=129382; -- locales_gossip_menu_option - option_text : menu_id=8713-id=0
UPDATE `trans_words` SET `content_loc5`='I\'m ready, Gymer. Go!' WHERE `word_id`=129498; -- locales_gossip_menu_option - option_text : menu_id=9852-id=3
UPDATE `trans_words` SET `content_loc5`='I\'ve been meaning to ask out about that monkey.' WHERE `word_id`=127949; -- locales_gossip_menu_option - option_text : menu_id=6555-id=0
UPDATE `trans_words` SET `content_loc5`='I\'ve got a staff of Archmage Vargoth lost ... I do not find anything in return?' WHERE `word_id`=129331; -- locales_gossip_menu_option - option_text : menu_id=7981-id=0
UPDATE `trans_words` SET `content_loc5`='I\'ve lost my Tabard of Blood Knight.' WHERE `word_id`=129120; -- locales_gossip_menu_option - option_text : menu_id=9832-id=1
UPDATE `trans_words` SET `content_loc5`='If you do not mind, King Jokkum, I can see what happened to Krolmir' WHERE `word_id`=129511; -- locales_gossip_menu_option - option_text : menu_id=9900-id=0
UPDATE `trans_words` SET `content_loc5`='If you want to know is male or female, look Frost Leopard by the tail.' WHERE `word_id`=129562; -- locales_gossip_menu_option - option_text : menu_id=10273-id=0
UPDATE `trans_words` SET `content_loc5`='If you want to know is male or female, look Icepaw Bear by the tail.' WHERE `word_id`=129563; -- locales_gossip_menu_option - option_text : menu_id=10274-id=0
UPDATE `trans_words` SET `content_loc5`='Important places' WHERE `word_id`=129525; -- locales_gossip_menu_option - option_text : menu_id=10043-id=11
UPDATE `trans_words` SET `content_loc5`='Impressive. When we will attack?' WHERE `word_id`=129358; -- locales_gossip_menu_option - option_text : menu_id=8438-id=0
UPDATE `trans_words` SET `content_loc5`='Initiative, please do my stuff.' WHERE `word_id`=129336; -- locales_gossip_menu_option - option_text : menu_id=8047-id=0
UPDATE `trans_words` SET `content_loc5`='Inside the rocket some substance. What is its composition?' WHERE `word_id`=129632; -- locales_gossip_menu_option - option_text : menu_id=10945-id=0
UPDATE `trans_words` SET `content_loc5`='Invasion of the Legion' WHERE `word_id`=129416; -- locales_gossip_menu_option - option_text : menu_id=9197-id=3
UPDATE `trans_words` SET `content_loc5`='Is there anything you would have of me?' WHERE `word_id`=128367; -- locales_gossip_menu_option - option_text : menu_id=50012-id=0
UPDATE `trans_words` SET `content_loc5`='Is there something I can do at the Shrine of Malorne?' WHERE `word_id`=129801; -- locales_gossip_menu_option - option_text : menu_id=12167-id=3
UPDATE `trans_words` SET `content_loc5`='It seems, I somewhere not there put the key.' WHERE `word_id`=129308; -- locales_gossip_menu_option - option_text : menu_id=7594-id=0
UPDATE `trans_words` SET `content_loc5`='It\'s... cool. How about these Flying Machine?' WHERE `word_id`=129399; -- locales_gossip_menu_option - option_text : menu_id=9085-id=0
UPDATE `trans_words` SET `content_loc5`='Journey to the fair will cost you' WHERE `word_id` = 129961; -- locales_gossip_menu_option - box_text : menu_id=12992-id=0
UPDATE `trans_words` SET `content_loc5`='Journey to the fair will cost you' WHERE `word_id`=129961; -- locales_gossip_menu_option - option_text : menu_id=12992-id=0
UPDATE `trans_words` SET `content_loc5`='Lady Jaina, this may sound like an odd request... but I have a young ward who is quite shy. You are a hero to him, and he asked me to get your autograph.' WHERE `word_id`=127878; -- locales_gossip_menu_option - option_text : menu_id=2465-id=1
UPDATE `trans_words` SET `content_loc5`='Lady Proudmoore. I am ready to go to Orgrimmar. Please open a portal.' WHERE `word_id`=129550; -- locales_gossip_menu_option - option_text : menu_id=10189-id=0
UPDATE `trans_words` SET `content_loc5`='lala' WHERE `word_id`=129425; -- locales_gossip_menu_option - option_text : menu_id=9212-id=1
UPDATE `trans_words` SET `content_loc5`='Lead us, Prince Arthas.' WHERE `word_id`=129475; -- locales_gossip_menu_option - option_text : menu_id=9681-id=0
UPDATE `trans_words` SET `content_loc5`='Learn recipe...' WHERE `word_id`=129264; -- locales_gossip_menu_option - option_text : menu_id=6443-id=0
UPDATE `trans_words` SET `content_loc5`='Let me browse your goods' WHERE `word_id`=128103; -- locales_gossip_menu_option - option_text : menu_id=3130-id=0
UPDATE `trans_words` SET `content_loc5`='Let the earth you would be down, the hero of the Alliance!' WHERE `word_id`=129521; -- locales_gossip_menu_option - option_text : menu_id=10040-id=1
UPDATE `trans_words` SET `content_loc5`='Let\'s begin, sister.' WHERE `word_id`=129503; -- locales_gossip_menu_option - option_text : menu_id=9865-id=0
UPDATE `trans_words` SET `content_loc5`='Locate pilot\'s sign' WHERE `word_id`=129407; -- locales_gossip_menu_option - option_text : menu_id=9190-id=0
UPDATE `trans_words` SET `content_loc5`='Lord Afrasastrasz sent me. He said you have a message to decode.' WHERE `word_id`=129982; -- locales_gossip_menu_option - option_text : menu_id=13160-id=1
UPDATE `trans_words` SET `content_loc5`='Lord Skwol! I hold your signet! Heed my call!' WHERE `word_id`=128390; -- locales_gossip_menu_option - option_text : menu_id=6543-id=4
UPDATE `trans_words` SET `content_loc5`='Loremaster Festival asked me to talk to you.' WHERE `word_id`=129423; -- locales_gossip_menu_option - option_text : menu_id=9203-id=0
UPDATE `trans_words` SET `content_loc5`='Mana spinning machine tool' WHERE `word_id`=129311; -- locales_gossip_menu_option - option_text : menu_id=7633-id=11
UPDATE `trans_words` SET `content_loc5`='Management Warchief Blackhand' WHERE `word_id`=129352; -- locales_gossip_menu_option - option_text : menu_id=8368-id=0
UPDATE `trans_words` SET `content_loc5`='May bee a couple copper will loosen your toungue. Now tell me, did you se who killed the Furlbrows?' WHERE `word_id`=129732; -- locales_gossip_menu_option - option_text : menu_id=11635-id=1
UPDATE `trans_words` SET `content_loc5`='May I have your report?' WHERE `word_id`=127969; -- locales_gossip_menu_option - option_text : menu_id=6690-id=0
UPDATE `trans_words` SET `content_loc5`='Merchants' WHERE `word_id`=129526; -- locales_gossip_menu_option - option_text : menu_id=10043-id=14
UPDATE `trans_words` SET `content_loc5`='Miss warm-up, sister... or you afraid to fight with someone who is not half as you?' WHERE `word_id`=129506; -- locales_gossip_menu_option - option_text : menu_id=9874-id=0
UPDATE `trans_words` SET `content_loc5`='My answer - Alexstrasza.' WHERE `word_id`=127930; -- locales_gossip_menu_option - option_text : menu_id=4763-id=3
UPDATE `trans_words` SET `content_loc5`='My answer - Malygos.' WHERE `word_id`=127929; -- locales_gossip_menu_option - option_text : menu_id=4763-id=4
UPDATE `trans_words` SET `content_loc5`='My answer - Neltharion.' WHERE `word_id`=127932; -- locales_gossip_menu_option - option_text : menu_id=4763-id=1
UPDATE `trans_words` SET `content_loc5`='My answer - Nozdormu.' WHERE `word_id`=127931; -- locales_gossip_menu_option - option_text : menu_id=4763-id=2
UPDATE `trans_words` SET `content_loc5`='My answer - Ysera.' WHERE `word_id`=127933; -- locales_gossip_menu_option - option_text : menu_id=4763-id=0
UPDATE `trans_words` SET `content_loc5`='My companions and I - to you, Lady Proudmoore.' WHERE `word_id`=129305; -- locales_gossip_menu_option - option_text : menu_id=7552-id=0
UPDATE `trans_words` SET `content_loc5`='My Lord, I must go to the upper floor of the temple.' WHERE `word_id`=129459; -- locales_gossip_menu_option - option_text : menu_id=9563-id=0
UPDATE `trans_words` SET `content_loc5`='My totemic beacon was lost - can I get another?' WHERE `word_id`=129403; -- locales_gossip_menu_option - option_text : menu_id=9157-id=0
UPDATE `trans_words` SET `content_loc5`='Ner\'zhul' WHERE `word_id`=128151; -- locales_gossip_menu_option - option_text : menu_id=4764-id=2
UPDATE `trans_words` SET `content_loc5`='No, please go ahead.' WHERE `word_id`=129603; -- locales_gossip_menu_option - option_text : menu_id=10643-id=0
UPDATE `trans_words` SET `content_loc5`='Oh, Grandma, what big eyes you have!' WHERE `word_id`=129301; -- locales_gossip_menu_option - option_text : menu_id=7442-id=0
UPDATE `trans_words` SET `content_loc5`='Oh, Grandma, what is your big production!' WHERE `word_id`=129302; -- locales_gossip_menu_option - option_text : menu_id=7443-id=0
UPDATE `trans_words` SET `content_loc5`='Oh, I assure you, it\'s not my fault ...' WHERE `word_id`=129356; -- locales_gossip_menu_option - option_text : menu_id=8435-id=0
UPDATE `trans_words` SET `content_loc5`='One of the ministers of cult came to my sword and died... Can I get another disguise? I promise, this time I\'ll be careful.' WHERE `word_id`=129454; -- locales_gossip_menu_option - option_text : menu_id=9537-id=0
UPDATE `trans_words` SET `content_loc5`='Orik, I need one more piece of Murkweed Elixir.' WHERE `word_id`=129455; -- locales_gossip_menu_option - option_text : menu_id=9542-id=0
UPDATE `trans_words` SET `content_loc5`='Papaya is now would be very handy.' WHERE `word_id`=129481; -- locales_gossip_menu_option - option_text : menu_id=9724-id=1
UPDATE `trans_words` SET `content_loc5`='Paval Reethe.' WHERE `word_id`=128449; -- locales_gossip_menu_option - option_text : menu_id=1186-id=1
UPDATE `trans_words` SET `content_loc5`='Perhaps I can be of some assistance. I will make a deal with you, Satyr. I shall recover this unforged breastplate and slay the beast. In exchange for this task, you will teach me how to create the breastplate.' WHERE `word_id`=128373; -- locales_gossip_menu_option - option_text : menu_id=50007-id=0
UPDATE `trans_words` SET `content_loc5`='Pet Store' WHERE `word_id`=129546; -- locales_gossip_menu_option - option_text : menu_id=10173-id=7
UPDATE `trans_words` SET `content_loc5`='Pet: baby gorilla' WHERE `word_id`=129412; -- locales_gossip_menu_option - option_text : menu_id=9194-id=1
UPDATE `trans_words` SET `content_loc5`='Pie, Pastry & Cake' WHERE `word_id`=129547; -- locales_gossip_menu_option - option_text : menu_id=10173-id=8
UPDATE `trans_words` SET `content_loc5`='Please send me to the Emerald Dream, to find acorns! I know about the dangers and do not fear it.' WHERE `word_id`=129558; -- locales_gossip_menu_option - option_text : menu_id=10215-id=1
UPDATE `trans_words` SET `content_loc5`='Please teach me how to become a Master of Elixirs, Lorokeem.' WHERE `word_id`=129066; -- locales_gossip_menu_option - option_text : menu_id=8540-id=0
UPDATE `trans_words` SET `content_loc5`='Please teach me how to become a Master of Potions, Lauranna.' WHERE `word_id`=129013; -- locales_gossip_menu_option - option_text : menu_id=7571-id=0
UPDATE `trans_words` SET `content_loc5`='Please teach me how to become a Master of Transmutations, Zarevhi.' WHERE `word_id`=129068; -- locales_gossip_menu_option - option_text : menu_id=8542-id=0
UPDATE `trans_words` SET `content_loc5`='Please teach me how to become a Mooncloth tailoring.' WHERE `word_id`=129060; -- locales_gossip_menu_option - option_text : menu_id=8530-id=1
UPDATE `trans_words` SET `content_loc5`='Please teach me how to become a Shadoweave tailoring.' WHERE `word_id`=129065; -- locales_gossip_menu_option - option_text : menu_id=8532-id=1
UPDATE `trans_words` SET `content_loc5`='Please teach me how to become a Spellfire tailoring.' WHERE `word_id`=129063; -- locales_gossip_menu_option - option_text : menu_id=8531-id=1
UPDATE `trans_words` SET `content_loc5`='Please tell me more about hippogryphs.' WHERE `word_id`=129174; -- locales_gossip_menu_option - option_text : menu_id=942-id=1
UPDATE `trans_words` SET `content_loc5`='Please tell me more about Maraudon' WHERE `word_id`=128442; -- locales_gossip_menu_option - option_text : menu_id=5349-id=0
UPDATE `trans_words` SET `content_loc5`='Please tell us more about the Gordunni Ogre Clan.' WHERE `word_id`=129175; -- locales_gossip_menu_option - option_text : menu_id=942-id=2
UPDATE `trans_words` SET `content_loc5`='Portals to capital cities' WHERE `word_id`=129523; -- locales_gossip_menu_option - option_text : menu_id=10043-id=5
UPDATE `trans_words` SET `content_loc5`='Prince Skaldrenox! I hold your signet! Heed my call!' WHERE `word_id`=128387; -- locales_gossip_menu_option - option_text : menu_id=6543-id=1
UPDATE `trans_words` SET `content_loc5`='Private Weeks, I need a new disguise' WHERE `word_id`=129321; -- locales_gossip_menu_option - option_text : menu_id=7771-id=0
UPDATE `trans_words` SET `content_loc5`='Purchase 5 Unstable Flask of the Beast for the cost of 50 Apexis Shards' WHERE `word_id`=129376; -- locales_gossip_menu_option - option_text : menu_id=8672-id=1
UPDATE `trans_words` SET `content_loc5`='Purchase 5 Unstable Flask of the Sorcerer for the cost of 50 Apexis Shards' WHERE `word_id`=129379; -- locales_gossip_menu_option - option_text : menu_id=8677-id=1
UPDATE `trans_words` SET `content_loc5`='Purchase a Dual Talent Specialization.' WHERE `word_id`=129155; -- locales_gossip_menu_option - option_text : menu_id=10371-id=0
UPDATE `trans_words` SET `content_loc5`='Put the barrel of termites on this box.' WHERE `word_id`=129213; -- locales_gossip_menu_option - option_text : menu_id=4362-id=0
UPDATE `trans_words` SET `content_loc5`='Ranged Weapons' WHERE `word_id`=129542; -- locales_gossip_menu_option - option_text : menu_id=10168-id=1
UPDATE `trans_words` SET `content_loc5`='Reach for the Eye of the Lich King, so that by concentrating all his will, to try to obtain the necessary information.' WHERE `word_id`=129517; -- locales_gossip_menu_option - option_text : menu_id=10005-id=0
UPDATE `trans_words` SET `content_loc5`='Read on if you dare...' WHERE `word_id`=129332; -- locales_gossip_menu_option - option_text : menu_id=7984-id=0
UPDATE `trans_words` SET `content_loc5`='Red jacket' WHERE `word_id`=129410; -- locales_gossip_menu_option - option_text : menu_id=9192-id=0
UPDATE `trans_words` SET `content_loc5`='Redeem marks the battlefield to honor.' WHERE `word_id`=129267; -- locales_gossip_menu_option - option_text : menu_id=6597-id=0
UPDATE `trans_words` SET `content_loc5`='Remove the shackles from Flamebringer and subordinate it to themselves' WHERE `word_id`=129451; -- locales_gossip_menu_option - option_text : menu_id=9512-id=0
UPDATE `trans_words` SET `content_loc5`='Restore points' WHERE `word_id`=129422; -- locales_gossip_menu_option - option_text : menu_id=9197-id=10
UPDATE `trans_words` SET `content_loc5`='Revered' WHERE `word_id`=4407; -- locales_gossip_menu_option - option_text : menu_id=7208-id=2
UPDATE `trans_words` SET `content_loc5`='Rhunok, I need to fill your power drink.' WHERE `word_id`=129479; -- locales_gossip_menu_option - option_text : menu_id=9715-id=0
UPDATE `trans_words` SET `content_loc5`='Sassy, I\'am ready, Let\'s go.' WHERE `word_id`=129901; -- locales_gossip_menu_option - option_text : menu_id=12493-id=0
UPDATE `trans_words` SET `content_loc5`='Scout Neftis, I need a new disguise' WHERE `word_id`=129026; -- locales_gossip_menu_option - option_text : menu_id=7772-id=0
UPDATE `trans_words` SET `content_loc5`='Scyers Bank' WHERE `word_id`=129349; -- locales_gossip_menu_option - option_text : menu_id=8315-id=1
UPDATE `trans_words` SET `content_loc5`='Scyers Gem Merchant' WHERE `word_id`=129368; -- locales_gossip_menu_option - option_text : menu_id=8548-id=1
UPDATE `trans_words` SET `content_loc5`='Scyers Inn' WHERE `word_id`=129350; -- locales_gossip_menu_option - option_text : menu_id=8317-id=1
UPDATE `trans_words` SET `content_loc5`='Scyers Stable' WHERE `word_id`=129351; -- locales_gossip_menu_option - option_text : menu_id=8321-id=1
UPDATE `trans_words` SET `content_loc5`='Sen\'jin Champion\'s Pennant' WHERE `word_id`=129572; -- locales_gossip_menu_option - option_text : menu_id=10358-id=4
UPDATE `trans_words` SET `content_loc5`='Send me back to Jagged Ridge.' WHERE `word_id`=129360; -- locales_gossip_menu_option - option_text : menu_id=8455-id=0
UPDATE `trans_words` SET `content_loc5`='Send me back to Ruuan.' WHERE `word_id`=129362; -- locales_gossip_menu_option - option_text : menu_id=8455-id=3
UPDATE `trans_words` SET `content_loc5`='Send me to Shatter Point.' WHERE `word_id`=128671; -- locales_gossip_menu_option - option_text : menu_id=8100-id=0
UPDATE `trans_words` SET `content_loc5`='Sergeant, give me a spyglass.' WHERE `word_id`=129388; -- locales_gossip_menu_option - option_text : menu_id=8886-id=0
UPDATE `trans_words` SET `content_loc5`='Show dragon.' WHERE `word_id`=130006; -- locales_gossip_menu_option - option_text : menu_id=13390-id=0
UPDATE `trans_words` SET `content_loc5`='Show me again, Matthias.' WHERE `word_id`=129560; -- locales_gossip_menu_option - option_text : menu_id=10226-id=0
UPDATE `trans_words` SET `content_loc5`='Show me my bank' WHERE `word_id`=129169; -- locales_gossip_menu_option - option_text : menu_id=0-id=7
UPDATE `trans_words` SET `content_loc5`='Show me the Seer!' WHERE `word_id`=129324; -- locales_gossip_menu_option - option_text : menu_id=7859-id=0
UPDATE `trans_words` SET `content_loc5`='Show me what I have access to, Lothos.' WHERE `word_id`=129215; -- locales_gossip_menu_option - option_text : menu_id=4781-id=0
UPDATE `trans_words` SET `content_loc5`='Silver Enclave' WHERE `word_id`=129528; -- locales_gossip_menu_option - option_text : menu_id=10056-id=0
UPDATE `trans_words` SET `content_loc5`='Small mounts' WHERE `word_id`=129618; -- locales_gossip_menu_option - option_text : menu_id=10810-id=0
UPDATE `trans_words` SET `content_loc5`='Sorry!' WHERE `word_id`=129687; -- locales_gossip_menu_option - option_text : menu_id=11388-id=1
UPDATE `trans_words` SET `content_loc5`='Sorry, Tinky, but I can not afford to be distracted by you, yet do here what should be done' WHERE `word_id`=129507; -- locales_gossip_menu_option - option_text : menu_id=9875-id=0
UPDATE `trans_words` SET `content_loc5`='Speaking of action... I was ordered to take an attack from the air.' WHERE `word_id`=129396; -- locales_gossip_menu_option - option_text : menu_id=9062-id=1
UPDATE `trans_words` SET `content_loc5`='Specialist, yes? And in what field?' WHERE `word_id`=129307; -- locales_gossip_menu_option - option_text : menu_id=7590-id=2
UPDATE `trans_words` SET `content_loc5`='Spiritcaller, I need more spirit calling totems.' WHERE `word_id`=129058; -- locales_gossip_menu_option - option_text : menu_id=8513-id=0
UPDATE `trans_words` SET `content_loc5`='Sprinkle with Metzen ashes of hooves of reindeer.' WHERE `word_id`=129269; -- locales_gossip_menu_option - option_text : menu_id=6763-id=0
UPDATE `trans_words` SET `content_loc5`='Start the battle.' WHERE `word_id`=129619; -- locales_gossip_menu_option - option_text : menu_id=10847-id=0
UPDATE `trans_words` SET `content_loc5`='Stefan told me that you can demonstrate the purpose of this subject.' WHERE `word_id`=129478; -- locales_gossip_menu_option - option_text : menu_id=9714-id=1
UPDATE `trans_words` SET `content_loc5`='Take Blood Knight Insignia' WHERE `word_id`=129002; -- locales_gossip_menu_option - option_text : menu_id=7486-id=0
UPDATE `trans_words` SET `content_loc5`='Take clothes' WHERE `word_id`=129402; -- locales_gossip_menu_option - option_text : menu_id=9155-id=0
UPDATE `trans_words` SET `content_loc5`='Take me to the Caverns of Time' WHERE `word_id`=129424; -- locales_gossip_menu_option - option_text : menu_id=9205-id=0
UPDATE `trans_words` SET `content_loc5`='Talespinner Festival asked me to talk to you.' WHERE `word_id`=129428; -- locales_gossip_menu_option - option_text : menu_id=9278-id=0
UPDATE `trans_words` SET `content_loc5`='Teleport me to the Guardian\'s Library' WHERE `word_id`=127704; -- locales_gossip_menu_option - option_text : menu_id=7139-id=3
UPDATE `trans_words` SET `content_loc5`='Teleport me to the Molten Core, Lothos.' WHERE `word_id`=128554; -- locales_gossip_menu_option - option_text : menu_id=5750-id=0
UPDATE `trans_words` SET `content_loc5`='Tell me about the admission of "Beat the shield".' WHERE `word_id`=129586; -- locales_gossip_menu_option - option_text : menu_id=10402-id=1
UPDATE `trans_words` SET `content_loc5`='Tell me about the admission of "Surge".' WHERE `word_id`=129584; -- locales_gossip_menu_option - option_text : menu_id=10400-id=1
UPDATE `trans_words` SET `content_loc5`='Tell me about the nearest ruins.' WHERE `word_id`=129602; -- locales_gossip_menu_option - option_text : menu_id=10641-id=0
UPDATE `trans_words` SET `content_loc5`='Tell me about the protection and reception "Attack".' WHERE `word_id`=129582; -- locales_gossip_menu_option - option_text : menu_id=10398-id=1
UPDATE `trans_words` SET `content_loc5`='Tell me about the reduction.' WHERE `word_id`=128448; -- locales_gossip_menu_option - option_text : menu_id=1141-id=0
UPDATE `trans_words` SET `content_loc5`='Tell me about your home.' WHERE `word_id`=129295; -- locales_gossip_menu_option - option_text : menu_id=7352-id=2
UPDATE `trans_words` SET `content_loc5`='Tell me more about our mission here, Nazgrel.' WHERE `word_id`=129340; -- locales_gossip_menu_option - option_text : menu_id=8085-id=0
UPDATE `trans_words` SET `content_loc5`='Tell me more about Remulos and Zaetar.' WHERE `word_id`=128478; -- locales_gossip_menu_option - option_text : menu_id=5346-id=0
UPDATE `trans_words` SET `content_loc5`='Tell me of youself, Xarantaur. Why are you called the Witness?' WHERE `word_id`=129143; -- locales_gossip_menu_option - option_text : menu_id=10178-id=0
UPDATE `trans_words` SET `content_loc5`='Ten thousand?! This is a robbery! Just try to go to sleep tonight - I\'ll slaughter you while you dream!' WHERE `word_id`=130015; -- locales_gossip_menu_option - option_text : menu_id=57800-id=1
UPDATE `trans_words` SET `content_loc5`='Thank you for telling me your story.' WHERE `word_id`=129406; -- locales_gossip_menu_option - option_text : menu_id=9182-id=0
UPDATE `trans_words` SET `content_loc5`='Thank you! I will be sure to notify you if I find anything else.' WHERE `word_id`=129146; -- locales_gossip_menu_option - option_text : menu_id=10213-id=0
UPDATE `trans_words` SET `content_loc5`='Thank you! I\'ll try.' WHERE `word_id`=129400; -- locales_gossip_menu_option - option_text : menu_id=9085-id=1
UPDATE `trans_words` SET `content_loc5`='Tharnariun, the trap is lost. Do you have another?' WHERE `word_id`=128455; -- locales_gossip_menu_option - option_text : menu_id=10482-id=0
UPDATE `trans_words` SET `content_loc5`='The commander Infernal Shout, affairs of Nordskola demand your attention. We will cope with the King-lichom and its servants without your help.' WHERE `word_id`=129660; -- locales_gossip_menu_option - option_text : menu_id=11206-id=0
UPDATE `trans_words` SET `content_loc5`='The Darkmoon Faire has arrived, you say? And where is she now?' WHERE `word_id`=127946; -- locales_gossip_menu_option - option_text : menu_id=6213-id=0
UPDATE `trans_words` SET `content_loc5`='The day of the judgement has come, fiend! I challenge you to battle!' WHERE `word_id`=128386; -- locales_gossip_menu_option - option_text : menu_id=6543-id=0
UPDATE `trans_words` SET `content_loc5`='The Duke of Fathoms! I hold your signet! Heed my call!' WHERE `word_id`=128385; -- locales_gossip_menu_option - option_text : menu_id=6542-id=4
UPDATE `trans_words` SET `content_loc5`='The Duke of Shards! I hold your signet! Heed my call!' WHERE `word_id`=128383; -- locales_gossip_menu_option - option_text : menu_id=6542-id=2
UPDATE `trans_words` SET `content_loc5`='The Duke of Zephyrs! I hold your signet! Heed my call!' WHERE `word_id`=128384; -- locales_gossip_menu_option - option_text : menu_id=6542-id=3
UPDATE `trans_words` SET `content_loc5`='The word is given. The King-lich will accept death from our hands!' WHERE `word_id`=129661; -- locales_gossip_menu_option - option_text : menu_id=11207-id=0
UPDATE `trans_words` SET `content_loc5`='They were able to survive?' WHERE `word_id`=129605; -- locales_gossip_menu_option - option_text : menu_id=10645-id=0
UPDATE `trans_words` SET `content_loc5`='This Dimensional Imploder sounds dangerous! How can I make one?' WHERE `word_id`=128186; -- locales_gossip_menu_option - option_text : menu_id=6092-id=0
UPDATE `trans_words` SET `content_loc5`='This does not happen again.' WHERE `word_id`=129639; -- locales_gossip_menu_option - option_text : menu_id=10998-id=0
UPDATE `trans_words` SET `content_loc5`='This is your Rocket label Snivel.' WHERE `word_id`=129629; -- locales_gossip_menu_option - option_text : menu_id=10929-id=0
UPDATE `trans_words` SET `content_loc5`='To shake given a hand Drakuru.' WHERE `word_id`=129465; -- locales_gossip_menu_option - option_text : menu_id=9615-id=1
UPDATE `trans_words` SET `content_loc5`='Toy Store' WHERE `word_id`=129548; -- locales_gossip_menu_option - option_text : menu_id=10173-id=10
UPDATE `trans_words` SET `content_loc5`='Transcript the Tablet' WHERE `word_id`=128093; -- locales_gossip_menu_option - option_text : menu_id=2187-id=0
UPDATE `trans_words` SET `content_loc5`='Undercity Champion\'s Pennant' WHERE `word_id`=129575; -- locales_gossip_menu_option - option_text : menu_id=10358-id=7
UPDATE `trans_words` SET `content_loc5`='Use engineering to access hidden shematics!' WHERE `word_id`=128982; -- locales_gossip_menu_option - option_text : menu_id=1050-id=1
UPDATE `trans_words` SET `content_loc5`='Vaelastrasz , no!' WHERE `word_id`=128475; -- locales_gossip_menu_option - option_text : menu_id=6101-id=0
UPDATE `trans_words` SET `content_loc5`='Vanira told me to ask you for the time the bat' WHERE `word_id`=129677; -- locales_gossip_menu_option - option_text : menu_id=11345-id=0
UPDATE `trans_words` SET `content_loc5`='Violet Citadel' WHERE `word_id`=129531; -- locales_gossip_menu_option - option_text : menu_id=10056-id=3
UPDATE `trans_words` SET `content_loc5`='War of the 17249ourge' WHERE `word_id`=129421; -- locales_gossip_menu_option - option_text : menu_id=9197-id=9
UPDATE `trans_words` SET `content_loc5`='Watcher Analisis: Freya' WHERE `word_id`=129576; -- locales_gossip_menu_option - option_text : menu_id=10368-id=2
UPDATE `trans_words` SET `content_loc5`='Watcher Analisis: Hodir' WHERE `word_id`=129577; -- locales_gossip_menu_option - option_text : menu_id=10368-id=3
UPDATE `trans_words` SET `content_loc5`='Watcher Analisis: Mimiron' WHERE `word_id`=129579; -- locales_gossip_menu_option - option_text : menu_id=10368-id=5
UPDATE `trans_words` SET `content_loc5`='Watcher Analisis: Thorim' WHERE `word_id`=129578; -- locales_gossip_menu_option - option_text : menu_id=10368-id=4
UPDATE `trans_words` SET `content_loc5`='Watcher Leesa\'oh, why are you here?' WHERE `word_id`=129304; -- locales_gossip_menu_option - option_text : menu_id=7495-id=0
UPDATE `trans_words` SET `content_loc5`='Wayfarer\'s Rest tavern' WHERE `word_id`=129322; -- locales_gossip_menu_option - option_text : menu_id=7845-id=1
UPDATE `trans_words` SET `content_loc5`='We are ready to meet face to face Illidan.' WHERE `word_id`=129371; -- locales_gossip_menu_option - option_text : menu_id=8638-id=0
UPDATE `trans_words` SET `content_loc5`='We do only what is best for Lordaeron, Your Highness.' WHERE `word_id`=129474; -- locales_gossip_menu_option - option_text : menu_id=9680-id=0
UPDATE `trans_words` SET `content_loc5`='Well' WHERE `word_id`=129527; -- locales_gossip_menu_option - option_text : menu_id=10055-id=2
UPDATE `trans_words` SET `content_loc5`='Well, then I\'ll try.' WHERE `word_id`=129299; -- locales_gossip_menu_option - option_text : menu_id=7422-id=0
UPDATE `trans_words` SET `content_loc5`='West' WHERE `word_id`=129312; -- locales_gossip_menu_option - option_text : menu_id=7639-id=0
UPDATE `trans_words` SET `content_loc5`='West Zeppelin Tower' WHERE `word_id`=129484; -- locales_gossip_menu_option - option_text : menu_id=9727-id=1
UPDATE `trans_words` SET `content_loc5`='What can you tell to me about a bear Ursangous\'s?' WHERE `word_id`=128447; -- locales_gossip_menu_option - option_text : menu_id=4346-id=1
UPDATE `trans_words` SET `content_loc5`='What can you tell to me about a hippogryph Sharptalon\'s?' WHERE `word_id`=128445; -- locales_gossip_menu_option - option_text : menu_id=4346-id=3
UPDATE `trans_words` SET `content_loc5`='What can you tell to me about a nightsaber Shadumbra\'s?' WHERE `word_id`=128446; -- locales_gossip_menu_option - option_text : menu_id=4346-id=2
UPDATE `trans_words` SET `content_loc5`='What do you know about the destruction of the magic gates at the Sunwell Plateau?' WHERE `word_id`=129395; -- locales_gossip_menu_option - option_text : menu_id=9046-id=0
UPDATE `trans_words` SET `content_loc5`='What do you know about the tavern "The last camp"' WHERE `word_id`=129217; -- locales_gossip_menu_option - option_text : menu_id=4944-id=0
UPDATE `trans_words` SET `content_loc5`='What do you think, where they hold in custody Chancellor Amye?' WHERE `word_id`=129448; -- locales_gossip_menu_option - option_text : menu_id=9509-id=1
UPDATE `trans_words` SET `content_loc5`='What happened to mages?' WHERE `word_id`=129604; -- locales_gossip_menu_option - option_text : menu_id=10644-id=0
UPDATE `trans_words` SET `content_loc5`='What if I don\'t like drinking... Is there another way I can help out?' WHERE `word_id`=128309; -- locales_gossip_menu_option - option_text : menu_id=9006-id=0
UPDATE `trans_words` SET `content_loc5`='What is the current state of the gates of the Sunwell?' WHERE `word_id`=129430; -- locales_gossip_menu_option - option_text : menu_id=9286-id=0
UPDATE `trans_words` SET `content_loc5`='What our successes in neutralization of cauldrons?' WHERE `word_id`=128463; -- locales_gossip_menu_option - option_text : menu_id=3183-id=0
UPDATE `trans_words` SET `content_loc5`='What\'s unusual about me you can suggest?' WHERE `word_id`=129298; -- locales_gossip_menu_option - option_text : menu_id=10330-id=3
UPDATE `trans_words` SET `content_loc5`='Where can I find the center of the elements?' WHERE `word_id`=129280; -- locales_gossip_menu_option - option_text : menu_id=7096-id=2
UPDATE `trans_words` SET `content_loc5`='Where have you sent them?' WHERE `word_id`=129633; -- locales_gossip_menu_option - option_text : menu_id=10946-id=0
UPDATE `trans_words` SET `content_loc5`='Where is contained Senior Scrivener Barriga?' WHERE `word_id`=129449; -- locales_gossip_menu_option - option_text : menu_id=9509-id=2
UPDATE `trans_words` SET `content_loc5`='Where is Elder Ezra Wheathoof?' WHERE `word_id`=128403; -- locales_gossip_menu_option - option_text : menu_id=6814-id=3
UPDATE `trans_words` SET `content_loc5`='Where would you like to fly to?.' WHERE `word_id`=129456; -- locales_gossip_menu_option - option_text : menu_id=9546-id=0
UPDATE `trans_words` SET `content_loc5`='Who is the king of ravens Aykiss?' WHERE `word_id`=129325; -- locales_gossip_menu_option - option_text : menu_id=7866-id=1
UPDATE `trans_words` SET `content_loc5`='Who is this Terokk, whom you now and then mention it?' WHERE `word_id`=129326; -- locales_gossip_menu_option - option_text : menu_id=7866-id=3
UPDATE `trans_words` SET `content_loc5`='Why are you all repair?' WHERE `word_id`=129318; -- locales_gossip_menu_option - option_text : menu_id=7757-id=0
UPDATE `trans_words` SET `content_loc5`='Why, Grandma, you have such big ears?' WHERE `word_id`=129300; -- locales_gossip_menu_option - option_text : menu_id=7441-id=0
UPDATE `trans_words` SET `content_loc5`='Wind Master' WHERE `word_id`=129310; -- locales_gossip_menu_option - option_text : menu_id=7633-id=2
UPDATE `trans_words` SET `content_loc5`='Would you renew my Silver Covenant disguise?' WHERE `word_id`=129623; -- locales_gossip_menu_option - option_text : menu_id=10857-id=2
UPDATE `trans_words` SET `content_loc5`='Yes elder. Tell me more of the book.' WHERE `word_id`=128719; -- locales_gossip_menu_option - option_text : menu_id=8617-id=0
UPDATE `trans_words` SET `content_loc5`='Yes, in Augustus. I would like to do business.' WHERE `word_id`=129212; -- locales_gossip_menu_option - option_text : menu_id=4085-id=0
UPDATE `trans_words` SET `content_loc5`='Yes... yes, it\'s me.' WHERE `word_id`=128718; -- locales_gossip_menu_option - option_text : menu_id=8616-id=0
UPDATE `trans_words` SET `content_loc5`='You can read the spell that will allow me to breathe underwater?' WHERE `word_id`=129348; -- locales_gossip_menu_option - option_text : menu_id=8298-id=0
UPDATE `trans_words` SET `content_loc5`='You don\'t have excess bunches of bananas?' WHERE `word_id`=129480; -- locales_gossip_menu_option - option_text : menu_id=9724-id=0
UPDATE `trans_words` SET `content_loc5`='You gave the crew disguises?' WHERE `word_id`=128740; -- locales_gossip_menu_option - option_text : menu_id=8775-id=0
UPDATE `trans_words` SET `content_loc5`='You may choose to care for an Oracle orphan or a frenzyheart orphan. But you will not be able help both.' WHERE `word_id` = 129591; -- locales_gossip_menu_option - box_text : menu_id=10502-id=0
UPDATE `trans_words` SET `content_loc5`='Your name is uttered in my presence only in whispers, $N. Who are you?' WHERE `word_id`=129309; -- locales_gossip_menu_option - option_text : menu_id=7596-id=0
UPDATE `trans_words` SET `content_loc5`='Zorus, I need a pair of goggles.' WHERE `word_id`=129355; -- locales_gossip_menu_option - option_text : menu_id=8392-id=0

SET NAMES 'latin1';
