-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `locales_achievement_reward` SET `subject_loc1`='전투모병관' WHERE `entry`=230;
UPDATE `locales_achievement_reward` SET `subject_loc1`='얼라이언스를 위하여!' WHERE `entry`=614;
UPDATE `locales_achievement_reward` SET `subject_loc1`='호드를 위하여!' WHERE `entry`=619;
UPDATE `locales_achievement_reward` SET `subject_loc1`='제독님, 안녕?' WHERE `entry`=871;
UPDATE `locales_achievement_reward` SET `subject_loc1`='외교관' WHERE `entry`=942;
UPDATE `locales_achievement_reward` SET `subject_loc1`='외교관' WHERE `entry`=943;
UPDATE `locales_achievement_reward` SET `subject_loc1`='전투모병관' WHERE `entry`=1175;

SET NAMES 'latin1';
