-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `script_texts` SET `content_loc10`='Ai! Tá bom, eu voltarei ao trabalho, $N!' WHERE `entry`=-1000600;
UPDATE `script_texts` SET `content_loc10`='Tô com sono... Tô com tanto sono...' WHERE `entry`=-1000601;

SET NAMES 'latin1';
