-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `mangos_string` SET `content_loc10`='Olá! Pront$go:a; para o treinamento?' WHERE `entry`=51;
UPDATE `mangos_string` SET `content_loc10`='Mestre da Guild' WHERE `entry`=811;
UPDATE `mangos_string` SET `content_loc10`='Oficial' WHERE `entry`=812;
UPDATE `mangos_string` SET `content_loc10`='Veterano' WHERE `entry`=813;
UPDATE `mangos_string` SET `content_loc10`='Membro' WHERE `entry`=814;
UPDATE `mangos_string` SET `content_loc10`='Iniciado' WHERE `entry`=815;

SET NAMES 'latin1';
