-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `locales_gossip_menu_option` SET `option_text_loc10`='Mestre da Guild' WHERE `menu_id`=435 AND `id`=6;
UPDATE `locales_gossip_menu_option` SET `option_text_loc10`='Mestre da Guild' WHERE `menu_id`=2121 AND `id`=4;
UPDATE `locales_gossip_menu_option` SET `option_text_loc10`='Mestre da Guild' WHERE `menu_id`=2352 AND `id`=3;
UPDATE `locales_gossip_menu_option` SET `option_text_loc10`='Mestre da Guild' WHERE `menu_id`=3506 AND `id`=2;
UPDATE `locales_gossip_menu_option` SET `option_text_loc10`='Mestre da Guild' WHERE `menu_id`=3533 AND `id`=2;
UPDATE `locales_gossip_menu_option` SET `option_text_loc10`='Mestre da Guild' WHERE `menu_id`=10265 AND `id`=3;

SET NAMES 'latin1';
