-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `locales_creature` SET `subname_loc10`='Mestre da Guild' WHERE `entry`=3370;
UPDATE `locales_creature` SET `subname_loc10`='Mestre da Guild' WHERE `entry`=4161;
UPDATE `locales_creature` SET `subname_loc10`='Mestre da Guild' WHERE `entry`=4613;
UPDATE `locales_creature` SET `subname_loc10`='Mestre da Guild' WHERE `entry`=4974;
UPDATE `locales_creature` SET `subname_loc10`='Mestre da Guild' WHERE `entry`=5054;
UPDATE `locales_creature` SET `subname_loc10`='Mestre da Guild' WHERE `entry`=5130;
UPDATE `locales_creature` SET `subname_loc10`='Mestre da Guild' WHERE `entry`=16568;
UPDATE `locales_creature` SET `subname_loc10`='Mestre da Guild' WHERE `entry`=16734;
UPDATE `locales_creature` SET `subname_loc10`='Mestre da Guild' WHERE `entry`=28774;
UPDATE `locales_creature` SET `subname_loc10`='Mestre da Guild' WHERE `entry`=52277;

SET NAMES 'latin1';
