-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc6`='AAA Cannon' WHERE `word_id` = 127649; -- locales_points_of_interest - icon_name : entry=464
UPDATE `trans_words` SET `content_loc6`='AAA Fortune Teller' WHERE `word_id` = 127653; -- locales_points_of_interest - icon_name : entry=468
UPDATE `trans_words` SET `content_loc6`='AAA Ring Toss' WHERE `word_id` = 127651; -- locales_points_of_interest - icon_name : entry=466
UPDATE `trans_words` SET `content_loc6`='AAA Shooting Gallery' WHERE `word_id` = 127652; -- locales_points_of_interest - icon_name : entry=467
UPDATE `trans_words` SET `content_loc6`='AAA Tonk Arena' WHERE `word_id` = 127648; -- locales_points_of_interest - icon_name : entry=463
UPDATE `trans_words` SET `content_loc6`='AAA Whack-a-Gnoll' WHERE `word_id` = 127650; -- locales_points_of_interest - icon_name : entry=465
UPDATE `trans_words` SET `content_loc6`='Aldor Gem Vendor' WHERE `word_id` = 127324; -- locales_points_of_interest - icon_name : entry=259
UPDATE `trans_words` SET `content_loc6`='Ammen Ford, Fisherwoman' WHERE `word_id` = 127295; -- locales_points_of_interest - icon_name : entry=232
UPDATE `trans_words` SET `content_loc6`='Ammen Vale: Fisherman' WHERE `word_id` = 127457; -- locales_points_of_interest - icon_name : entry=1352
UPDATE `trans_words` SET `content_loc6`='Arena Battlemaster Exodar' WHERE `word_id` = 127376; -- locales_points_of_interest - icon_name : entry=264
UPDATE `trans_words` SET `content_loc6`='Azure Watch, Alchemist' WHERE `word_id` = 127290; -- locales_points_of_interest - icon_name : entry=227
UPDATE `trans_words` SET `content_loc6`='Azure Watch, Engineering Trainer' WHERE `word_id` = 127293; -- locales_points_of_interest - icon_name : entry=230
UPDATE `trans_words` SET `content_loc6`='Azure Watch, First Aid Trainer' WHERE `word_id` = 127294; -- locales_points_of_interest - icon_name : entry=231
UPDATE `trans_words` SET `content_loc6`='Azure Watch, Herbalist' WHERE `word_id` = 127296; -- locales_points_of_interest - icon_name : entry=233
UPDATE `trans_words` SET `content_loc6`='Azure Watch, Hunter Trainer' WHERE `word_id` = 127284; -- locales_points_of_interest - icon_name : entry=221
UPDATE `trans_words` SET `content_loc6`='Azure Watch, Innkeeper' WHERE `word_id` = 127282; -- locales_points_of_interest - icon_name : entry=219
UPDATE `trans_words` SET `content_loc6`='Azure Watch, Mage Trainer' WHERE `word_id` = 127285; -- locales_points_of_interest - icon_name : entry=222
UPDATE `trans_words` SET `content_loc6`='Azure Watch, Mining Trainer' WHERE `word_id` = 127298; -- locales_points_of_interest - icon_name : entry=235
UPDATE `trans_words` SET `content_loc6`='Azure Watch, Paladin Trainer' WHERE `word_id` = 127286; -- locales_points_of_interest - icon_name : entry=223
UPDATE `trans_words` SET `content_loc6`='Azure Watch, Priest Trainer' WHERE `word_id` = 127287; -- locales_points_of_interest - icon_name : entry=224
UPDATE `trans_words` SET `content_loc6`='Azure Watch, Shaman Trainer' WHERE `word_id` = 127288; -- locales_points_of_interest - icon_name : entry=225
UPDATE `trans_words` SET `content_loc6`='Azure Watch, Stable Master' WHERE `word_id` = 127283; -- locales_points_of_interest - icon_name : entry=220
UPDATE `trans_words` SET `content_loc6`='Azure Watch, Warrior Trainer' WHERE `word_id` = 127289; -- locales_points_of_interest - icon_name : entry=226
UPDATE `trans_words` SET `content_loc6`='Azure Watch: Alchemy Trainer' WHERE `word_id` = 127453; -- locales_points_of_interest - icon_name : entry=1345
UPDATE `trans_words` SET `content_loc6`='Azure Watch: First Aid Trainer' WHERE `word_id` = 127456; -- locales_points_of_interest - icon_name : entry=1351
UPDATE `trans_words` SET `content_loc6`='Azure Watch: Herbalism' WHERE `word_id` = 127458; -- locales_points_of_interest - icon_name : entry=1353
UPDATE `trans_words` SET `content_loc6`='Azure Watch: Hunter Trainer' WHERE `word_id` = 127447; -- locales_points_of_interest - icon_name : entry=1338
UPDATE `trans_words` SET `content_loc6`='Azure Watch: Innkeeper' WHERE `word_id` = 127445; -- locales_points_of_interest - icon_name : entry=1335
UPDATE `trans_words` SET `content_loc6`='Azure Watch: Mage Trainer' WHERE `word_id` = 127448; -- locales_points_of_interest - icon_name : entry=1340
UPDATE `trans_words` SET `content_loc6`='Azure Watch: Mining Trainer' WHERE `word_id` = 127461; -- locales_points_of_interest - icon_name : entry=1357
UPDATE `trans_words` SET `content_loc6`='Azure Watch: Paladin Trainer' WHERE `word_id` = 127449; -- locales_points_of_interest - icon_name : entry=1341
UPDATE `trans_words` SET `content_loc6`='Azure Watch: Priest Trainer' WHERE `word_id` = 127450; -- locales_points_of_interest - icon_name : entry=1342
UPDATE `trans_words` SET `content_loc6`='Azure Watch: Shaman Trainer' WHERE `word_id` = 127451; -- locales_points_of_interest - icon_name : entry=1343
UPDATE `trans_words` SET `content_loc6`='Azure Watch: Stable Master' WHERE `word_id` = 127446; -- locales_points_of_interest - icon_name : entry=1337
UPDATE `trans_words` SET `content_loc6`='Azure Watch: Warrior Trainer' WHERE `word_id` = 127452; -- locales_points_of_interest - icon_name : entry=1344
UPDATE `trans_words` SET `content_loc6`='Battlemasters Darnassus' WHERE `word_id` = 127193; -- locales_points_of_interest - icon_name : entry=1132
UPDATE `trans_words` SET `content_loc6`='Battlemasters Ironforge' WHERE `word_id` = 127183; -- locales_points_of_interest - icon_name : entry=1076
UPDATE `trans_words` SET `content_loc6`='Battlemasters Orgrimmar' WHERE `word_id` = 127212; -- locales_points_of_interest - icon_name : entry=1202
UPDATE `trans_words` SET `content_loc6`='Battlemasters Stormwind' WHERE `word_id` = 127172; -- locales_points_of_interest - icon_name : entry=1034
UPDATE `trans_words` SET `content_loc6`='Battlemasters Thunder Bluff' WHERE `word_id` = 127240; -- locales_points_of_interest - icon_name : entry=1311
UPDATE `trans_words` SET `content_loc6`='Battlemasters Undercity' WHERE `word_id` = 127234; -- locales_points_of_interest - icon_name : entry=1241
UPDATE `trans_words` SET `content_loc6`='Bixi and Buliwyf' WHERE `word_id` = 127182; -- locales_points_of_interest - icon_name : entry=1072
UPDATE `trans_words` SET `content_loc6`='Bloodhoof Village Inn' WHERE `word_id` = 127245; -- locales_points_of_interest - icon_name : entry=1286
UPDATE `trans_words` SET `content_loc6`='Brew of the Month Club, Ironforge' WHERE `word_id` = 127631; -- locales_points_of_interest - icon_name : entry=1718
UPDATE `trans_words` SET `content_loc6`='Brew of the Month Club, Orgrimmar' WHERE `word_id` = 127628; -- locales_points_of_interest - icon_name : entry=1715
UPDATE `trans_words` SET `content_loc6`='Brewfest Ram Racing' WHERE `word_id` = 127630; -- locales_points_of_interest - icon_name : entry=1717
UPDATE `trans_words` SET `content_loc6`='Brewfest Souvenirs' WHERE `word_id` = 127629; -- locales_points_of_interest - icon_name : entry=1716
UPDATE `trans_words` SET `content_loc6`='Dalaran Alchemy Trainer' WHERE `word_id` = 127405; -- locales_points_of_interest - icon_name : entry=151
UPDATE `trans_words` SET `content_loc6`='Dalaran Alliance Inn' WHERE `word_id` = 127391; -- locales_points_of_interest - icon_name : entry=137
UPDATE `trans_words` SET `content_loc6`='Dalaran Antonidas Memorial' WHERE `word_id` = 127398; -- locales_points_of_interest - icon_name : entry=144
UPDATE `trans_words` SET `content_loc6`='Dalaran Archaeology Trainer' WHERE `word_id` = 127642; -- locales_points_of_interest - icon_name : entry=454
UPDATE `trans_words` SET `content_loc6`='Dalaran Barber' WHERE `word_id` = 127388; -- locales_points_of_interest - icon_name : entry=133
UPDATE `trans_words` SET `content_loc6`='Dalaran Blacksmithing Trainer' WHERE `word_id` = 127406; -- locales_points_of_interest - icon_name : entry=152
UPDATE `trans_words` SET `content_loc6`='Dalaran Cemetary' WHERE `word_id` = 127401; -- locales_points_of_interest - icon_name : entry=147
UPDATE `trans_words` SET `content_loc6`='Dalaran Cloth Armor & Clothing' WHERE `word_id` = 127417; -- locales_points_of_interest - icon_name : entry=163
UPDATE `trans_words` SET `content_loc6`='Dalaran Eastern Sewer Entrance' WHERE `word_id` = 127382; -- locales_points_of_interest - icon_name : entry=126
UPDATE `trans_words` SET `content_loc6`='Dalaran Enchanting Trainer' WHERE `word_id` = 127407; -- locales_points_of_interest - icon_name : entry=153
UPDATE `trans_words` SET `content_loc6`='Dalaran Engineering Trainer' WHERE `word_id` = 127408; -- locales_points_of_interest - icon_name : entry=154
UPDATE `trans_words` SET `content_loc6`='Dalaran Eventide' WHERE `word_id` = 127400; -- locales_points_of_interest - icon_name : entry=146
UPDATE `trans_words` SET `content_loc6`='Dalaran First Aid Trainer' WHERE `word_id` = 127409; -- locales_points_of_interest - icon_name : entry=155
UPDATE `trans_words` SET `content_loc6`='Dalaran Fishing Fountain' WHERE `word_id` = 127410; -- locales_points_of_interest - icon_name : entry=156
UPDATE `trans_words` SET `content_loc6`='Dalaran Flight Master' WHERE `word_id` = 127389; -- locales_points_of_interest - icon_name : entry=134
UPDATE `trans_words` SET `content_loc6`='Dalaran Flowers' WHERE `word_id` = 127418; -- locales_points_of_interest - icon_name : entry=164
UPDATE `trans_words` SET `content_loc6`='Dalaran Fruit Vendor' WHERE `word_id` = 127419; -- locales_points_of_interest - icon_name : entry=165
UPDATE `trans_words` SET `content_loc6`='Dalaran General & Trade Store' WHERE `word_id` = 127420; -- locales_points_of_interest - icon_name : entry=166
UPDATE `trans_words` SET `content_loc6`='Dalaran Herbalism Trainer' WHERE `word_id` = 127411; -- locales_points_of_interest - icon_name : entry=157
UPDATE `trans_words` SET `content_loc6`='Dalaran Horde Inn' WHERE `word_id` = 127392; -- locales_points_of_interest - icon_name : entry=138
UPDATE `trans_words` SET `content_loc6`='Dalaran Inn' WHERE `word_id` = 127390; -- locales_points_of_interest - icon_name : entry=136
UPDATE `trans_words` SET `content_loc6`='Dalaran Inscription Trainer' WHERE `word_id` = 127402; -- locales_points_of_interest - icon_name : entry=148
UPDATE `trans_words` SET `content_loc6`='Dalaran Jewelcrafting Trainer' WHERE `word_id` = 127412; -- locales_points_of_interest - icon_name : entry=158
UPDATE `trans_words` SET `content_loc6`='Dalaran Krasus\' Landing' WHERE `word_id` = 127394; -- locales_points_of_interest - icon_name : entry=140
UPDATE `trans_words` SET `content_loc6`='Dalaran Leather & Mail Armor' WHERE `word_id` = 127436; -- locales_points_of_interest - icon_name : entry=238
UPDATE `trans_words` SET `content_loc6`='Dalaran Leatherworking Trainer' WHERE `word_id` = 127413; -- locales_points_of_interest - icon_name : entry=159
UPDATE `trans_words` SET `content_loc6`='Dalaran Locksmith' WHERE `word_id` = 127393; -- locales_points_of_interest - icon_name : entry=139
UPDATE `trans_words` SET `content_loc6`='Dalaran Mage Trainer' WHERE `word_id` = 127404; -- locales_points_of_interest - icon_name : entry=150
UPDATE `trans_words` SET `content_loc6`='Dalaran Melee Weapons' WHERE `word_id` = 127426; -- locales_points_of_interest - icon_name : entry=172
UPDATE `trans_words` SET `content_loc6`='Dalaran Mining Trainer' WHERE `word_id` = 127414; -- locales_points_of_interest - icon_name : entry=160
UPDATE `trans_words` SET `content_loc6`='Dalaran Northern Bank' WHERE `word_id` = 127386; -- locales_points_of_interest - icon_name : entry=131
UPDATE `trans_words` SET `content_loc6`='Dalaran Pet Store' WHERE `word_id` = 127421; -- locales_points_of_interest - icon_name : entry=167
UPDATE `trans_words` SET `content_loc6`='Dalaran Pie, Pastry & Cake' WHERE `word_id` = 127422; -- locales_points_of_interest - icon_name : entry=168
UPDATE `trans_words` SET `content_loc6`='Dalaran Plate Armor & Shields' WHERE `word_id` = 127437; -- locales_points_of_interest - icon_name : entry=239
UPDATE `trans_words` SET `content_loc6`='Dalaran Ranged Weapons' WHERE `word_id` = 127427; -- locales_points_of_interest - icon_name : entry=173
UPDATE `trans_words` SET `content_loc6`='Dalaran Reagents' WHERE `word_id` = 127423; -- locales_points_of_interest - icon_name : entry=169
UPDATE `trans_words` SET `content_loc6`='Dalaran Runeweaver Square' WHERE `word_id` = 127399; -- locales_points_of_interest - icon_name : entry=145
UPDATE `trans_words` SET `content_loc6`='Dalaran Sewer Arena' WHERE `word_id` = 127439; -- locales_points_of_interest - icon_name : entry=270
UPDATE `trans_words` SET `content_loc6`='Dalaran Sewer Bank' WHERE `word_id` = 127440; -- locales_points_of_interest - icon_name : entry=271
UPDATE `trans_words` SET `content_loc6`='Dalaran Sewer Inn' WHERE `word_id` = 127441; -- locales_points_of_interest - icon_name : entry=272
UPDATE `trans_words` SET `content_loc6`='Dalaran Sewer Tunnel' WHERE `word_id` = 127442; -- locales_points_of_interest - icon_name : entry=273
UPDATE `trans_words` SET `content_loc6`='Dalaran Sewer Vendors' WHERE `word_id` = 127443; -- locales_points_of_interest - icon_name : entry=274
UPDATE `trans_words` SET `content_loc6`='Dalaran Silver Enclave' WHERE `word_id` = 127384; -- locales_points_of_interest - icon_name : entry=129
UPDATE `trans_words` SET `content_loc6`='Dalaran Skinning Trainer' WHERE `word_id` = 127415; -- locales_points_of_interest - icon_name : entry=161
UPDATE `trans_words` SET `content_loc6`='Dalaran Southern Bank' WHERE `word_id` = 127387; -- locales_points_of_interest - icon_name : entry=132
UPDATE `trans_words` SET `content_loc6`='Dalaran Stable Master' WHERE `word_id` = 127403; -- locales_points_of_interest - icon_name : entry=149
UPDATE `trans_words` SET `content_loc6`='Dalaran Staves & Wands' WHERE `word_id` = 127428; -- locales_points_of_interest - icon_name : entry=174
UPDATE `trans_words` SET `content_loc6`='Dalaran Sunreaver\'s Sanctuary' WHERE `word_id` = 127385; -- locales_points_of_interest - icon_name : entry=130
UPDATE `trans_words` SET `content_loc6`='Dalaran Tailoring Trainer' WHERE `word_id` = 127416; -- locales_points_of_interest - icon_name : entry=162
UPDATE `trans_words` SET `content_loc6`='Dalaran Toy Store' WHERE `word_id` = 127424; -- locales_points_of_interest - icon_name : entry=170
UPDATE `trans_words` SET `content_loc6`='Dalaran Trade District' WHERE `word_id` = 127397; -- locales_points_of_interest - icon_name : entry=143
UPDATE `trans_words` SET `content_loc6`='Dalaran Trinkets' WHERE `word_id` = 127425; -- locales_points_of_interest - icon_name : entry=171
UPDATE `trans_words` SET `content_loc6`='Dalaran Violet Citadel' WHERE `word_id` = 127395; -- locales_points_of_interest - icon_name : entry=141
UPDATE `trans_words` SET `content_loc6`='Dalaran Violet Hold' WHERE `word_id` = 127396; -- locales_points_of_interest - icon_name : entry=142
UPDATE `trans_words` SET `content_loc6`='Dalaran Western Sewer Entrance' WHERE `word_id` = 127383; -- locales_points_of_interest - icon_name : entry=127
UPDATE `trans_words` SET `content_loc6`='Dalaran Wine & Cheese' WHERE `word_id` = 127429; -- locales_points_of_interest - icon_name : entry=175
UPDATE `trans_words` SET `content_loc6`='Dalaran: Alchemy Trainer' WHERE `word_id` = 127574; -- locales_points_of_interest - icon_name : entry=1633
UPDATE `trans_words` SET `content_loc6`='Dalaran: Alliance Inn' WHERE `word_id` = 127546; -- locales_points_of_interest - icon_name : entry=1561
UPDATE `trans_words` SET `content_loc6`='Dalaran: Antonidas Memorial' WHERE `word_id` = 127556; -- locales_points_of_interest - icon_name : entry=1589
UPDATE `trans_words` SET `content_loc6`='Dalaran: Barber' WHERE `word_id` = 127543; -- locales_points_of_interest - icon_name : entry=1544
UPDATE `trans_words` SET `content_loc6`='Dalaran: Blacksmithing Trainer' WHERE `word_id` = 127580; -- locales_points_of_interest - icon_name : entry=1640
UPDATE `trans_words` SET `content_loc6`='Dalaran: Cemetary' WHERE `word_id` = 127559; -- locales_points_of_interest - icon_name : entry=1592
UPDATE `trans_words` SET `content_loc6`='Dalaran: Cloth Armor & Clothing' WHERE `word_id` = 127563; -- locales_points_of_interest - icon_name : entry=1616
UPDATE `trans_words` SET `content_loc6`='Dalaran: Eastern Sewer Entrance' WHERE `word_id` = 127538; -- locales_points_of_interest - icon_name : entry=1534
UPDATE `trans_words` SET `content_loc6`='Dalaran: Enchanting Trainer' WHERE `word_id` = 127581; -- locales_points_of_interest - icon_name : entry=1644
UPDATE `trans_words` SET `content_loc6`='Dalaran: Engineering Trainer' WHERE `word_id` = 127582; -- locales_points_of_interest - icon_name : entry=1646
UPDATE `trans_words` SET `content_loc6`='Dalaran: Eventide' WHERE `word_id` = 127558; -- locales_points_of_interest - icon_name : entry=1591
UPDATE `trans_words` SET `content_loc6`='Dalaran: First Aid Trainer' WHERE `word_id` = 127583; -- locales_points_of_interest - icon_name : entry=1648
UPDATE `trans_words` SET `content_loc6`='Dalaran: Fishing Fountain' WHERE `word_id` = 127584; -- locales_points_of_interest - icon_name : entry=1650
UPDATE `trans_words` SET `content_loc6`='Dalaran: Flight Master' WHERE `word_id` = 127544; -- locales_points_of_interest - icon_name : entry=1549
UPDATE `trans_words` SET `content_loc6`='Dalaran: Flowers' WHERE `word_id` = 127566; -- locales_points_of_interest - icon_name : entry=1624
UPDATE `trans_words` SET `content_loc6`='Dalaran: Fruit Vendor' WHERE `word_id` = 127567; -- locales_points_of_interest - icon_name : entry=1625
UPDATE `trans_words` SET `content_loc6`='Dalaran: General & Trade Store' WHERE `word_id` = 127568; -- locales_points_of_interest - icon_name : entry=1626
UPDATE `trans_words` SET `content_loc6`='Dalaran: Herbalism Trainer' WHERE `word_id` = 127585; -- locales_points_of_interest - icon_name : entry=1652
UPDATE `trans_words` SET `content_loc6`='Dalaran: Horde Inn' WHERE `word_id` = 127549; -- locales_points_of_interest - icon_name : entry=1566
UPDATE `trans_words` SET `content_loc6`='Dalaran: Inn' WHERE `word_id` = 127547; -- locales_points_of_interest - icon_name : entry=1562
UPDATE `trans_words` SET `content_loc6`='Dalaran: Inscription Trainer' WHERE `word_id` = 127561; -- locales_points_of_interest - icon_name : entry=1594
UPDATE `trans_words` SET `content_loc6`='Dalaran: Jewelcrafting Trainer' WHERE `word_id` = 127569; -- locales_points_of_interest - icon_name : entry=1627
UPDATE `trans_words` SET `content_loc6`='Dalaran: Krasus\' Landing' WHERE `word_id` = 127552; -- locales_points_of_interest - icon_name : entry=1578
UPDATE `trans_words` SET `content_loc6`='Dalaran: Leatherworking Trainer' WHERE `word_id` = 127586; -- locales_points_of_interest - icon_name : entry=1660
UPDATE `trans_words` SET `content_loc6`='Dalaran: Locksmith' WHERE `word_id` = 127548; -- locales_points_of_interest - icon_name : entry=1564
UPDATE `trans_words` SET `content_loc6`='Dalaran: Mage Trainer' WHERE `word_id` = 127562; -- locales_points_of_interest - icon_name : entry=1598
UPDATE `trans_words` SET `content_loc6`='Dalaran: Mail & Leather Armor' WHERE `word_id` = 127564; -- locales_points_of_interest - icon_name : entry=1617
UPDATE `trans_words` SET `content_loc6`='Dalaran: Melee Weapons' WHERE `word_id` = 127576; -- locales_points_of_interest - icon_name : entry=1635
UPDATE `trans_words` SET `content_loc6`='Dalaran: Mining Trainer' WHERE `word_id` = 127587; -- locales_points_of_interest - icon_name : entry=1662
UPDATE `trans_words` SET `content_loc6`='Dalaran: Northern Bank' WHERE `word_id` = 127550; -- locales_points_of_interest - icon_name : entry=1573
UPDATE `trans_words` SET `content_loc6`='Dalaran: Pet Store' WHERE `word_id` = 127570; -- locales_points_of_interest - icon_name : entry=1628
UPDATE `trans_words` SET `content_loc6`='Dalaran: Pie, Pastry & Cake' WHERE `word_id` = 127571; -- locales_points_of_interest - icon_name : entry=1629
UPDATE `trans_words` SET `content_loc6`='Dalaran: Plate & Shields' WHERE `word_id` = 127565; -- locales_points_of_interest - icon_name : entry=1619
UPDATE `trans_words` SET `content_loc6`='Dalaran: Ranged Weapons' WHERE `word_id` = 127577; -- locales_points_of_interest - icon_name : entry=1636
UPDATE `trans_words` SET `content_loc6`='Dalaran: Reagents' WHERE `word_id` = 127572; -- locales_points_of_interest - icon_name : entry=1630
UPDATE `trans_words` SET `content_loc6`='Dalaran: Runeweaver Square' WHERE `word_id` = 127557; -- locales_points_of_interest - icon_name : entry=1590
UPDATE `trans_words` SET `content_loc6`='Dalaran: Sewer Arena' WHERE `word_id` = 127621; -- locales_points_of_interest - icon_name : entry=1708
UPDATE `trans_words` SET `content_loc6`='Dalaran: Sewer Bank' WHERE `word_id` = 127622; -- locales_points_of_interest - icon_name : entry=1709
UPDATE `trans_words` SET `content_loc6`='Dalaran: Sewer Inn' WHERE `word_id` = 127623; -- locales_points_of_interest - icon_name : entry=1710
UPDATE `trans_words` SET `content_loc6`='Dalaran: Sewer Tunnel' WHERE `word_id` = 127624; -- locales_points_of_interest - icon_name : entry=1711
UPDATE `trans_words` SET `content_loc6`='Dalaran: Sewer Vendors' WHERE `word_id` = 127625; -- locales_points_of_interest - icon_name : entry=1712
UPDATE `trans_words` SET `content_loc6`='Dalaran: Silver Enclave' WHERE `word_id` = 127541; -- locales_points_of_interest - icon_name : entry=1537
UPDATE `trans_words` SET `content_loc6`='Dalaran: Skinning Trainer' WHERE `word_id` = 127588; -- locales_points_of_interest - icon_name : entry=1664
UPDATE `trans_words` SET `content_loc6`='Dalaran: Southern Bank' WHERE `word_id` = 127551; -- locales_points_of_interest - icon_name : entry=1574
UPDATE `trans_words` SET `content_loc6`='Dalaran: Stable Master' WHERE `word_id` = 127560; -- locales_points_of_interest - icon_name : entry=1593
UPDATE `trans_words` SET `content_loc6`='Dalaran: Staves & Wands' WHERE `word_id` = 127578; -- locales_points_of_interest - icon_name : entry=1637
UPDATE `trans_words` SET `content_loc6`='Dalaran: Sunreaver\'s Sanctuary' WHERE `word_id` = 127542; -- locales_points_of_interest - icon_name : entry=1538
UPDATE `trans_words` SET `content_loc6`='Dalaran: Tailoring Trainer' WHERE `word_id` = 127589; -- locales_points_of_interest - icon_name : entry=1666
UPDATE `trans_words` SET `content_loc6`='Dalaran: Toy Store' WHERE `word_id` = 127573; -- locales_points_of_interest - icon_name : entry=1631
UPDATE `trans_words` SET `content_loc6`='Dalaran: Trade District' WHERE `word_id` = 127555; -- locales_points_of_interest - icon_name : entry=1587
UPDATE `trans_words` SET `content_loc6`='Dalaran: Trinkets' WHERE `word_id` = 127575; -- locales_points_of_interest - icon_name : entry=1634
UPDATE `trans_words` SET `content_loc6`='Dalaran: Violet Citadel' WHERE `word_id` = 127553; -- locales_points_of_interest - icon_name : entry=1581
UPDATE `trans_words` SET `content_loc6`='Dalaran: Violet Hold' WHERE `word_id` = 127554; -- locales_points_of_interest - icon_name : entry=1582
UPDATE `trans_words` SET `content_loc6`='Dalaran: Visitor Center' WHERE `word_id` = 127545; -- locales_points_of_interest - icon_name : entry=1551
UPDATE `trans_words` SET `content_loc6`='Dalaran: Well' WHERE `word_id` = 127540; -- locales_points_of_interest - icon_name : entry=1536
UPDATE `trans_words` SET `content_loc6`='Dalaran: Western Sewer Entrance' WHERE `word_id` = 127539; -- locales_points_of_interest - icon_name : entry=1535
UPDATE `trans_words` SET `content_loc6`='Dalaran: Wine & Cheese' WHERE `word_id` = 127579; -- locales_points_of_interest - icon_name : entry=1638
UPDATE `trans_words` SET `content_loc6`='Darkmoon Game Tokens' WHERE `word_id` = 127646; -- locales_points_of_interest - icon_name : entry=460
UPDATE `trans_words` SET `content_loc6`='Darnassus Alchemy Trainer' WHERE `word_id` = 127198; -- locales_points_of_interest - icon_name : entry=102
UPDATE `trans_words` SET `content_loc6`='Darnassus Bank' WHERE `word_id` = 127188; -- locales_points_of_interest - icon_name : entry=1124
UPDATE `trans_words` SET `content_loc6`='Darnassus Blacksmithing' WHERE `word_id` = 127647; -- locales_points_of_interest - icon_name : entry=462
UPDATE `trans_words` SET `content_loc6`='Darnassus Cooking Trainer' WHERE `word_id` = 127199; -- locales_points_of_interest - icon_name : entry=103
UPDATE `trans_words` SET `content_loc6`='Darnassus Druid Trainer' WHERE `word_id` = 127194; -- locales_points_of_interest - icon_name : entry=1133
UPDATE `trans_words` SET `content_loc6`='Darnassus Enchanting Trainer' WHERE `word_id` = 127200; -- locales_points_of_interest - icon_name : entry=104
UPDATE `trans_words` SET `content_loc6`='Darnassus First Aid Trainer' WHERE `word_id` = 127201; -- locales_points_of_interest - icon_name : entry=105
UPDATE `trans_words` SET `content_loc6`='Darnassus Fishing Trainer' WHERE `word_id` = 127202; -- locales_points_of_interest - icon_name : entry=106
UPDATE `trans_words` SET `content_loc6`='Darnassus Guild Master' WHERE `word_id` = 127190; -- locales_points_of_interest - icon_name : entry=1127
UPDATE `trans_words` SET `content_loc6`='Darnassus Herbalism Trainer' WHERE `word_id` = 127249; -- locales_points_of_interest - icon_name : entry=1143
UPDATE `trans_words` SET `content_loc6`='Darnassus Hippogryph Master' WHERE `word_id` = 127189; -- locales_points_of_interest - icon_name : entry=91
UPDATE `trans_words` SET `content_loc6`='Darnassus Hunter Trainer' WHERE `word_id` = 127195; -- locales_points_of_interest - icon_name : entry=1134
UPDATE `trans_words` SET `content_loc6`='Darnassus Inn' WHERE `word_id` = 127191; -- locales_points_of_interest - icon_name : entry=1128
UPDATE `trans_words` SET `content_loc6`='Darnassus Inscription' WHERE `word_id` = 127381; -- locales_points_of_interest - icon_name : entry=107
UPDATE `trans_words` SET `content_loc6`='Darnassus Leatherworking Trainer' WHERE `word_id` = 127203; -- locales_points_of_interest - icon_name : entry=108
UPDATE `trans_words` SET `content_loc6`='Darnassus Mage Trainer' WHERE `word_id` = 127373; -- locales_points_of_interest - icon_name : entry=265
UPDATE `trans_words` SET `content_loc6`='Darnassus Mailbox' WHERE `word_id` = 127192; -- locales_points_of_interest - icon_name : entry=1129
UPDATE `trans_words` SET `content_loc6`='Darnassus Paladin Trainer' WHERE `word_id` = 127374; -- locales_points_of_interest - icon_name : entry=266
UPDATE `trans_words` SET `content_loc6`='Darnassus Rogue Trainer' WHERE `word_id` = 127196; -- locales_points_of_interest - icon_name : entry=100
UPDATE `trans_words` SET `content_loc6`='Darnassus Skinning Trainer' WHERE `word_id` = 127204; -- locales_points_of_interest - icon_name : entry=109
UPDATE `trans_words` SET `content_loc6`='Darnassus Tailor' WHERE `word_id` = 127205; -- locales_points_of_interest - icon_name : entry=110
UPDATE `trans_words` SET `content_loc6`='Dedlow Wormwood' WHERE `word_id` = 104383; -- locales_points_of_interest - icon_name : entry=461
UPDATE `trans_words` SET `content_loc6`='Deepmountain Mining & Jewelcrafting' WHERE `word_id` = 120911; -- locales_points_of_interest - icon_name : entry=74
UPDATE `trans_words` SET `content_loc6`='Dolanaar Inn' WHERE `word_id` = 127206; -- locales_points_of_interest - icon_name : entry=111
UPDATE `trans_words` SET `content_loc6`='Embassy of the Horde' WHERE `word_id` = 127636; -- locales_points_of_interest - icon_name : entry=1903
UPDATE `trans_words` SET `content_loc6`='Eversong Woods, Leatherworker' WHERE `word_id` = 127371; -- locales_points_of_interest - icon_name : entry=398
UPDATE `trans_words` SET `content_loc6`='Eversong Woods, Skinner' WHERE `word_id` = 127372; -- locales_points_of_interest - icon_name : entry=399
UPDATE `trans_words` SET `content_loc6`='Eversong Woods: Leatherworker' WHERE `word_id` = 127481; -- locales_points_of_interest - icon_name : entry=1418
UPDATE `trans_words` SET `content_loc6`='Eversong Woods: Skinning Trainer' WHERE `word_id` = 127483; -- locales_points_of_interest - icon_name : entry=1421
UPDATE `trans_words` SET `content_loc6`='Exodar Inscription Trainer' WHERE `word_id` = 127459; -- locales_points_of_interest - icon_name : entry=1354
UPDATE `trans_words` SET `content_loc6`='Exodar Inscription' WHERE `word_id` = 127432; -- locales_points_of_interest - icon_name : entry=212
UPDATE `trans_words` SET `content_loc6`='Exodar, Alchemist Trainers' WHERE `word_id` = 127269; -- locales_points_of_interest - icon_name : entry=205
UPDATE `trans_words` SET `content_loc6`='Exodar, Auctioneer' WHERE `word_id` = 127254; -- locales_points_of_interest - icon_name : entry=190
UPDATE `trans_words` SET `content_loc6`='Exodar, bank' WHERE `word_id` = 127255; -- locales_points_of_interest - icon_name : entry=191
UPDATE `trans_words` SET `content_loc6`='Exodar, Battlemasters' WHERE `word_id` = 127375; -- locales_points_of_interest - icon_name : entry=263
UPDATE `trans_words` SET `content_loc6`='Exodar, Blacksmithing Trainers' WHERE `word_id` = 127270; -- locales_points_of_interest - icon_name : entry=206
UPDATE `trans_words` SET `content_loc6`='Exodar, Cook' WHERE `word_id` = 127281; -- locales_points_of_interest - icon_name : entry=218
UPDATE `trans_words` SET `content_loc6`='Exodar, Druid Trainer' WHERE `word_id` = 127262; -- locales_points_of_interest - icon_name : entry=198
UPDATE `trans_words` SET `content_loc6`='Exodar, Enchanters' WHERE `word_id` = 127271; -- locales_points_of_interest - icon_name : entry=207
UPDATE `trans_words` SET `content_loc6`='Exodar, Engineering' WHERE `word_id` = 127272; -- locales_points_of_interest - icon_name : entry=208
UPDATE `trans_words` SET `content_loc6`='Exodar, First Aid Trainer' WHERE `word_id` = 127273; -- locales_points_of_interest - icon_name : entry=209
UPDATE `trans_words` SET `content_loc6`='Exodar, Fishing Trainer' WHERE `word_id` = 127274; -- locales_points_of_interest - icon_name : entry=210
UPDATE `trans_words` SET `content_loc6`='Exodar, Guild Master' WHERE `word_id` = 127257; -- locales_points_of_interest - icon_name : entry=193
UPDATE `trans_words` SET `content_loc6`='Exodar, Herbalist Trainer' WHERE `word_id` = 127275; -- locales_points_of_interest - icon_name : entry=211
UPDATE `trans_words` SET `content_loc6`='Exodar, Hippogryph Master' WHERE `word_id` = 127256; -- locales_points_of_interest - icon_name : entry=192
UPDATE `trans_words` SET `content_loc6`='Exodar, Hunter Trainers' WHERE `word_id` = 127263; -- locales_points_of_interest - icon_name : entry=199
UPDATE `trans_words` SET `content_loc6`='Exodar, Inn' WHERE `word_id` = 127258; -- locales_points_of_interest - icon_name : entry=194
UPDATE `trans_words` SET `content_loc6`='Exodar, Jewelcrafters' WHERE `word_id` = 127276; -- locales_points_of_interest - icon_name : entry=213
UPDATE `trans_words` SET `content_loc6`='Exodar, Leatherworking' WHERE `word_id` = 127277; -- locales_points_of_interest - icon_name : entry=214
UPDATE `trans_words` SET `content_loc6`='Exodar, Mage Trainers' WHERE `word_id` = 127264; -- locales_points_of_interest - icon_name : entry=200
UPDATE `trans_words` SET `content_loc6`='Exodar, Mailbox' WHERE `word_id` = 127259; -- locales_points_of_interest - icon_name : entry=195
UPDATE `trans_words` SET `content_loc6`='Exodar, Mining Trainers' WHERE `word_id` = 127278; -- locales_points_of_interest - icon_name : entry=215
UPDATE `trans_words` SET `content_loc6`='Exodar, Paladin Trainers' WHERE `word_id` = 127265; -- locales_points_of_interest - icon_name : entry=201
UPDATE `trans_words` SET `content_loc6`='Exodar, Priest Trainers' WHERE `word_id` = 127266; -- locales_points_of_interest - icon_name : entry=202
UPDATE `trans_words` SET `content_loc6`='Exodar, Shaman Trainer' WHERE `word_id` = 127267; -- locales_points_of_interest - icon_name : entry=203
UPDATE `trans_words` SET `content_loc6`='Exodar, Skinning Trainer' WHERE `word_id` = 127279; -- locales_points_of_interest - icon_name : entry=216
UPDATE `trans_words` SET `content_loc6`='Exodar, Stable Master' WHERE `word_id` = 127260; -- locales_points_of_interest - icon_name : entry=196
UPDATE `trans_words` SET `content_loc6`='Exodar, Tailors' WHERE `word_id` = 127280; -- locales_points_of_interest - icon_name : entry=217
UPDATE `trans_words` SET `content_loc6`='Exodar, Warrior Trainers' WHERE `word_id` = 127268; -- locales_points_of_interest - icon_name : entry=204
UPDATE `trans_words` SET `content_loc6`='Exodar, Weapon Master' WHERE `word_id` = 127261; -- locales_points_of_interest - icon_name : entry=197
UPDATE `trans_words` SET `content_loc6`='Exodar: Alchemy Trainer' WHERE `word_id` = 127607; -- locales_points_of_interest - icon_name : entry=1689
UPDATE `trans_words` SET `content_loc6`='Exodar: Arena Battlemaster' WHERE `word_id` = 127599; -- locales_points_of_interest - icon_name : entry=1681
UPDATE `trans_words` SET `content_loc6`='Exodar: Auction House' WHERE `word_id` = 127590; -- locales_points_of_interest - icon_name : entry=1668
UPDATE `trans_words` SET `content_loc6`='Exodar: Bank' WHERE `word_id` = 127591; -- locales_points_of_interest - icon_name : entry=1669
UPDATE `trans_words` SET `content_loc6`='Exodar: Battlemaster' WHERE `word_id` = 127598; -- locales_points_of_interest - icon_name : entry=1680
UPDATE `trans_words` SET `content_loc6`='Exodar: Blacksmithing Trainer' WHERE `word_id` = 127608; -- locales_points_of_interest - icon_name : entry=1690
UPDATE `trans_words` SET `content_loc6`='Exodar: Cooking Trainer' WHERE `word_id` = 127620; -- locales_points_of_interest - icon_name : entry=1707
UPDATE `trans_words` SET `content_loc6`='Exodar: Druid Trainer' WHERE `word_id` = 127600; -- locales_points_of_interest - icon_name : entry=1682
UPDATE `trans_words` SET `content_loc6`='Exodar: Enchanting Trainer' WHERE `word_id` = 127609; -- locales_points_of_interest - icon_name : entry=1691
UPDATE `trans_words` SET `content_loc6`='Exodar: Engineering Trainer' WHERE `word_id` = 127610; -- locales_points_of_interest - icon_name : entry=1693
UPDATE `trans_words` SET `content_loc6`='Exodar: First Aid Trainer' WHERE `word_id` = 127611; -- locales_points_of_interest - icon_name : entry=1695
UPDATE `trans_words` SET `content_loc6`='Exodar: Fishing Trainer' WHERE `word_id` = 127612; -- locales_points_of_interest - icon_name : entry=1697
UPDATE `trans_words` SET `content_loc6`='Exodar: Guild Master' WHERE `word_id` = 127593; -- locales_points_of_interest - icon_name : entry=1673
UPDATE `trans_words` SET `content_loc6`='Exodar: Herbalist Trainer' WHERE `word_id` = 127613; -- locales_points_of_interest - icon_name : entry=1698
UPDATE `trans_words` SET `content_loc6`='Exodar: Hippogryph Master' WHERE `word_id` = 127592; -- locales_points_of_interest - icon_name : entry=1671
UPDATE `trans_words` SET `content_loc6`='Exodar: Hunter Trainer' WHERE `word_id` = 127601; -- locales_points_of_interest - icon_name : entry=1683
UPDATE `trans_words` SET `content_loc6`='Exodar: Inn' WHERE `word_id` = 127595; -- locales_points_of_interest - icon_name : entry=1676
UPDATE `trans_words` SET `content_loc6`='Exodar: Inscription Trainer' WHERE `word_id` = 127614; -- locales_points_of_interest - icon_name : entry=1701
UPDATE `trans_words` SET `content_loc6`='Exodar: Jewelcrafting Trainer' WHERE `word_id` = 127615; -- locales_points_of_interest - icon_name : entry=1702
UPDATE `trans_words` SET `content_loc6`='Exodar: Leatherworking Trainer' WHERE `word_id` = 127616; -- locales_points_of_interest - icon_name : entry=1703
UPDATE `trans_words` SET `content_loc6`='Exodar: Mage Trainer' WHERE `word_id` = 127602; -- locales_points_of_interest - icon_name : entry=1684
UPDATE `trans_words` SET `content_loc6`='Exodar: Mailbox' WHERE `word_id` = 127594; -- locales_points_of_interest - icon_name : entry=1675
UPDATE `trans_words` SET `content_loc6`='Exodar: Mining Trainer' WHERE `word_id` = 127617; -- locales_points_of_interest - icon_name : entry=1704
UPDATE `trans_words` SET `content_loc6`='Exodar: Paladin Trainer' WHERE `word_id` = 127603; -- locales_points_of_interest - icon_name : entry=1685
UPDATE `trans_words` SET `content_loc6`='Exodar: Priest Trainer' WHERE `word_id` = 127604; -- locales_points_of_interest - icon_name : entry=1686
UPDATE `trans_words` SET `content_loc6`='Exodar: Shaman Trainer' WHERE `word_id` = 127605; -- locales_points_of_interest - icon_name : entry=1687
UPDATE `trans_words` SET `content_loc6`='Exodar: Skinning Trainer' WHERE `word_id` = 127618; -- locales_points_of_interest - icon_name : entry=1705
UPDATE `trans_words` SET `content_loc6`='Exodar: Stable Master' WHERE `word_id` = 127596; -- locales_points_of_interest - icon_name : entry=1677
UPDATE `trans_words` SET `content_loc6`='Exodar: Tailor Trainer' WHERE `word_id` = 127619; -- locales_points_of_interest - icon_name : entry=1706
UPDATE `trans_words` SET `content_loc6`='Exodar: Warrior Trainer' WHERE `word_id` = 127606; -- locales_points_of_interest - icon_name : entry=1688
UPDATE `trans_words` SET `content_loc6`='Exodar: Weapon Master' WHERE `word_id` = 127597; -- locales_points_of_interest - icon_name : entry=1679
UPDATE `trans_words` SET `content_loc6`='Falconwing Square, Cook' WHERE `word_id` = 127366; -- locales_points_of_interest - icon_name : entry=393
UPDATE `trans_words` SET `content_loc6`='Falconwing Square, First Aid Trainer' WHERE `word_id` = 127368; -- locales_points_of_interest - icon_name : entry=395
UPDATE `trans_words` SET `content_loc6`='Falconwing Square, Hunter Trainer' WHERE `word_id` = 127358; -- locales_points_of_interest - icon_name : entry=385
UPDATE `trans_words` SET `content_loc6`='Falconwing Square, Innkeeper' WHERE `word_id` = 127356; -- locales_points_of_interest - icon_name : entry=383
UPDATE `trans_words` SET `content_loc6`='Falconwing Square, Jewelcrafter' WHERE `word_id` = 127370; -- locales_points_of_interest - icon_name : entry=397
UPDATE `trans_words` SET `content_loc6`='Falconwing Square, Mage Trainer' WHERE `word_id` = 127359; -- locales_points_of_interest - icon_name : entry=386
UPDATE `trans_words` SET `content_loc6`='Falconwing Square, Priest Trainer' WHERE `word_id` = 127361; -- locales_points_of_interest - icon_name : entry=388
UPDATE `trans_words` SET `content_loc6`='Falconwing Square, Rogue Trainer' WHERE `word_id` = 127362; -- locales_points_of_interest - icon_name : entry=389
UPDATE `trans_words` SET `content_loc6`='Falconwing Square, Stable Master' WHERE `word_id` = 127357; -- locales_points_of_interest - icon_name : entry=384
UPDATE `trans_words` SET `content_loc6`='Falconwing Square, Warlock Trainer' WHERE `word_id` = 127363; -- locales_points_of_interest - icon_name : entry=390
UPDATE `trans_words` SET `content_loc6`='Falconwing Square: Cook' WHERE `word_id` = 127476; -- locales_points_of_interest - icon_name : entry=1411
UPDATE `trans_words` SET `content_loc6`='Falconwing Square: First Aid' WHERE `word_id` = 127469; -- locales_points_of_interest - icon_name : entry=1414
UPDATE `trans_words` SET `content_loc6`='Falconwing Square: Hunter Trainer' WHERE `word_id` = 127467; -- locales_points_of_interest - icon_name : entry=1403
UPDATE `trans_words` SET `content_loc6`='Falconwing Square: Innkeeper' WHERE `word_id` = 127465; -- locales_points_of_interest - icon_name : entry=1401
UPDATE `trans_words` SET `content_loc6`='Falconwing Square: Jewelcrafter' WHERE `word_id` = 127480; -- locales_points_of_interest - icon_name : entry=1417
UPDATE `trans_words` SET `content_loc6`='Falconwing Square: Mage Trainer' WHERE `word_id` = 127468; -- locales_points_of_interest - icon_name : entry=1404
UPDATE `trans_words` SET `content_loc6`='Falconwing Square: Paladin Trainer' WHERE `word_id` = 127470; -- locales_points_of_interest - icon_name : entry=1405
UPDATE `trans_words` SET `content_loc6`='Falconwing Square: Priest Trainer' WHERE `word_id` = 127471; -- locales_points_of_interest - icon_name : entry=1406
UPDATE `trans_words` SET `content_loc6`='Falconwing Square: Rogue Trainer' WHERE `word_id` = 127472; -- locales_points_of_interest - icon_name : entry=1407
UPDATE `trans_words` SET `content_loc6`='Falconwing Square: Stable Master' WHERE `word_id` = 127466; -- locales_points_of_interest - icon_name : entry=1402
UPDATE `trans_words` SET `content_loc6`='Falconwing Square: Warlock Trainer' WHERE `word_id` = 127473; -- locales_points_of_interest - icon_name : entry=1408
UPDATE `trans_words` SET `content_loc6`='Farstrider Retreat, Blacksmith' WHERE `word_id` = 127365; -- locales_points_of_interest - icon_name : entry=392
UPDATE `trans_words` SET `content_loc6`='Farstrider Retreat: Blacksmith' WHERE `word_id` = 127475; -- locales_points_of_interest - icon_name : entry=1410
UPDATE `trans_words` SET `content_loc6`='Flight Master of Orgrimmar' WHERE `word_id` = 127635; -- locales_points_of_interest - icon_name : entry=1902
UPDATE `trans_words` SET `content_loc6`='Goblin Brewfest Ram Racing' WHERE `word_id` = 127627; -- locales_points_of_interest - icon_name : entry=1714
UPDATE `trans_words` SET `content_loc6`='Goblin Brewfest Souvenirs' WHERE `word_id` = 127626; -- locales_points_of_interest - icon_name : entry=1713
UPDATE `trans_words` SET `content_loc6`='Guns Darkmoon Faire' WHERE `word_id` = 127632; -- locales_points_of_interest - icon_name : entry=1719
UPDATE `trans_words` SET `content_loc6`='Hunter Lodge' WHERE `word_id` = 127173; -- locales_points_of_interest - icon_name : entry=1037
UPDATE `trans_words` SET `content_loc6`='Ironforge Archaeology' WHERE `word_id` = 127644; -- locales_points_of_interest - icon_name : entry=456
UPDATE `trans_words` SET `content_loc6`='Ironforge Barber' WHERE `word_id` = 127379; -- locales_points_of_interest - icon_name : entry=1075
UPDATE `trans_words` SET `content_loc6`='Ironforge Druid Trainer' WHERE `word_id` = 127643; -- locales_points_of_interest - icon_name : entry=455
UPDATE `trans_words` SET `content_loc6`='Ironforge Gryphon Master' WHERE `word_id` = 127179; -- locales_points_of_interest - icon_name : entry=1067
UPDATE `trans_words` SET `content_loc6`='Ironforge Inscription' WHERE `word_id` = 127380; -- locales_points_of_interest - icon_name : entry=1097
UPDATE `trans_words` SET `content_loc6`='Ironforge Mailbox' WHERE `word_id` = 127181; -- locales_points_of_interest - icon_name : entry=1069
UPDATE `trans_words` SET `content_loc6`='Ironforge Rogue Trainer' WHERE `word_id` = 127184; -- locales_points_of_interest - icon_name : entry=1082
UPDATE `trans_words` SET `content_loc6`='Ironforge Shaman Trainer' WHERE `word_id` = 127251; -- locales_points_of_interest - icon_name : entry=1086
UPDATE `trans_words` SET `content_loc6`='Ironforge Warlock Trainer' WHERE `word_id` = 127185; -- locales_points_of_interest - icon_name : entry=1084
UPDATE `trans_words` SET `content_loc6`='Odesyus Landing: Blacksmith' WHERE `word_id` = 127454; -- locales_points_of_interest - icon_name : entry=1346
UPDATE `trans_words` SET `content_loc6`='Odesyus Landing: Cook' WHERE `word_id` = 127455; -- locales_points_of_interest - icon_name : entry=1348
UPDATE `trans_words` SET `content_loc6`='Odesyus Landing: Tailor' WHERE `word_id` = 127463; -- locales_points_of_interest - icon_name : entry=1359
UPDATE `trans_words` SET `content_loc6`='Odesyus\' Landing, Blacksmith' WHERE `word_id` = 127291; -- locales_points_of_interest - icon_name : entry=228
UPDATE `trans_words` SET `content_loc6`='Odesyus\' Landing, Cook' WHERE `word_id` = 127292; -- locales_points_of_interest - icon_name : entry=229
UPDATE `trans_words` SET `content_loc6`='Odesyus\' Landing, Tailor' WHERE `word_id` = 127300; -- locales_points_of_interest - icon_name : entry=237
UPDATE `trans_words` SET `content_loc6`='Orgrimmar Barber' WHERE `word_id` = 127430; -- locales_points_of_interest - icon_name : entry=10018
UPDATE `trans_words` SET `content_loc6`='Orgrimmar Battlemasters' WHERE `word_id` = 127645; -- locales_points_of_interest - icon_name : entry=459
UPDATE `trans_words` SET `content_loc6`='Orgrimmar Eastern Zeppelin Tower' WHERE `word_id` = 127252; -- locales_points_of_interest - icon_name : entry=1231
UPDATE `trans_words` SET `content_loc6`='Orgrimmar Ethereals' WHERE `word_id` = 127640; -- locales_points_of_interest - icon_name : entry=458
UPDATE `trans_words` SET `content_loc6`='Orgrimmar Hunter\'s Hall' WHERE `word_id` = 127248; -- locales_points_of_interest - icon_name : entry=1204
UPDATE `trans_words` SET `content_loc6`='Orgrimmar Inn' WHERE `word_id` = 127208; -- locales_points_of_interest - icon_name : entry=1190
UPDATE `trans_words` SET `content_loc6`='Orgrimmar Inscription' WHERE `word_id` = 127431; -- locales_points_of_interest - icon_name : entry=1182
UPDATE `trans_words` SET `content_loc6`='Orgrimmar Mailbox' WHERE `word_id` = 127209; -- locales_points_of_interest - icon_name : entry=1192
UPDATE `trans_words` SET `content_loc6`='Orgrimmar Western Zeppelin Tower' WHERE `word_id` = 127253; -- locales_points_of_interest - icon_name : entry=1195
UPDATE `trans_words` SET `content_loc6`='Orgrimmar: Portals' WHERE `word_id` = 127637; -- locales_points_of_interest - icon_name : entry=12245
UPDATE `trans_words` SET `content_loc6`='Orgrimmar: The auction house' WHERE `word_id` = 127633; -- locales_points_of_interest - icon_name : entry=12628
UPDATE `trans_words` SET `content_loc6`='Orgrimmar:' WHERE `word_id` = 127634; -- locales_points_of_interest - icon_name : entry=1912
UPDATE `trans_words` SET `content_loc6`='Razor Hill Inn' WHERE `word_id` = 127213; -- locales_points_of_interest - icon_name : entry=1165
UPDATE `trans_words` SET `content_loc6`='Saltheril\'s Haven, Alchemist' WHERE `word_id` = 127364; -- locales_points_of_interest - icon_name : entry=391
UPDATE `trans_words` SET `content_loc6`='Saltheril\'s Haven, Enchanter' WHERE `word_id` = 127367; -- locales_points_of_interest - icon_name : entry=394
UPDATE `trans_words` SET `content_loc6`='Saltheril\'s Haven, Herbalist' WHERE `word_id` = 127369; -- locales_points_of_interest - icon_name : entry=396
UPDATE `trans_words` SET `content_loc6`='Saltheril\'s Haven, Tailor' WHERE `word_id` = 127247; -- locales_points_of_interest - icon_name : entry=400
UPDATE `trans_words` SET `content_loc6`='Saltheril\'s Haven: Alchemist' WHERE `word_id` = 127474; -- locales_points_of_interest - icon_name : entry=1409
UPDATE `trans_words` SET `content_loc6`='Saltheril\'s Haven: Enchanter' WHERE `word_id` = 127477; -- locales_points_of_interest - icon_name : entry=1412
UPDATE `trans_words` SET `content_loc6`='Saltheril\'s Haven: Herbalist' WHERE `word_id` = 127478; -- locales_points_of_interest - icon_name : entry=1415
UPDATE `trans_words` SET `content_loc6`='Saltheril\'s Haven: Tailor' WHERE `word_id` = 127482; -- locales_points_of_interest - icon_name : entry=1420
UPDATE `trans_words` SET `content_loc6`='Sayoc & Hanashi' WHERE `word_id` = 127211; -- locales_points_of_interest - icon_name : entry=1196
UPDATE `trans_words` SET `content_loc6`='Scryer Gem Vendor' WHERE `word_id` = 127325; -- locales_points_of_interest - icon_name : entry=258
UPDATE `trans_words` SET `content_loc6`='Shattrath Alchemist' WHERE `word_id` = 127305; -- locales_points_of_interest - icon_name : entry=248
UPDATE `trans_words` SET `content_loc6`='Shattrath Alchemy Lab' WHERE `word_id` = 127314; -- locales_points_of_interest - icon_name : entry=257
UPDATE `trans_words` SET `content_loc6`='Shattrath Arena Battlemasters' WHERE `word_id` = 127323; -- locales_points_of_interest - icon_name : entry=262
UPDATE `trans_words` SET `content_loc6`='Shattrath Armor/Weapon Crafter' WHERE `word_id` = 127306; -- locales_points_of_interest - icon_name : entry=249
UPDATE `trans_words` SET `content_loc6`='Shattrath Bank Aldor' WHERE `word_id` = 127315; -- locales_points_of_interest - icon_name : entry=260
UPDATE `trans_words` SET `content_loc6`='Shattrath Bank Scryer' WHERE `word_id` = 127316; -- locales_points_of_interest - icon_name : entry=241
UPDATE `trans_words` SET `content_loc6`='Shattrath Battlemasters Alliance' WHERE `word_id` = 127321; -- locales_points_of_interest - icon_name : entry=246
UPDATE `trans_words` SET `content_loc6`='Shattrath Battlemasters Horde' WHERE `word_id` = 127322; -- locales_points_of_interest - icon_name : entry=247
UPDATE `trans_words` SET `content_loc6`='Shattrath Cantina' WHERE `word_id` = 127303; -- locales_points_of_interest - icon_name : entry=240
UPDATE `trans_words` SET `content_loc6`='Shattrath Cook' WHERE `word_id` = 127307; -- locales_points_of_interest - icon_name : entry=250
UPDATE `trans_words` SET `content_loc6`='Shattrath Enchanters' WHERE `word_id` = 127308; -- locales_points_of_interest - icon_name : entry=251
UPDATE `trans_words` SET `content_loc6`='Shattrath First Aid' WHERE `word_id` = 127309; -- locales_points_of_interest - icon_name : entry=252
UPDATE `trans_words` SET `content_loc6`='Shattrath Inn Aldor' WHERE `word_id` = 127317; -- locales_points_of_interest - icon_name : entry=261
UPDATE `trans_words` SET `content_loc6`='Shattrath Inn Scryer' WHERE `word_id` = 127318; -- locales_points_of_interest - icon_name : entry=242
UPDATE `trans_words` SET `content_loc6`='Shattrath Jewelcrafter' WHERE `word_id` = 127310; -- locales_points_of_interest - icon_name : entry=253
UPDATE `trans_words` SET `content_loc6`='Shattrath Leatherworker' WHERE `word_id` = 127311; -- locales_points_of_interest - icon_name : entry=254
UPDATE `trans_words` SET `content_loc6`='Shattrath Mana Loom' WHERE `word_id` = 127313; -- locales_points_of_interest - icon_name : entry=256
UPDATE `trans_words` SET `content_loc6`='Shattrath Skinner' WHERE `word_id` = 127312; -- locales_points_of_interest - icon_name : entry=255
UPDATE `trans_words` SET `content_loc6`='Shattrath Stable Aldor' WHERE `word_id` = 127319; -- locales_points_of_interest - icon_name : entry=244
UPDATE `trans_words` SET `content_loc6`='Shattrath Stable Scryer' WHERE `word_id` = 127320; -- locales_points_of_interest - icon_name : entry=245
UPDATE `trans_words` SET `content_loc6`='Shattrath Taxi' WHERE `word_id` = 127304; -- locales_points_of_interest - icon_name : entry=243
UPDATE `trans_words` SET `content_loc6`='Shattrath: Alchemist' WHERE `word_id` = 127528; -- locales_points_of_interest - icon_name : entry=1520
UPDATE `trans_words` SET `content_loc6`='Shattrath: Alchemy Laboratory' WHERE `word_id` = 127537; -- locales_points_of_interest - icon_name : entry=1533
UPDATE `trans_words` SET `content_loc6`='Shattrath: Aldor Bank' WHERE `word_id` = 127516; -- locales_points_of_interest - icon_name : entry=1501
UPDATE `trans_words` SET `content_loc6`='Shattrath: Aldor Gem Merchant' WHERE `word_id` = 127526; -- locales_points_of_interest - icon_name : entry=1517
UPDATE `trans_words` SET `content_loc6`='Shattrath: Aldor Inn' WHERE `word_id` = 127518; -- locales_points_of_interest - icon_name : entry=1503
UPDATE `trans_words` SET `content_loc6`='Shattrath: Aldor Stable' WHERE `word_id` = 127521; -- locales_points_of_interest - icon_name : entry=1511
UPDATE `trans_words` SET `content_loc6`='Shattrath: Alliance Battlemasters' WHERE `word_id` = 127523; -- locales_points_of_interest - icon_name : entry=1513
UPDATE `trans_words` SET `content_loc6`='Shattrath: Arena Battlemasters' WHERE `word_id` = 127525; -- locales_points_of_interest - icon_name : entry=1516
UPDATE `trans_words` SET `content_loc6`='Shattrath: Cook' WHERE `word_id` = 127530; -- locales_points_of_interest - icon_name : entry=1523
UPDATE `trans_words` SET `content_loc6`='Shattrath: Enchanters' WHERE `word_id` = 127531; -- locales_points_of_interest - icon_name : entry=1524
UPDATE `trans_words` SET `content_loc6`='Shattrath: First Aid' WHERE `word_id` = 127532; -- locales_points_of_interest - icon_name : entry=1527
UPDATE `trans_words` SET `content_loc6`='Shattrath: Flight Master' WHERE `word_id` = 127520; -- locales_points_of_interest - icon_name : entry=1505
UPDATE `trans_words` SET `content_loc6`='Shattrath: Grocery Store' WHERE `word_id` = 127515; -- locales_points_of_interest - icon_name : entry=1500
UPDATE `trans_words` SET `content_loc6`='Shattrath: Horde Battlemasters' WHERE `word_id` = 127524; -- locales_points_of_interest - icon_name : entry=1515
UPDATE `trans_words` SET `content_loc6`='Shattrath: Jewelcrafter' WHERE `word_id` = 127533; -- locales_points_of_interest - icon_name : entry=1528
UPDATE `trans_words` SET `content_loc6`='Shattrath: Leatherworker' WHERE `word_id` = 127534; -- locales_points_of_interest - icon_name : entry=1529
UPDATE `trans_words` SET `content_loc6`='Shattrath: Mana Spinning Machine Tools' WHERE `word_id` = 127536; -- locales_points_of_interest - icon_name : entry=1532
UPDATE `trans_words` SET `content_loc6`='Shattrath: Scryers Bank' WHERE `word_id` = 127517; -- locales_points_of_interest - icon_name : entry=1502
UPDATE `trans_words` SET `content_loc6`='Shattrath: Scryers Gem Merchant' WHERE `word_id` = 127527; -- locales_points_of_interest - icon_name : entry=1518
UPDATE `trans_words` SET `content_loc6`='Shattrath: Scryers Inn' WHERE `word_id` = 127519; -- locales_points_of_interest - icon_name : entry=1504
UPDATE `trans_words` SET `content_loc6`='Shattrath: Scryers Stable' WHERE `word_id` = 127522; -- locales_points_of_interest - icon_name : entry=1512
UPDATE `trans_words` SET `content_loc6`='Shattrath: Skinning Trainer' WHERE `word_id` = 127535; -- locales_points_of_interest - icon_name : entry=1530
UPDATE `trans_words` SET `content_loc6`='Shattrath: Weaponsmith and Armorsmith' WHERE `word_id` = 127529; -- locales_points_of_interest - icon_name : entry=1521
UPDATE `trans_words` SET `content_loc6`='Silvermoon City Inscription' WHERE `word_id` = 127438; -- locales_points_of_interest - icon_name : entry=376
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Alchemy' WHERE `word_id` = 127342; -- locales_points_of_interest - icon_name : entry=368
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Auction House' WHERE `word_id` = 127326; -- locales_points_of_interest - icon_name : entry=349
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Bank' WHERE `word_id` = 127327; -- locales_points_of_interest - icon_name : entry=351
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Battlemasters' WHERE `word_id` = 127334; -- locales_points_of_interest - icon_name : entry=360
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Blacksmithing' WHERE `word_id` = 127343; -- locales_points_of_interest - icon_name : entry=369
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Cooking' WHERE `word_id` = 127344; -- locales_points_of_interest - icon_name : entry=370
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Druid Trainer' WHERE `word_id` = 127335; -- locales_points_of_interest - icon_name : entry=361
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Enchanting' WHERE `word_id` = 127345; -- locales_points_of_interest - icon_name : entry=371
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Engineering' WHERE `word_id` = 127346; -- locales_points_of_interest - icon_name : entry=372
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, First Aid' WHERE `word_id` = 127347; -- locales_points_of_interest - icon_name : entry=373
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Fishing' WHERE `word_id` = 127348; -- locales_points_of_interest - icon_name : entry=374
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Flight Master' WHERE `word_id` = 127328; -- locales_points_of_interest - icon_name : entry=353
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Guild House' WHERE `word_id` = 127329; -- locales_points_of_interest - icon_name : entry=354
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Herbalism' WHERE `word_id` = 127349; -- locales_points_of_interest - icon_name : entry=375
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Hunter Trainer' WHERE `word_id` = 127336; -- locales_points_of_interest - icon_name : entry=362
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Inn' WHERE `word_id` = 127330; -- locales_points_of_interest - icon_name : entry=355
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Jewelcrafting' WHERE `word_id` = 127350; -- locales_points_of_interest - icon_name : entry=377
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Leatherworking' WHERE `word_id` = 127351; -- locales_points_of_interest - icon_name : entry=378
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Mage Trainer' WHERE `word_id` = 127337; -- locales_points_of_interest - icon_name : entry=363
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Mailbox' WHERE `word_id` = 127331; -- locales_points_of_interest - icon_name : entry=357
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Mana Loom' WHERE `word_id` = 127355; -- locales_points_of_interest - icon_name : entry=382
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Mining' WHERE `word_id` = 127352; -- locales_points_of_interest - icon_name : entry=379
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Paladin Trainer' WHERE `word_id` = 127338; -- locales_points_of_interest - icon_name : entry=364
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Priest Trainer' WHERE `word_id` = 127339; -- locales_points_of_interest - icon_name : entry=365
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Rogue Trainer' WHERE `word_id` = 127340; -- locales_points_of_interest - icon_name : entry=366
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Skinning' WHERE `word_id` = 127353; -- locales_points_of_interest - icon_name : entry=380
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Stable Master' WHERE `word_id` = 127332; -- locales_points_of_interest - icon_name : entry=358
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Tailoring' WHERE `word_id` = 127354; -- locales_points_of_interest - icon_name : entry=381
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Warlock Trainers' WHERE `word_id` = 127341; -- locales_points_of_interest - icon_name : entry=367
UPDATE `trans_words` SET `content_loc6`='Silvermoon City, Weapon Master' WHERE `word_id` = 127333; -- locales_points_of_interest - icon_name : entry=359
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Alchemy Trainer' WHERE `word_id` = 127502; -- locales_points_of_interest - icon_name : entry=1445
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Bank' WHERE `word_id` = 127486; -- locales_points_of_interest - icon_name : entry=1424
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Battlemaster' WHERE `word_id` = 127493; -- locales_points_of_interest - icon_name : entry=1436
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Blacksmithing Trainer' WHERE `word_id` = 127503; -- locales_points_of_interest - icon_name : entry=1446
UPDATE `trans_words` SET `content_loc6`='Silvermoon: City Inn' WHERE `word_id` = 127488; -- locales_points_of_interest - icon_name : entry=1429
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Cooking Trainer' WHERE `word_id` = 127504; -- locales_points_of_interest - icon_name : entry=1447
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Druid Trainer' WHERE `word_id` = 127494; -- locales_points_of_interest - icon_name : entry=1437
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Enchanting Trainer' WHERE `word_id` = 127505; -- locales_points_of_interest - icon_name : entry=1448
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Engineering Trainer' WHERE `word_id` = 127506; -- locales_points_of_interest - icon_name : entry=1449
UPDATE `trans_words` SET `content_loc6`='Silvermoon: First Aid Trainer' WHERE `word_id` = 127507; -- locales_points_of_interest - icon_name : entry=1450
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Fishing Trainer' WHERE `word_id` = 127508; -- locales_points_of_interest - icon_name : entry=1451
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Guild House' WHERE `word_id` = 127487; -- locales_points_of_interest - icon_name : entry=1427
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Herbalism Trainer' WHERE `word_id` = 127509; -- locales_points_of_interest - icon_name : entry=1453
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Hunter Trainer' WHERE `word_id` = 127495; -- locales_points_of_interest - icon_name : entry=1438
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Inscription Trainer' WHERE `word_id` = 127479; -- locales_points_of_interest - icon_name : entry=1416
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Jewelcrafting Trainer' WHERE `word_id` = 127511; -- locales_points_of_interest - icon_name : entry=1457
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Leatherworking Trainer' WHERE `word_id` = 127510; -- locales_points_of_interest - icon_name : entry=1456
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Mage Trainer' WHERE `word_id` = 127496; -- locales_points_of_interest - icon_name : entry=1439
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Mailbox' WHERE `word_id` = 127490; -- locales_points_of_interest - icon_name : entry=1432
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Mana Spinning Machine Tools' WHERE `word_id` = 127501; -- locales_points_of_interest - icon_name : entry=1444
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Mining Trainer' WHERE `word_id` = 127512; -- locales_points_of_interest - icon_name : entry=1458
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Paladin Trainer' WHERE `word_id` = 127497; -- locales_points_of_interest - icon_name : entry=1440
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Priest Trainer' WHERE `word_id` = 127498; -- locales_points_of_interest - icon_name : entry=1441
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Rogue Trainer' WHERE `word_id` = 127499; -- locales_points_of_interest - icon_name : entry=1442
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Royal Exchange Auction House' WHERE `word_id` = 127485; -- locales_points_of_interest - icon_name : entry=1423
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Skinning Trainer' WHERE `word_id` = 127513; -- locales_points_of_interest - icon_name : entry=1459
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Stable Master' WHERE `word_id` = 127491; -- locales_points_of_interest - icon_name : entry=1434
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Tailor' WHERE `word_id` = 127514; -- locales_points_of_interest - icon_name : entry=1460
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Warlock Trainer' WHERE `word_id` = 127500; -- locales_points_of_interest - icon_name : entry=1443
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Wayfarer\'s Rest tavern' WHERE `word_id` = 127489; -- locales_points_of_interest - icon_name : entry=1431
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Weapon Master' WHERE `word_id` = 127492; -- locales_points_of_interest - icon_name : entry=1435
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Western Auction House' WHERE `word_id` = 127484; -- locales_points_of_interest - icon_name : entry=1422
UPDATE `trans_words` SET `content_loc6`='Silvermoon: Wind Master' WHERE `word_id` = 127464; -- locales_points_of_interest - icon_name : entry=1400
UPDATE `trans_words` SET `content_loc6`='Stable Master of Orgrimmar' WHERE `word_id` = 127639; -- locales_points_of_interest - icon_name : entry=4902
UPDATE `trans_words` SET `content_loc6`='Stillpine Hold, Leatherworker' WHERE `word_id` = 127297; -- locales_points_of_interest - icon_name : entry=234
UPDATE `trans_words` SET `content_loc6`='Stillpine Hold, Skinner' WHERE `word_id` = 127299; -- locales_points_of_interest - icon_name : entry=236
UPDATE `trans_words` SET `content_loc6`='Stillpine Hold: Leatherworker' WHERE `word_id` = 127460; -- locales_points_of_interest - icon_name : entry=1356
UPDATE `trans_words` SET `content_loc6`='Stillpine Hold: Skinner' WHERE `word_id` = 127462; -- locales_points_of_interest - icon_name : entry=1358
UPDATE `trans_words` SET `content_loc6`='Stonefire Tavern' WHERE `word_id` = 127180; -- locales_points_of_interest - icon_name : entry=1068
UPDATE `trans_words` SET `content_loc6`='Stormwind - Rogue House' WHERE `word_id` = 127176; -- locales_points_of_interest - icon_name : entry=1041
UPDATE `trans_words` SET `content_loc6`='Stormwind Bank' WHERE `word_id` = 127169; -- locales_points_of_interest - icon_name : entry=1021
UPDATE `trans_words` SET `content_loc6`='Stormwind Barber' WHERE `word_id` = 127378; -- locales_points_of_interest - icon_name : entry=1035
UPDATE `trans_words` SET `content_loc6`='Stormwind Barracks' WHERE `word_id` = 127177; -- locales_points_of_interest - icon_name : entry=1044
UPDATE `trans_words` SET `content_loc6`='Stormwind Druid Trainer' WHERE `word_id` = 127641; -- locales_points_of_interest - icon_name : entry=457
UPDATE `trans_words` SET `content_loc6`='Stormwind Gryphon Master' WHERE `word_id` = 127171; -- locales_points_of_interest - icon_name : entry=1027
UPDATE `trans_words` SET `content_loc6`='Stormwind Inscription' WHERE `word_id` = 127377; -- locales_points_of_interest - icon_name : entry=1015
UPDATE `trans_words` SET `content_loc6`='Stormwind Locksmith' WHERE `word_id` = 127250; -- locales_points_of_interest - icon_name : entry=1029
UPDATE `trans_words` SET `content_loc6`='The Deeprun Tram' WHERE `word_id` = 127170; -- locales_points_of_interest - icon_name : entry=1025
UPDATE `trans_words` SET `content_loc6`='The Vault' WHERE `word_id` = 127178; -- locales_points_of_interest - icon_name : entry=1060
UPDATE `trans_words` SET `content_loc6`='Theramore Alchemy' WHERE `word_id` = 127662; -- locales_points_of_interest - icon_name : entry=478
UPDATE `trans_words` SET `content_loc6`='Theramore Archaeology' WHERE `word_id` = 127663; -- locales_points_of_interest - icon_name : entry=479
UPDATE `trans_words` SET `content_loc6`='Theramore Banker' WHERE `word_id` = 127654; -- locales_points_of_interest - icon_name : entry=469
UPDATE `trans_words` SET `content_loc6`='Theramore Blacksmithing' WHERE `word_id` = 127664; -- locales_points_of_interest - icon_name : entry=480
UPDATE `trans_words` SET `content_loc6`='Theramore Cooking' WHERE `word_id` = 127665; -- locales_points_of_interest - icon_name : entry=481
UPDATE `trans_words` SET `content_loc6`='Theramore Enchanting' WHERE `word_id` = 127666; -- locales_points_of_interest - icon_name : entry=482
UPDATE `trans_words` SET `content_loc6`='Theramore Engineering' WHERE `word_id` = 127667; -- locales_points_of_interest - icon_name : entry=483
UPDATE `trans_words` SET `content_loc6`='Theramore First Aid' WHERE `word_id` = 127668; -- locales_points_of_interest - icon_name : entry=484
UPDATE `trans_words` SET `content_loc6`='Theramore Fishing' WHERE `word_id` = 127669; -- locales_points_of_interest - icon_name : entry=485
UPDATE `trans_words` SET `content_loc6`='Theramore Herbalism' WHERE `word_id` = 127670; -- locales_points_of_interest - icon_name : entry=486
UPDATE `trans_words` SET `content_loc6`='Theramore Hunter' WHERE `word_id` = 127655; -- locales_points_of_interest - icon_name : entry=470
UPDATE `trans_words` SET `content_loc6`='Theramore Inscription' WHERE `word_id` = 127671; -- locales_points_of_interest - icon_name : entry=487
UPDATE `trans_words` SET `content_loc6`='Theramore Jewelcrafting' WHERE `word_id` = 127672; -- locales_points_of_interest - icon_name : entry=488
UPDATE `trans_words` SET `content_loc6`='Theramore Leatherworking' WHERE `word_id` = 127673; -- locales_points_of_interest - icon_name : entry=489
UPDATE `trans_words` SET `content_loc6`='Theramore Mining' WHERE `word_id` = 127674; -- locales_points_of_interest - icon_name : entry=490
UPDATE `trans_words` SET `content_loc6`='Theramore Paladin' WHERE `word_id` = 127656; -- locales_points_of_interest - icon_name : entry=472
UPDATE `trans_words` SET `content_loc6`='Theramore Priest' WHERE `word_id` = 127657; -- locales_points_of_interest - icon_name : entry=473
UPDATE `trans_words` SET `content_loc6`='Theramore Riding' WHERE `word_id` = 127675; -- locales_points_of_interest - icon_name : entry=491
UPDATE `trans_words` SET `content_loc6`='Theramore Rogue' WHERE `word_id` = 127658; -- locales_points_of_interest - icon_name : entry=474
UPDATE `trans_words` SET `content_loc6`='Theramore Shaman' WHERE `word_id` = 127659; -- locales_points_of_interest - icon_name : entry=475
UPDATE `trans_words` SET `content_loc6`='Theramore Skinning' WHERE `word_id` = 127676; -- locales_points_of_interest - icon_name : entry=492
UPDATE `trans_words` SET `content_loc6`='Theramore Tailoring' WHERE `word_id` = 127677; -- locales_points_of_interest - icon_name : entry=493
UPDATE `trans_words` SET `content_loc6`='Theramore Warlock' WHERE `word_id` = 127660; -- locales_points_of_interest - icon_name : entry=476
UPDATE `trans_words` SET `content_loc6`='Theramore Warrior' WHERE `word_id` = 127661; -- locales_points_of_interest - icon_name : entry=477
UPDATE `trans_words` SET `content_loc6`='Thunder Bluff Auction house' WHERE `word_id` = 127241; -- locales_points_of_interest - icon_name : entry=1308
UPDATE `trans_words` SET `content_loc6`='Thunder Bluff Inn' WHERE `word_id` = 127243; -- locales_points_of_interest - icon_name : entry=1306
UPDATE `trans_words` SET `content_loc6`='Thunder Bluff Inscription' WHERE `word_id` = 127433; -- locales_points_of_interest - icon_name : entry=1299
UPDATE `trans_words` SET `content_loc6`='Thunder Bluff Mailbox' WHERE `word_id` = 127242; -- locales_points_of_interest - icon_name : entry=1307
UPDATE `trans_words` SET `content_loc6`='Thunder Bluff Zeppelin' WHERE `word_id` = 127302; -- locales_points_of_interest - icon_name : entry=1312
UPDATE `trans_words` SET `content_loc6`='Undercity Bank' WHERE `word_id` = 127236; -- locales_points_of_interest - icon_name : entry=1232
UPDATE `trans_words` SET `content_loc6`='Undercity Barber' WHERE `word_id` = 127434; -- locales_points_of_interest - icon_name : entry=1242
UPDATE `trans_words` SET `content_loc6`='Undercity Bat Handler' WHERE `word_id` = 127235; -- locales_points_of_interest - icon_name : entry=1233
UPDATE `trans_words` SET `content_loc6`='Undercity Blacksmithing Trainer' WHERE `word_id` = 127224; -- locales_points_of_interest - icon_name : entry=1245
UPDATE `trans_words` SET `content_loc6`='Undercity Cooking Trainer' WHERE `word_id` = 127223; -- locales_points_of_interest - icon_name : entry=1247
UPDATE `trans_words` SET `content_loc6`='Undercity Enchanting Trainer' WHERE `word_id` = 127222; -- locales_points_of_interest - icon_name : entry=1248
UPDATE `trans_words` SET `content_loc6`='Undercity Engineering Trainer' WHERE `word_id` = 127221; -- locales_points_of_interest - icon_name : entry=1249
UPDATE `trans_words` SET `content_loc6`='Undercity First Aid Trainer' WHERE `word_id` = 127220; -- locales_points_of_interest - icon_name : entry=1251
UPDATE `trans_words` SET `content_loc6`='Undercity Fishing Trainer' WHERE `word_id` = 127219; -- locales_points_of_interest - icon_name : entry=1252
UPDATE `trans_words` SET `content_loc6`='Undercity Guild Master' WHERE `word_id` = 127233; -- locales_points_of_interest - icon_name : entry=1234
UPDATE `trans_words` SET `content_loc6`='Undercity Herbalism Trainer' WHERE `word_id` = 127218; -- locales_points_of_interest - icon_name : entry=1253
UPDATE `trans_words` SET `content_loc6`='Undercity Inn' WHERE `word_id` = 127232; -- locales_points_of_interest - icon_name : entry=1235
UPDATE `trans_words` SET `content_loc6`='Undercity Inscription' WHERE `word_id` = 127435; -- locales_points_of_interest - icon_name : entry=1256
UPDATE `trans_words` SET `content_loc6`='Undercity Leatherworking Trainer' WHERE `word_id` = 127217; -- locales_points_of_interest - icon_name : entry=1257
UPDATE `trans_words` SET `content_loc6`='Undercity Locksmith' WHERE `word_id` = 127301; -- locales_points_of_interest - icon_name : entry=1260
UPDATE `trans_words` SET `content_loc6`='Undercity Mage Trainers' WHERE `word_id` = 127229; -- locales_points_of_interest - icon_name : entry=1262
UPDATE `trans_words` SET `content_loc6`='Undercity Mailbox' WHERE `word_id` = 127231; -- locales_points_of_interest - icon_name : entry=1236
UPDATE `trans_words` SET `content_loc6`='Undercity Mining Trainer' WHERE `word_id` = 127216; -- locales_points_of_interest - icon_name : entry=1258
UPDATE `trans_words` SET `content_loc6`='Undercity Priest Trainers' WHERE `word_id` = 127228; -- locales_points_of_interest - icon_name : entry=1264
UPDATE `trans_words` SET `content_loc6`='Undercity Rogue Trainers' WHERE `word_id` = 127227; -- locales_points_of_interest - icon_name : entry=1265
UPDATE `trans_words` SET `content_loc6`='Undercity Skinning Trainer' WHERE `word_id` = 127215; -- locales_points_of_interest - icon_name : entry=1259
UPDATE `trans_words` SET `content_loc6`='Undercity Tailoring Trainer' WHERE `word_id` = 127214; -- locales_points_of_interest - icon_name : entry=1261
UPDATE `trans_words` SET `content_loc6`='Undercity Warlock Trainers' WHERE `word_id` = 127226; -- locales_points_of_interest - icon_name : entry=1266
UPDATE `trans_words` SET `content_loc6`='Undercity Warrior Trainers' WHERE `word_id` = 127225; -- locales_points_of_interest - icon_name : entry=1267
UPDATE `trans_words` SET `content_loc6`='Undercity Zeppelin' WHERE `word_id` = 127230; -- locales_points_of_interest - icon_name : entry=1238
UPDATE `trans_words` SET `content_loc6`='Wind Rider Roost' WHERE `word_id` = 127244; -- locales_points_of_interest - icon_name : entry=1304

SET NAMES 'latin1';
