-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc8`='A Tribute to Immortality' WHERE `word_id` = 333627; -- locales_achievement_reward - subject : entry=4079
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:4854' WHERE `word_id` = 333687; -- locales_achievement_reward - subject : entry=4854
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:4855' WHERE `word_id` = 333686; -- locales_achievement_reward - subject : entry=4855
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:4856' WHERE `word_id` = 333685; -- locales_achievement_reward - subject : entry=4856
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5116' WHERE `word_id` = 333645; -- locales_achievement_reward - subject : entry=5116
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5121' WHERE `word_id` = 333646; -- locales_achievement_reward - subject : entry=5121
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5123' WHERE `word_id` = 333643; -- locales_achievement_reward - subject : entry=5123
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5330' WHERE `word_id` = 333657; -- locales_achievement_reward - subject : entry=5330
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5331' WHERE `word_id` = 333680; -- locales_achievement_reward - subject : entry=5331
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5332' WHERE `word_id` = 333658; -- locales_achievement_reward - subject : entry=5332
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5333' WHERE `word_id` = 333675; -- locales_achievement_reward - subject : entry=5333
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5334' WHERE `word_id` = 333659; -- locales_achievement_reward - subject : entry=5334
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5335' WHERE `word_id` = 333671; -- locales_achievement_reward - subject : entry=5335
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5336' WHERE `word_id` = 333673; -- locales_achievement_reward - subject : entry=5336
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5337' WHERE `word_id` = 333672; -- locales_achievement_reward - subject : entry=5337
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5338' WHERE `word_id` = 333682; -- locales_achievement_reward - subject : entry=5338
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5339' WHERE `word_id` = 333674; -- locales_achievement_reward - subject : entry=5339
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5340' WHERE `word_id` = 333681; -- locales_achievement_reward - subject : entry=5340
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5341' WHERE `word_id` = 333676; -- locales_achievement_reward - subject : entry=5341
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5343' WHERE `word_id` = 333656; -- locales_achievement_reward - subject : entry=5343
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5345' WHERE `word_id` = 333663; -- locales_achievement_reward - subject : entry=5345
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5346' WHERE `word_id` = 333668; -- locales_achievement_reward - subject : entry=5346
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5347' WHERE `word_id` = 333661; -- locales_achievement_reward - subject : entry=5347
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5348' WHERE `word_id` = 333662; -- locales_achievement_reward - subject : entry=5348
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5349' WHERE `word_id` = 333667; -- locales_achievement_reward - subject : entry=5349
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5350' WHERE `word_id` = 333660; -- locales_achievement_reward - subject : entry=5350
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5351' WHERE `word_id` = 333684; -- locales_achievement_reward - subject : entry=5351
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5352' WHERE `word_id` = 333677; -- locales_achievement_reward - subject : entry=5352
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5353' WHERE `word_id` = 333683; -- locales_achievement_reward - subject : entry=5353
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5354' WHERE `word_id` = 333678; -- locales_achievement_reward - subject : entry=5354
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5355' WHERE `word_id` = 333669; -- locales_achievement_reward - subject : entry=5355
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5356' WHERE `word_id` = 333670; -- locales_achievement_reward - subject : entry=5356
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5357' WHERE `word_id` = 333666; -- locales_achievement_reward - subject : entry=5357
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5359' WHERE `word_id` = 333679; -- locales_achievement_reward - subject : entry=5359
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5363' WHERE `word_id` = 333664; -- locales_achievement_reward - subject : entry=5363
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5506' WHERE `word_id` = 333665; -- locales_achievement_reward - subject : entry=5506
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5767' WHERE `word_id` = 333655; -- locales_achievement_reward - subject : entry=5767
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5803' WHERE `word_id` = 333644; -- locales_achievement_reward - subject : entry=5803
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5827' WHERE `word_id` = 333648; -- locales_achievement_reward - subject : entry=5827
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:5879' WHERE `word_id` = 333647; -- locales_achievement_reward - subject : entry=5879
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:6116' WHERE `word_id` = 333688; -- locales_achievement_reward - subject : entry=6116
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:6177' WHERE `word_id` = 333689; -- locales_achievement_reward - subject : entry=6177
UPDATE `trans_words` SET `content_loc8`='Alliance War Steed' WHERE `word_id` = 333712; -- locales_achievement_reward - subject : entry=5328
UPDATE `trans_words` SET `content_loc8`='Brutally Dedicated' WHERE `word_id` = 333619; -- locales_achievement_reward - subject : entry=876
UPDATE `trans_words` SET `content_loc8`='Champion,$B$BI have received word of your great deeds from my allies in the Earthen Ring. Many have taken up arms in defense of our troubled world, but your achievements are of particular note.$B$BPlease accept this gift in recognition of your skill and bravery. With heroes like you and your comrades assisting our cause, we may yet prevail.$B$BThrall' WHERE `word_id` = 333695; -- locales_achievement_reward - text : entry=4845
UPDATE `trans_words` SET `content_loc8`='Champion,$B$BI have received word of your great deeds from my allies in the Earthen Ring. Many have taken up arms in defense of our troubled world, but your achievements are of particular note.$B$BYour bravery should not go unrecognized. Please accept this gift on behalf of the Earthen Ring. With heroes like you and your comrades assisting our cause, we may yet prevail.$B$BThrall' WHERE `word_id` = 333706; -- locales_achievement_reward - text : entry=4853
UPDATE `trans_words` SET `content_loc8`='Champion,$B$BWhen the world\'s strongest rose to the rallying call of the Avengers of Hyjal, you stood among the very greatest of them, the best and the bravest who dared all in that maw of fire and hatred.$B$BIt is for this reason that I ask a boon of you:$B$BA clutch of Millagazor\'s eggs has been discovered, tainted by the otherworldly vileness of the Twilight\'s Hammer. Rather than destroying what remains of her brood, it is my hope that champions such as you, through strength of character and force of will, can tame the ill-fated hatchlings, offering them lives as noble steeds and companions rather than doomed monstrosities.$B$BWill you honor my humble request and take this egg, to raise it as your own...?$B$BMalfurion Stormrage' WHERE `word_id` = 333709; -- locales_achievement_reward - text : entry=5828
UPDATE `trans_words` SET `content_loc8`='Congratulations on your conviction to reach the 80th season of adventure. You are undoubtedly dedicated to the cause of ridding Azeroth of the evils which have plagued us.$B$BAnd while the journey thus far has been no minor feat, the true battle lies ahead.$B$BFight on!$B$BRhonin' WHERE `word_id` = 333614; -- locales_achievement_reward - text : entry=13
UPDATE `trans_words` SET `content_loc8`='Glory of the Cataclysm Hero' WHERE `word_id` = 333694; -- locales_achievement_reward - subject : entry=4845
UPDATE `trans_words` SET `content_loc8`='Glory of the Cataclysm Raider' WHERE `word_id` = 333705; -- locales_achievement_reward - subject : entry=4853
UPDATE `trans_words` SET `content_loc8`='Glory of the Firelands Raider' WHERE `word_id` = 333708; -- locales_achievement_reward - subject : entry=5828
UPDATE `trans_words` SET `content_loc8`='Glory of the Hero' WHERE `word_id` = 333564; -- locales_achievement_reward - subject : entry=2136
UPDATE `trans_words` SET `content_loc8`='Greetings from Darnassus' WHERE `word_id` = 333546; -- locales_achievement_reward - subject : entry=1681
UPDATE `trans_words` SET `content_loc8`='Hallowed Be Thy Name' WHERE `word_id` = 336887; -- locales_achievement_reward - subject : entry=1656
UPDATE `trans_words` SET `content_loc8`='Hello again. Friend!$B$BThis mischievous little fellow is driving everyone in the pet store nuts!$B$BI thought you might take him along on some of your adventures... Perhaps he\'ll calm down after he\'s seen a bit of the world.$B$BYou DO wear a helmet, right... ?$B$B--Breanni' WHERE `word_id` = 333704; -- locales_achievement_reward - text : entry=5876
UPDATE `trans_words` SET `content_loc8`='Higher Learning' WHERE `word_id` = 333558; -- locales_achievement_reward - subject : entry=1956
UPDATE `trans_words` SET `content_loc8`='Honorable $N,$B$BFor your deeds upon the Isle of Conquest,$B$Bit is my honor to present you with this$B$Btabard. Wear it proudly.$B$BHigh Commander Halford Wyrmbane' WHERE `word_id` = 333623; -- locales_achievement_reward - text : entry=3857
UPDATE `trans_words` SET `content_loc8`='Honorable $N,$B$BFor your deeds upon the Isle of Conquest,$B$Bit is my honor to present you with this$B$Btabard. Wear it proudly.$B$BOverlord Agmar' WHERE `word_id` = 333622; -- locales_achievement_reward - text : entry=3957
UPDATE `trans_words` SET `content_loc8`='Horde War Wolf' WHERE `word_id` = 333710; -- locales_achievement_reward - subject : entry=5325
UPDATE `trans_words` SET `content_loc8`='How many Alliance heads have fallen into the dust by your hand? How many Victories won, enemies crushed, battefields(sic) taken?$B$BThe eyes of Hellscream have been upon you, and they are pleased. Ride on proudly, for the Horde!$B$B--Warchief Garrosh Hellscream' WHERE `word_id` = 333711; -- locales_achievement_reward - text : entry=5325
UPDATE `trans_words` SET `content_loc8`='I found this locket in the Igneous Depths, near the lava\'s edge. It is not mine, and I know that it does not belong to either of the Arch Druids. Perhaps it belonged to one of the fire druids.$B$BNo matter who its owner, I have no use for it. Please take it as a small token of our appreciation for all you\'ve done for us.' WHERE `word_id` = 333691; -- locales_achievement_reward - text : entry=5859
UPDATE `trans_words` SET `content_loc8`='I\'m Going Nuts!' WHERE `word_id` = 333703; -- locales_achievement_reward - subject : entry=5876
UPDATE `trans_words` SET `content_loc8`='I\'ve heard your stables are nearly as extensive as mine, now. Impressive! Perhaps we can help one another...$B$BI\'ve one too many dragonhawks, and hoped you could give this one a home. Naturally it\'s been trained as a mount and not a hunting pet, and you\'ll find it as loyal and tireless as any other steed I raise.$B$BYours again,$BMei' WHERE `word_id` = 333633; -- locales_achievement_reward - text : entry=2536
UPDATE `trans_words` SET `content_loc8`='Leading the Cavalry' WHERE `word_id` = 333566; -- locales_achievement_reward - subject : entry=2143
UPDATE `trans_words` SET `content_loc8`='Left Behind' WHERE `word_id` = 333690; -- locales_achievement_reward - subject : entry=5859
UPDATE `trans_words` SET `content_loc8`='P.U.G.' WHERE `word_id` = 333624; -- locales_achievement_reward - subject : entry=4478
UPDATE `trans_words` SET `content_loc8`='Quite the Achiever' WHERE `word_id` = 333531; -- locales_achievement_reward - subject : entry=1021
UPDATE `trans_words` SET `content_loc8`='The Coin Master' WHERE `word_id` = 333562; -- locales_achievement_reward - subject : entry=2096
UPDATE `trans_words` SET `content_loc8`='Time and again your skill and bravery have been proven on the field of battle.$B$BYour deeds will not go unrewarded. Ride on proudly, for the Alliance!$B$B--Your King' WHERE `word_id` = 333713; -- locales_achievement_reward - text : entry=5328

SET NAMES 'latin1';
