-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc8`='AAA Cannon' WHERE `word_id` = 127649; -- locales_points_of_interest - icon_name : entry=464
UPDATE `trans_words` SET `content_loc8`='AAA Fortune Teller' WHERE `word_id` = 127653; -- locales_points_of_interest - icon_name : entry=468
UPDATE `trans_words` SET `content_loc8`='AAA Ring Toss' WHERE `word_id` = 127651; -- locales_points_of_interest - icon_name : entry=466
UPDATE `trans_words` SET `content_loc8`='AAA Shooting Gallery' WHERE `word_id` = 127652; -- locales_points_of_interest - icon_name : entry=467
UPDATE `trans_words` SET `content_loc8`='AAA Tonk Arena' WHERE `word_id` = 127648; -- locales_points_of_interest - icon_name : entry=463
UPDATE `trans_words` SET `content_loc8`='AAA Whack-a-Gnoll' WHERE `word_id` = 127650; -- locales_points_of_interest - icon_name : entry=465
UPDATE `trans_words` SET `content_loc8`='Aldor Gem Vendor' WHERE `word_id` = 127324; -- locales_points_of_interest - icon_name : entry=259
UPDATE `trans_words` SET `content_loc8`='Ammen Ford, Fisherwoman' WHERE `word_id` = 127295; -- locales_points_of_interest - icon_name : entry=232
UPDATE `trans_words` SET `content_loc8`='Arena Battlemaster Exodar' WHERE `word_id` = 127376; -- locales_points_of_interest - icon_name : entry=264
UPDATE `trans_words` SET `content_loc8`='Azure Watch, Alchemist' WHERE `word_id` = 127290; -- locales_points_of_interest - icon_name : entry=227
UPDATE `trans_words` SET `content_loc8`='Azure Watch, Engineering Trainer' WHERE `word_id` = 127293; -- locales_points_of_interest - icon_name : entry=230
UPDATE `trans_words` SET `content_loc8`='Azure Watch, First Aid Trainer' WHERE `word_id` = 127294; -- locales_points_of_interest - icon_name : entry=231
UPDATE `trans_words` SET `content_loc8`='Azure Watch, Herbalist' WHERE `word_id` = 127296; -- locales_points_of_interest - icon_name : entry=233
UPDATE `trans_words` SET `content_loc8`='Azure Watch, Hunter Trainer' WHERE `word_id` = 127284; -- locales_points_of_interest - icon_name : entry=221
UPDATE `trans_words` SET `content_loc8`='Azure Watch, Innkeeper' WHERE `word_id` = 127282; -- locales_points_of_interest - icon_name : entry=219
UPDATE `trans_words` SET `content_loc8`='Azure Watch, Mage Trainer' WHERE `word_id` = 127285; -- locales_points_of_interest - icon_name : entry=222
UPDATE `trans_words` SET `content_loc8`='Azure Watch, Mining Trainer' WHERE `word_id` = 127298; -- locales_points_of_interest - icon_name : entry=235
UPDATE `trans_words` SET `content_loc8`='Azure Watch, Paladin Trainer' WHERE `word_id` = 127286; -- locales_points_of_interest - icon_name : entry=223
UPDATE `trans_words` SET `content_loc8`='Azure Watch, Priest Trainer' WHERE `word_id` = 127287; -- locales_points_of_interest - icon_name : entry=224
UPDATE `trans_words` SET `content_loc8`='Azure Watch, Shaman Trainer' WHERE `word_id` = 127288; -- locales_points_of_interest - icon_name : entry=225
UPDATE `trans_words` SET `content_loc8`='Azure Watch, Stable Master' WHERE `word_id` = 127283; -- locales_points_of_interest - icon_name : entry=220
UPDATE `trans_words` SET `content_loc8`='Azure Watch, Warrior Trainer' WHERE `word_id` = 127289; -- locales_points_of_interest - icon_name : entry=226
UPDATE `trans_words` SET `content_loc8`='Dalaran Alchemy Trainer' WHERE `word_id` = 127405; -- locales_points_of_interest - icon_name : entry=151
UPDATE `trans_words` SET `content_loc8`='Dalaran Alliance Inn' WHERE `word_id` = 127391; -- locales_points_of_interest - icon_name : entry=137
UPDATE `trans_words` SET `content_loc8`='Dalaran Antonidas Memorial' WHERE `word_id` = 127398; -- locales_points_of_interest - icon_name : entry=144
UPDATE `trans_words` SET `content_loc8`='Dalaran Archaeology Trainer' WHERE `word_id` = 127642; -- locales_points_of_interest - icon_name : entry=454
UPDATE `trans_words` SET `content_loc8`='Dalaran Barber' WHERE `word_id` = 127388; -- locales_points_of_interest - icon_name : entry=133
UPDATE `trans_words` SET `content_loc8`='Dalaran Blacksmithing Trainer' WHERE `word_id` = 127406; -- locales_points_of_interest - icon_name : entry=152
UPDATE `trans_words` SET `content_loc8`='Dalaran Cemetary' WHERE `word_id` = 127401; -- locales_points_of_interest - icon_name : entry=147
UPDATE `trans_words` SET `content_loc8`='Dalaran Cloth Armor & Clothing' WHERE `word_id` = 127417; -- locales_points_of_interest - icon_name : entry=163
UPDATE `trans_words` SET `content_loc8`='Dalaran Enchanting Trainer' WHERE `word_id` = 127407; -- locales_points_of_interest - icon_name : entry=153
UPDATE `trans_words` SET `content_loc8`='Dalaran Engineering Trainer' WHERE `word_id` = 127408; -- locales_points_of_interest - icon_name : entry=154
UPDATE `trans_words` SET `content_loc8`='Dalaran Eventide' WHERE `word_id` = 127400; -- locales_points_of_interest - icon_name : entry=146
UPDATE `trans_words` SET `content_loc8`='Dalaran First Aid Trainer' WHERE `word_id` = 127409; -- locales_points_of_interest - icon_name : entry=155
UPDATE `trans_words` SET `content_loc8`='Dalaran Fishing Fountain' WHERE `word_id` = 127410; -- locales_points_of_interest - icon_name : entry=156
UPDATE `trans_words` SET `content_loc8`='Dalaran Flight Master' WHERE `word_id` = 127389; -- locales_points_of_interest - icon_name : entry=134
UPDATE `trans_words` SET `content_loc8`='Dalaran Flowers' WHERE `word_id` = 127418; -- locales_points_of_interest - icon_name : entry=164
UPDATE `trans_words` SET `content_loc8`='Dalaran Fruit Vendor' WHERE `word_id` = 127419; -- locales_points_of_interest - icon_name : entry=165
UPDATE `trans_words` SET `content_loc8`='Dalaran General & Trade Store' WHERE `word_id` = 127420; -- locales_points_of_interest - icon_name : entry=166
UPDATE `trans_words` SET `content_loc8`='Dalaran Herbalism Trainer' WHERE `word_id` = 127411; -- locales_points_of_interest - icon_name : entry=157
UPDATE `trans_words` SET `content_loc8`='Dalaran Horde Inn' WHERE `word_id` = 127392; -- locales_points_of_interest - icon_name : entry=138
UPDATE `trans_words` SET `content_loc8`='Dalaran Inn' WHERE `word_id` = 127390; -- locales_points_of_interest - icon_name : entry=136
UPDATE `trans_words` SET `content_loc8`='Dalaran Inscription Trainer' WHERE `word_id` = 127402; -- locales_points_of_interest - icon_name : entry=148
UPDATE `trans_words` SET `content_loc8`='Dalaran Jewelcrafting Trainer' WHERE `word_id` = 127412; -- locales_points_of_interest - icon_name : entry=158
UPDATE `trans_words` SET `content_loc8`='Dalaran Krasus\' Landing' WHERE `word_id` = 127394; -- locales_points_of_interest - icon_name : entry=140
UPDATE `trans_words` SET `content_loc8`='Dalaran Leather & Mail Armor' WHERE `word_id` = 127436; -- locales_points_of_interest - icon_name : entry=238
UPDATE `trans_words` SET `content_loc8`='Dalaran Leatherworking Trainer' WHERE `word_id` = 127413; -- locales_points_of_interest - icon_name : entry=159
UPDATE `trans_words` SET `content_loc8`='Dalaran Locksmith' WHERE `word_id` = 127393; -- locales_points_of_interest - icon_name : entry=139
UPDATE `trans_words` SET `content_loc8`='Dalaran Mage Trainer' WHERE `word_id` = 127404; -- locales_points_of_interest - icon_name : entry=150
UPDATE `trans_words` SET `content_loc8`='Dalaran Melee Weapons' WHERE `word_id` = 127426; -- locales_points_of_interest - icon_name : entry=172
UPDATE `trans_words` SET `content_loc8`='Dalaran Mining Trainer' WHERE `word_id` = 127414; -- locales_points_of_interest - icon_name : entry=160
UPDATE `trans_words` SET `content_loc8`='Dalaran Northern Bank' WHERE `word_id` = 127386; -- locales_points_of_interest - icon_name : entry=131
UPDATE `trans_words` SET `content_loc8`='Dalaran Pet Store' WHERE `word_id` = 127421; -- locales_points_of_interest - icon_name : entry=167
UPDATE `trans_words` SET `content_loc8`='Dalaran Pie, Pastry & Cake' WHERE `word_id` = 127422; -- locales_points_of_interest - icon_name : entry=168
UPDATE `trans_words` SET `content_loc8`='Dalaran Plate Armor & Shields' WHERE `word_id` = 127437; -- locales_points_of_interest - icon_name : entry=239
UPDATE `trans_words` SET `content_loc8`='Dalaran Ranged Weapons' WHERE `word_id` = 127427; -- locales_points_of_interest - icon_name : entry=173
UPDATE `trans_words` SET `content_loc8`='Dalaran Reagents' WHERE `word_id` = 127423; -- locales_points_of_interest - icon_name : entry=169
UPDATE `trans_words` SET `content_loc8`='Dalaran Runeweaver Square' WHERE `word_id` = 127399; -- locales_points_of_interest - icon_name : entry=145
UPDATE `trans_words` SET `content_loc8`='Dalaran Sewer Arena' WHERE `word_id` = 127439; -- locales_points_of_interest - icon_name : entry=270
UPDATE `trans_words` SET `content_loc8`='Dalaran Sewer Bank' WHERE `word_id` = 127440; -- locales_points_of_interest - icon_name : entry=271
UPDATE `trans_words` SET `content_loc8`='Dalaran Sewer Inn' WHERE `word_id` = 127441; -- locales_points_of_interest - icon_name : entry=272
UPDATE `trans_words` SET `content_loc8`='Dalaran Sewer Tunnel' WHERE `word_id` = 127442; -- locales_points_of_interest - icon_name : entry=273
UPDATE `trans_words` SET `content_loc8`='Dalaran Sewer Vendors' WHERE `word_id` = 127443; -- locales_points_of_interest - icon_name : entry=274
UPDATE `trans_words` SET `content_loc8`='Dalaran Silver Enclave' WHERE `word_id` = 127384; -- locales_points_of_interest - icon_name : entry=129
UPDATE `trans_words` SET `content_loc8`='Dalaran Skinning Trainer' WHERE `word_id` = 127415; -- locales_points_of_interest - icon_name : entry=161
UPDATE `trans_words` SET `content_loc8`='Dalaran Southern Bank' WHERE `word_id` = 127387; -- locales_points_of_interest - icon_name : entry=132
UPDATE `trans_words` SET `content_loc8`='Dalaran Stable Master' WHERE `word_id` = 127403; -- locales_points_of_interest - icon_name : entry=149
UPDATE `trans_words` SET `content_loc8`='Dalaran Staves & Wands' WHERE `word_id` = 127428; -- locales_points_of_interest - icon_name : entry=174
UPDATE `trans_words` SET `content_loc8`='Dalaran Sunreaver\'s Sanctuary' WHERE `word_id` = 127385; -- locales_points_of_interest - icon_name : entry=130
UPDATE `trans_words` SET `content_loc8`='Dalaran Tailoring Trainer' WHERE `word_id` = 127416; -- locales_points_of_interest - icon_name : entry=162
UPDATE `trans_words` SET `content_loc8`='Dalaran Toy Store' WHERE `word_id` = 127424; -- locales_points_of_interest - icon_name : entry=170
UPDATE `trans_words` SET `content_loc8`='Dalaran Trade District' WHERE `word_id` = 127397; -- locales_points_of_interest - icon_name : entry=143
UPDATE `trans_words` SET `content_loc8`='Dalaran Trinkets' WHERE `word_id` = 127425; -- locales_points_of_interest - icon_name : entry=171
UPDATE `trans_words` SET `content_loc8`='Dalaran Violet Citadel' WHERE `word_id` = 127395; -- locales_points_of_interest - icon_name : entry=141
UPDATE `trans_words` SET `content_loc8`='Dalaran Violet Hold' WHERE `word_id` = 127396; -- locales_points_of_interest - icon_name : entry=142
UPDATE `trans_words` SET `content_loc8`='Dalaran Wine & Cheese' WHERE `word_id` = 127429; -- locales_points_of_interest - icon_name : entry=175
UPDATE `trans_words` SET `content_loc8`='Darkmoon Game Tokens' WHERE `word_id` = 127646; -- locales_points_of_interest - icon_name : entry=460
UPDATE `trans_words` SET `content_loc8`='Darnassus Blacksmithing' WHERE `word_id` = 127647; -- locales_points_of_interest - icon_name : entry=462
UPDATE `trans_words` SET `content_loc8`='Darnassus Hippogryph Master' WHERE `word_id` = 127189; -- locales_points_of_interest - icon_name : entry=91
UPDATE `trans_words` SET `content_loc8`='Darnassus Mage Trainer' WHERE `word_id` = 127373; -- locales_points_of_interest - icon_name : entry=265
UPDATE `trans_words` SET `content_loc8`='Darnassus Paladin Trainer' WHERE `word_id` = 127374; -- locales_points_of_interest - icon_name : entry=266
UPDATE `trans_words` SET `content_loc8`='Embassy of the Horde' WHERE `word_id` = 127636; -- locales_points_of_interest - icon_name : entry=1903
UPDATE `trans_words` SET `content_loc8`='Eversong Woods, Leatherworker' WHERE `word_id` = 127371; -- locales_points_of_interest - icon_name : entry=398
UPDATE `trans_words` SET `content_loc8`='Eversong Woods, Skinner' WHERE `word_id` = 127372; -- locales_points_of_interest - icon_name : entry=399
UPDATE `trans_words` SET `content_loc8`='Exodar Inscription' WHERE `word_id` = 127432; -- locales_points_of_interest - icon_name : entry=212
UPDATE `trans_words` SET `content_loc8`='Exodar, Alchemist Trainers' WHERE `word_id` = 127269; -- locales_points_of_interest - icon_name : entry=205
UPDATE `trans_words` SET `content_loc8`='Exodar, Auctioneer' WHERE `word_id` = 127254; -- locales_points_of_interest - icon_name : entry=190
UPDATE `trans_words` SET `content_loc8`='Exodar, bank' WHERE `word_id` = 127255; -- locales_points_of_interest - icon_name : entry=191
UPDATE `trans_words` SET `content_loc8`='Exodar, Battlemasters' WHERE `word_id` = 127375; -- locales_points_of_interest - icon_name : entry=263
UPDATE `trans_words` SET `content_loc8`='Exodar, Blacksmithing Trainers' WHERE `word_id` = 127270; -- locales_points_of_interest - icon_name : entry=206
UPDATE `trans_words` SET `content_loc8`='Exodar, Cook' WHERE `word_id` = 127281; -- locales_points_of_interest - icon_name : entry=218
UPDATE `trans_words` SET `content_loc8`='Exodar, Druid Trainer' WHERE `word_id` = 127262; -- locales_points_of_interest - icon_name : entry=198
UPDATE `trans_words` SET `content_loc8`='Exodar, Enchanters' WHERE `word_id` = 127271; -- locales_points_of_interest - icon_name : entry=207
UPDATE `trans_words` SET `content_loc8`='Exodar, Engineering' WHERE `word_id` = 127272; -- locales_points_of_interest - icon_name : entry=208
UPDATE `trans_words` SET `content_loc8`='Exodar, First Aid Trainer' WHERE `word_id` = 127273; -- locales_points_of_interest - icon_name : entry=209
UPDATE `trans_words` SET `content_loc8`='Exodar, Fishing Trainer' WHERE `word_id` = 127274; -- locales_points_of_interest - icon_name : entry=210
UPDATE `trans_words` SET `content_loc8`='Exodar, Guild Master' WHERE `word_id` = 127257; -- locales_points_of_interest - icon_name : entry=193
UPDATE `trans_words` SET `content_loc8`='Exodar, Herbalist Trainer' WHERE `word_id` = 127275; -- locales_points_of_interest - icon_name : entry=211
UPDATE `trans_words` SET `content_loc8`='Exodar, Hippogryph Master' WHERE `word_id` = 127256; -- locales_points_of_interest - icon_name : entry=192
UPDATE `trans_words` SET `content_loc8`='Exodar, Hunter Trainers' WHERE `word_id` = 127263; -- locales_points_of_interest - icon_name : entry=199
UPDATE `trans_words` SET `content_loc8`='Exodar, Inn' WHERE `word_id` = 127258; -- locales_points_of_interest - icon_name : entry=194
UPDATE `trans_words` SET `content_loc8`='Exodar, Jewelcrafters' WHERE `word_id` = 127276; -- locales_points_of_interest - icon_name : entry=213
UPDATE `trans_words` SET `content_loc8`='Exodar, Leatherworking' WHERE `word_id` = 127277; -- locales_points_of_interest - icon_name : entry=214
UPDATE `trans_words` SET `content_loc8`='Exodar, Mage Trainers' WHERE `word_id` = 127264; -- locales_points_of_interest - icon_name : entry=200
UPDATE `trans_words` SET `content_loc8`='Exodar, Mailbox' WHERE `word_id` = 127259; -- locales_points_of_interest - icon_name : entry=195
UPDATE `trans_words` SET `content_loc8`='Exodar, Mining Trainers' WHERE `word_id` = 127278; -- locales_points_of_interest - icon_name : entry=215
UPDATE `trans_words` SET `content_loc8`='Exodar, Paladin Trainers' WHERE `word_id` = 127265; -- locales_points_of_interest - icon_name : entry=201
UPDATE `trans_words` SET `content_loc8`='Exodar, Priest Trainers' WHERE `word_id` = 127266; -- locales_points_of_interest - icon_name : entry=202
UPDATE `trans_words` SET `content_loc8`='Exodar, Shaman Trainer' WHERE `word_id` = 127267; -- locales_points_of_interest - icon_name : entry=203
UPDATE `trans_words` SET `content_loc8`='Exodar, Skinning Trainer' WHERE `word_id` = 127279; -- locales_points_of_interest - icon_name : entry=216
UPDATE `trans_words` SET `content_loc8`='Exodar, Stable Master' WHERE `word_id` = 127260; -- locales_points_of_interest - icon_name : entry=196
UPDATE `trans_words` SET `content_loc8`='Exodar, Tailors' WHERE `word_id` = 127280; -- locales_points_of_interest - icon_name : entry=217
UPDATE `trans_words` SET `content_loc8`='Exodar, Warrior Trainers' WHERE `word_id` = 127268; -- locales_points_of_interest - icon_name : entry=204
UPDATE `trans_words` SET `content_loc8`='Exodar, Weapon Master' WHERE `word_id` = 127261; -- locales_points_of_interest - icon_name : entry=197
UPDATE `trans_words` SET `content_loc8`='Falconwing Square, Cook' WHERE `word_id` = 127366; -- locales_points_of_interest - icon_name : entry=393
UPDATE `trans_words` SET `content_loc8`='Falconwing Square, First Aid Trainer' WHERE `word_id` = 127368; -- locales_points_of_interest - icon_name : entry=395
UPDATE `trans_words` SET `content_loc8`='Falconwing Square, Hunter Trainer' WHERE `word_id` = 127358; -- locales_points_of_interest - icon_name : entry=385
UPDATE `trans_words` SET `content_loc8`='Falconwing Square, Innkeeper' WHERE `word_id` = 127356; -- locales_points_of_interest - icon_name : entry=383
UPDATE `trans_words` SET `content_loc8`='Falconwing Square, Jewelcrafter' WHERE `word_id` = 127370; -- locales_points_of_interest - icon_name : entry=397
UPDATE `trans_words` SET `content_loc8`='Falconwing Square, Mage Trainer' WHERE `word_id` = 127359; -- locales_points_of_interest - icon_name : entry=386
UPDATE `trans_words` SET `content_loc8`='Falconwing Square, Priest Trainer' WHERE `word_id` = 127361; -- locales_points_of_interest - icon_name : entry=388
UPDATE `trans_words` SET `content_loc8`='Falconwing Square, Rogue Trainer' WHERE `word_id` = 127362; -- locales_points_of_interest - icon_name : entry=389
UPDATE `trans_words` SET `content_loc8`='Falconwing Square, Stable Master' WHERE `word_id` = 127357; -- locales_points_of_interest - icon_name : entry=384
UPDATE `trans_words` SET `content_loc8`='Falconwing Square, Warlock Trainer' WHERE `word_id` = 127363; -- locales_points_of_interest - icon_name : entry=390
UPDATE `trans_words` SET `content_loc8`='Farstrider Retreat, Blacksmith' WHERE `word_id` = 127365; -- locales_points_of_interest - icon_name : entry=392
UPDATE `trans_words` SET `content_loc8`='Flight Master of Orgrimmar' WHERE `word_id` = 127635; -- locales_points_of_interest - icon_name : entry=1902
UPDATE `trans_words` SET `content_loc8`='Ironforge Archaeology' WHERE `word_id` = 127644; -- locales_points_of_interest - icon_name : entry=456
UPDATE `trans_words` SET `content_loc8`='Ironforge Druid Trainer' WHERE `word_id` = 127643; -- locales_points_of_interest - icon_name : entry=455
UPDATE `trans_words` SET `content_loc8`='Odesyus\' Landing, Blacksmith' WHERE `word_id` = 127291; -- locales_points_of_interest - icon_name : entry=228
UPDATE `trans_words` SET `content_loc8`='Odesyus\' Landing, Cook' WHERE `word_id` = 127292; -- locales_points_of_interest - icon_name : entry=229
UPDATE `trans_words` SET `content_loc8`='Odesyus\' Landing, Tailor' WHERE `word_id` = 127300; -- locales_points_of_interest - icon_name : entry=237
UPDATE `trans_words` SET `content_loc8`='Orgrimmar Battlemasters' WHERE `word_id` = 127645; -- locales_points_of_interest - icon_name : entry=459
UPDATE `trans_words` SET `content_loc8`='Orgrimmar Ethereals' WHERE `word_id` = 127640; -- locales_points_of_interest - icon_name : entry=458
UPDATE `trans_words` SET `content_loc8`='Orgrimmar: Portals' WHERE `word_id` = 127637; -- locales_points_of_interest - icon_name : entry=12245
UPDATE `trans_words` SET `content_loc8`='Orgrimmar: The auction house' WHERE `word_id` = 127633; -- locales_points_of_interest - icon_name : entry=12628
UPDATE `trans_words` SET `content_loc8`='Orgrimmar:' WHERE `word_id` = 127634; -- locales_points_of_interest - icon_name : entry=1912
UPDATE `trans_words` SET `content_loc8`='Saltheril\'s Haven, Alchemist' WHERE `word_id` = 127364; -- locales_points_of_interest - icon_name : entry=391
UPDATE `trans_words` SET `content_loc8`='Saltheril\'s Haven, Enchanter' WHERE `word_id` = 127367; -- locales_points_of_interest - icon_name : entry=394
UPDATE `trans_words` SET `content_loc8`='Saltheril\'s Haven, Herbalist' WHERE `word_id` = 127369; -- locales_points_of_interest - icon_name : entry=396
UPDATE `trans_words` SET `content_loc8`='Saltheril\'s Haven, Tailor' WHERE `word_id` = 127247; -- locales_points_of_interest - icon_name : entry=400
UPDATE `trans_words` SET `content_loc8`='Scryer Gem Vendor' WHERE `word_id` = 127325; -- locales_points_of_interest - icon_name : entry=258
UPDATE `trans_words` SET `content_loc8`='Shattrath Alchemist' WHERE `word_id` = 127305; -- locales_points_of_interest - icon_name : entry=248
UPDATE `trans_words` SET `content_loc8`='Shattrath Alchemy Lab' WHERE `word_id` = 127314; -- locales_points_of_interest - icon_name : entry=257
UPDATE `trans_words` SET `content_loc8`='Shattrath Arena Battlemasters' WHERE `word_id` = 127323; -- locales_points_of_interest - icon_name : entry=262
UPDATE `trans_words` SET `content_loc8`='Shattrath Armor/Weapon Crafter' WHERE `word_id` = 127306; -- locales_points_of_interest - icon_name : entry=249
UPDATE `trans_words` SET `content_loc8`='Shattrath Bank Aldor' WHERE `word_id` = 127315; -- locales_points_of_interest - icon_name : entry=260
UPDATE `trans_words` SET `content_loc8`='Shattrath Bank Scryer' WHERE `word_id` = 127316; -- locales_points_of_interest - icon_name : entry=241
UPDATE `trans_words` SET `content_loc8`='Shattrath Battlemasters Alliance' WHERE `word_id` = 127321; -- locales_points_of_interest - icon_name : entry=246
UPDATE `trans_words` SET `content_loc8`='Shattrath Battlemasters Horde' WHERE `word_id` = 127322; -- locales_points_of_interest - icon_name : entry=247
UPDATE `trans_words` SET `content_loc8`='Shattrath Cantina' WHERE `word_id` = 127303; -- locales_points_of_interest - icon_name : entry=240
UPDATE `trans_words` SET `content_loc8`='Shattrath Cook' WHERE `word_id` = 127307; -- locales_points_of_interest - icon_name : entry=250
UPDATE `trans_words` SET `content_loc8`='Shattrath Enchanters' WHERE `word_id` = 127308; -- locales_points_of_interest - icon_name : entry=251
UPDATE `trans_words` SET `content_loc8`='Shattrath First Aid' WHERE `word_id` = 127309; -- locales_points_of_interest - icon_name : entry=252
UPDATE `trans_words` SET `content_loc8`='Shattrath Inn Aldor' WHERE `word_id` = 127317; -- locales_points_of_interest - icon_name : entry=261
UPDATE `trans_words` SET `content_loc8`='Shattrath Inn Scryer' WHERE `word_id` = 127318; -- locales_points_of_interest - icon_name : entry=242
UPDATE `trans_words` SET `content_loc8`='Shattrath Jewelcrafter' WHERE `word_id` = 127310; -- locales_points_of_interest - icon_name : entry=253
UPDATE `trans_words` SET `content_loc8`='Shattrath Leatherworker' WHERE `word_id` = 127311; -- locales_points_of_interest - icon_name : entry=254
UPDATE `trans_words` SET `content_loc8`='Shattrath Mana Loom' WHERE `word_id` = 127313; -- locales_points_of_interest - icon_name : entry=256
UPDATE `trans_words` SET `content_loc8`='Shattrath Skinner' WHERE `word_id` = 127312; -- locales_points_of_interest - icon_name : entry=255
UPDATE `trans_words` SET `content_loc8`='Shattrath Stable Aldor' WHERE `word_id` = 127319; -- locales_points_of_interest - icon_name : entry=244
UPDATE `trans_words` SET `content_loc8`='Shattrath Stable Scryer' WHERE `word_id` = 127320; -- locales_points_of_interest - icon_name : entry=245
UPDATE `trans_words` SET `content_loc8`='Shattrath Taxi' WHERE `word_id` = 127304; -- locales_points_of_interest - icon_name : entry=243
UPDATE `trans_words` SET `content_loc8`='Silvermoon City Inscription' WHERE `word_id` = 127438; -- locales_points_of_interest - icon_name : entry=376
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Alchemy' WHERE `word_id` = 127342; -- locales_points_of_interest - icon_name : entry=368
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Auction House' WHERE `word_id` = 127326; -- locales_points_of_interest - icon_name : entry=349
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Bank' WHERE `word_id` = 127327; -- locales_points_of_interest - icon_name : entry=351
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Battlemasters' WHERE `word_id` = 127334; -- locales_points_of_interest - icon_name : entry=360
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Blacksmithing' WHERE `word_id` = 127343; -- locales_points_of_interest - icon_name : entry=369
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Cooking' WHERE `word_id` = 127344; -- locales_points_of_interest - icon_name : entry=370
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Druid Trainer' WHERE `word_id` = 127335; -- locales_points_of_interest - icon_name : entry=361
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Enchanting' WHERE `word_id` = 127345; -- locales_points_of_interest - icon_name : entry=371
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Engineering' WHERE `word_id` = 127346; -- locales_points_of_interest - icon_name : entry=372
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, First Aid' WHERE `word_id` = 127347; -- locales_points_of_interest - icon_name : entry=373
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Fishing' WHERE `word_id` = 127348; -- locales_points_of_interest - icon_name : entry=374
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Flight Master' WHERE `word_id` = 127328; -- locales_points_of_interest - icon_name : entry=353
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Guild House' WHERE `word_id` = 127329; -- locales_points_of_interest - icon_name : entry=354
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Herbalism' WHERE `word_id` = 127349; -- locales_points_of_interest - icon_name : entry=375
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Hunter Trainer' WHERE `word_id` = 127336; -- locales_points_of_interest - icon_name : entry=362
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Inn' WHERE `word_id` = 127330; -- locales_points_of_interest - icon_name : entry=355
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Jewelcrafting' WHERE `word_id` = 127350; -- locales_points_of_interest - icon_name : entry=377
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Leatherworking' WHERE `word_id` = 127351; -- locales_points_of_interest - icon_name : entry=378
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Mage Trainer' WHERE `word_id` = 127337; -- locales_points_of_interest - icon_name : entry=363
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Mailbox' WHERE `word_id` = 127331; -- locales_points_of_interest - icon_name : entry=357
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Mana Loom' WHERE `word_id` = 127355; -- locales_points_of_interest - icon_name : entry=382
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Mining' WHERE `word_id` = 127352; -- locales_points_of_interest - icon_name : entry=379
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Paladin Trainer' WHERE `word_id` = 127338; -- locales_points_of_interest - icon_name : entry=364
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Priest Trainer' WHERE `word_id` = 127339; -- locales_points_of_interest - icon_name : entry=365
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Rogue Trainer' WHERE `word_id` = 127340; -- locales_points_of_interest - icon_name : entry=366
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Skinning' WHERE `word_id` = 127353; -- locales_points_of_interest - icon_name : entry=380
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Stable Master' WHERE `word_id` = 127332; -- locales_points_of_interest - icon_name : entry=358
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Tailoring' WHERE `word_id` = 127354; -- locales_points_of_interest - icon_name : entry=381
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Warlock Trainers' WHERE `word_id` = 127341; -- locales_points_of_interest - icon_name : entry=367
UPDATE `trans_words` SET `content_loc8`='Silvermoon City, Weapon Master' WHERE `word_id` = 127333; -- locales_points_of_interest - icon_name : entry=359
UPDATE `trans_words` SET `content_loc8`='Stable Master of Orgrimmar' WHERE `word_id` = 127639; -- locales_points_of_interest - icon_name : entry=4902
UPDATE `trans_words` SET `content_loc8`='Stillpine Hold, Leatherworker' WHERE `word_id` = 127297; -- locales_points_of_interest - icon_name : entry=234
UPDATE `trans_words` SET `content_loc8`='Stillpine Hold, Skinner' WHERE `word_id` = 127299; -- locales_points_of_interest - icon_name : entry=236
UPDATE `trans_words` SET `content_loc8`='Stormwind Druid Trainer' WHERE `word_id` = 127641; -- locales_points_of_interest - icon_name : entry=457
UPDATE `trans_words` SET `content_loc8`='Theramore Alchemy' WHERE `word_id` = 127662; -- locales_points_of_interest - icon_name : entry=478
UPDATE `trans_words` SET `content_loc8`='Theramore Archaeology' WHERE `word_id` = 127663; -- locales_points_of_interest - icon_name : entry=479
UPDATE `trans_words` SET `content_loc8`='Theramore Banker' WHERE `word_id` = 127654; -- locales_points_of_interest - icon_name : entry=469
UPDATE `trans_words` SET `content_loc8`='Theramore Blacksmithing' WHERE `word_id` = 127664; -- locales_points_of_interest - icon_name : entry=480
UPDATE `trans_words` SET `content_loc8`='Theramore Cooking' WHERE `word_id` = 127665; -- locales_points_of_interest - icon_name : entry=481
UPDATE `trans_words` SET `content_loc8`='Theramore Enchanting' WHERE `word_id` = 127666; -- locales_points_of_interest - icon_name : entry=482
UPDATE `trans_words` SET `content_loc8`='Theramore Engineering' WHERE `word_id` = 127667; -- locales_points_of_interest - icon_name : entry=483
UPDATE `trans_words` SET `content_loc8`='Theramore First Aid' WHERE `word_id` = 127668; -- locales_points_of_interest - icon_name : entry=484
UPDATE `trans_words` SET `content_loc8`='Theramore Fishing' WHERE `word_id` = 127669; -- locales_points_of_interest - icon_name : entry=485
UPDATE `trans_words` SET `content_loc8`='Theramore Herbalism' WHERE `word_id` = 127670; -- locales_points_of_interest - icon_name : entry=486
UPDATE `trans_words` SET `content_loc8`='Theramore Hunter' WHERE `word_id` = 127655; -- locales_points_of_interest - icon_name : entry=470
UPDATE `trans_words` SET `content_loc8`='Theramore Inscription' WHERE `word_id` = 127671; -- locales_points_of_interest - icon_name : entry=487
UPDATE `trans_words` SET `content_loc8`='Theramore Jewelcrafting' WHERE `word_id` = 127672; -- locales_points_of_interest - icon_name : entry=488
UPDATE `trans_words` SET `content_loc8`='Theramore Leatherworking' WHERE `word_id` = 127673; -- locales_points_of_interest - icon_name : entry=489
UPDATE `trans_words` SET `content_loc8`='Theramore Mining' WHERE `word_id` = 127674; -- locales_points_of_interest - icon_name : entry=490
UPDATE `trans_words` SET `content_loc8`='Theramore Paladin' WHERE `word_id` = 127656; -- locales_points_of_interest - icon_name : entry=472
UPDATE `trans_words` SET `content_loc8`='Theramore Priest' WHERE `word_id` = 127657; -- locales_points_of_interest - icon_name : entry=473
UPDATE `trans_words` SET `content_loc8`='Theramore Riding' WHERE `word_id` = 127675; -- locales_points_of_interest - icon_name : entry=491
UPDATE `trans_words` SET `content_loc8`='Theramore Rogue' WHERE `word_id` = 127658; -- locales_points_of_interest - icon_name : entry=474
UPDATE `trans_words` SET `content_loc8`='Theramore Shaman' WHERE `word_id` = 127659; -- locales_points_of_interest - icon_name : entry=475
UPDATE `trans_words` SET `content_loc8`='Theramore Skinning' WHERE `word_id` = 127676; -- locales_points_of_interest - icon_name : entry=492
UPDATE `trans_words` SET `content_loc8`='Theramore Tailoring' WHERE `word_id` = 127677; -- locales_points_of_interest - icon_name : entry=493
UPDATE `trans_words` SET `content_loc8`='Theramore Warlock' WHERE `word_id` = 127660; -- locales_points_of_interest - icon_name : entry=476
UPDATE `trans_words` SET `content_loc8`='Theramore Warrior' WHERE `word_id` = 127661; -- locales_points_of_interest - icon_name : entry=477

SET NAMES 'latin1';
