-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc8`='[PH] Get E.C.A.C.' WHERE `word_id`=128451; -- locales_gossip_menu_option - option_text : menu_id=524-id=0
UPDATE `trans_words` SET `content_loc8`='[PH] Get Thieves\' Tools' WHERE `word_id`=128154; -- locales_gossip_menu_option - option_text : menu_id=524-id=1
UPDATE `trans_words` SET `content_loc8`='[PH] I want to deliver prisoner.' WHERE `word_id`=129166; -- locales_gossip_menu_option - option_text : menu_id=9184-id=0
UPDATE `trans_words` SET `content_loc8`='[PH] Learn Ultrasafe Transporter.' WHERE `word_id`=128976; -- locales_gossip_menu_option - option_text : menu_id=8306-id=0
UPDATE `trans_words` SET `content_loc8`='Arcanist Tubalin said you might be able to lend me a certain tabard.' WHERE `word_id`=129620; -- locales_gossip_menu_option - option_text : menu_id=10854-id=0
UPDATE `trans_words` SET `content_loc8`='Bring me back to life' WHERE `word_id`=129168; -- locales_gossip_menu_option - option_text : menu_id=0-id=4
UPDATE `trans_words` SET `content_loc8`='Can you tell me about this shard?' WHERE `word_id`=127827; -- locales_gossip_menu_option - option_text : menu_id=21-id=1
UPDATE `trans_words` SET `content_loc8`='Do you know where I can find Half Pendant of Aquatic Agility?' WHERE `word_id`=127921; -- locales_gossip_menu_option - option_text : menu_id=4041-id=1
UPDATE `trans_words` SET `content_loc8`='Do you know where I can find Half Pendant of Aquatic Endurance?' WHERE `word_id`=128016; -- locales_gossip_menu_option - option_text : menu_id=4042-id=1
UPDATE `trans_words` SET `content_loc8`='Get me up into the skies, Sassy.' WHERE `word_id`=129655; -- locales_gossip_menu_option - option_text : menu_id=11146-id=0
UPDATE `trans_words` SET `content_loc8`='Hearthglen? But...' WHERE `word_id`=127883; -- locales_gossip_menu_option - option_text : menu_id=2904-id=0
UPDATE `trans_words` SET `content_loc8`='Hold on friend. Tell me what happened here.' WHERE `word_id`=129519; -- locales_gossip_menu_option - option_text : menu_id=10036-id=0
UPDATE `trans_words` SET `content_loc8`='I am ready to meet with Anachronos, Ziradormi.' WHERE `word_id`=129927; -- locales_gossip_menu_option - option_text : menu_id=12760-id=0
UPDATE `trans_words` SET `content_loc8`='I know this is rather silly but a young ward who is a bit shy would like your hoofprint.' WHERE `word_id`=127943; -- locales_gossip_menu_option - option_text : menu_id=5851-id=0
UPDATE `trans_words` SET `content_loc8`='I lost Spectral Essence.' WHERE `word_id`=129199; -- locales_gossip_menu_option - option_text : menu_id=3310-id=1
UPDATE `trans_words` SET `content_loc8`='I need to fly to the Windrunner. Official Business!' WHERE `word_id`=129081; -- locales_gossip_menu_option - option_text : menu_id=8894-id=0
UPDATE `trans_words` SET `content_loc8`='I need to know where the princess are, Kharan!' WHERE `word_id`=128457; -- locales_gossip_menu_option - option_text : menu_id=1822-id=0
UPDATE `trans_words` SET `content_loc8`='I was just wondering what you knew about the gnolls to the south. Someone has been giving them supplies to practice necromancy.' WHERE `word_id`=129775; -- locales_gossip_menu_option - option_text : menu_id=11942-id=0
UPDATE `trans_words` SET `content_loc8`='I would like to build a catapult.' WHERE `word_id`=129512; -- locales_gossip_menu_option - option_text : menu_id=9904-id=0
UPDATE `trans_words` SET `content_loc8`='I would like to build a demolisher.' WHERE `word_id`=129513; -- locales_gossip_menu_option - option_text : menu_id=9904-id=1
UPDATE `trans_words` SET `content_loc8`='I would like to build a siege engine.' WHERE `word_id`=129514; -- locales_gossip_menu_option - option_text : menu_id=9904-id=2
UPDATE `trans_words` SET `content_loc8`='I\'d like you to make me a new Cache of Mau\'ari please' WHERE `word_id`=129191; -- locales_gossip_menu_option - option_text : menu_id=2703-id=2
UPDATE `trans_words` SET `content_loc8`='I\'m ready to deliver the tome, Arcanist Tybalin.' WHERE `word_id`=129624; -- locales_gossip_menu_option - option_text : menu_id=10858-id=1
UPDATE `trans_words` SET `content_loc8`='If you want to know is male or female, look Frost Leopard by the tail.' WHERE `word_id`=129562; -- locales_gossip_menu_option - option_text : menu_id=10273-id=0
UPDATE `trans_words` SET `content_loc8`='If you want to know is male or female, look Icepaw Bear by the tail.' WHERE `word_id`=129563; -- locales_gossip_menu_option - option_text : menu_id=10274-id=0
UPDATE `trans_words` SET `content_loc8`='Is there anything you would have of me?' WHERE `word_id`=128367; -- locales_gossip_menu_option - option_text : menu_id=50012-id=0
UPDATE `trans_words` SET `content_loc8`='Is there something I can do at the Shrine of Malorne?' WHERE `word_id`=129801; -- locales_gossip_menu_option - option_text : menu_id=12167-id=3
UPDATE `trans_words` SET `content_loc8`='Lady Proudmoore. I am ready to go to Orgrimmar. Please open a portal.' WHERE `word_id`=129550; -- locales_gossip_menu_option - option_text : menu_id=10189-id=0
UPDATE `trans_words` SET `content_loc8`='lala' WHERE `word_id`=129425; -- locales_gossip_menu_option - option_text : menu_id=9212-id=1
UPDATE `trans_words` SET `content_loc8`='Learn recipe...' WHERE `word_id`=129264; -- locales_gossip_menu_option - option_text : menu_id=6443-id=0
UPDATE `trans_words` SET `content_loc8`='May I have your report?' WHERE `word_id`=127969; -- locales_gossip_menu_option - option_text : menu_id=6690-id=0
UPDATE `trans_words` SET `content_loc8`='Ner\'zhul' WHERE `word_id`=128151; -- locales_gossip_menu_option - option_text : menu_id=4764-id=2
UPDATE `trans_words` SET `content_loc8`='Perhaps I can be of some assistance. I will make a deal with you, Satyr. I shall recover this unforged breastplate and slay the beast. In exchange for this task, you will teach me how to create the breastplate.' WHERE `word_id`=128373; -- locales_gossip_menu_option - option_text : menu_id=50007-id=0
UPDATE `trans_words` SET `content_loc8`='Show me my bank' WHERE `word_id`=129169; -- locales_gossip_menu_option - option_text : menu_id=0-id=7
UPDATE `trans_words` SET `content_loc8`='Take Blood Knight Insignia' WHERE `word_id`=129002; -- locales_gossip_menu_option - option_text : menu_id=7486-id=0
UPDATE `trans_words` SET `content_loc8`='Take me to the Caverns of Time' WHERE `word_id`=129424; -- locales_gossip_menu_option - option_text : menu_id=9205-id=0
UPDATE `trans_words` SET `content_loc8`='Thank you for telling me your story.' WHERE `word_id`=129406; -- locales_gossip_menu_option - option_text : menu_id=9182-id=0
UPDATE `trans_words` SET `content_loc8`='Thank you! I will be sure to notify you if I find anything else.' WHERE `word_id`=129146; -- locales_gossip_menu_option - option_text : menu_id=10213-id=0
UPDATE `trans_words` SET `content_loc8`='The word is given. The King-lich will accept death from our hands!' WHERE `word_id`=129661; -- locales_gossip_menu_option - option_text : menu_id=11207-id=0
UPDATE `trans_words` SET `content_loc8`='This Dimensional Imploder sounds dangerous! How can I make one?' WHERE `word_id`=128186; -- locales_gossip_menu_option - option_text : menu_id=6092-id=0
UPDATE `trans_words` SET `content_loc8`='Transcript the Tablet' WHERE `word_id`=128093; -- locales_gossip_menu_option - option_text : menu_id=2187-id=0
UPDATE `trans_words` SET `content_loc8`='Watcher Analisis: Freya' WHERE `word_id`=129576; -- locales_gossip_menu_option - option_text : menu_id=10368-id=2
UPDATE `trans_words` SET `content_loc8`='Watcher Analisis: Hodir' WHERE `word_id`=129577; -- locales_gossip_menu_option - option_text : menu_id=10368-id=3
UPDATE `trans_words` SET `content_loc8`='Watcher Analisis: Mimiron' WHERE `word_id`=129579; -- locales_gossip_menu_option - option_text : menu_id=10368-id=5
UPDATE `trans_words` SET `content_loc8`='Watcher Analisis: Thorim' WHERE `word_id`=129578; -- locales_gossip_menu_option - option_text : menu_id=10368-id=4
UPDATE `trans_words` SET `content_loc8`='Would you renew my Silver Covenant disguise?' WHERE `word_id`=129623; -- locales_gossip_menu_option - option_text : menu_id=10857-id=2
UPDATE `trans_words` SET `content_loc8`='Yes elder. Tell me more of the book.' WHERE `word_id`=128719; -- locales_gossip_menu_option - option_text : menu_id=8617-id=0
UPDATE `trans_words` SET `content_loc8`='Yes... yes, it\'s me.' WHERE `word_id`=128718; -- locales_gossip_menu_option - option_text : menu_id=8616-id=0
UPDATE `trans_words` SET `content_loc8`='You gave the crew disguises?' WHERE `word_id`=128740; -- locales_gossip_menu_option - option_text : menu_id=8775-id=0
UPDATE `trans_words` SET `content_loc8`='You may choose to care for an Oracle orphan or a frenzyheart orphan. But you will not be able help both.' WHERE `word_id` = 129591; -- locales_gossip_menu_option - box_text : menu_id=10502-id=0

SET NAMES 'latin1';
