-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc3`='%s begins to emanate a power dark energy!' WHERE `word_id` = 6657; -- creature_ai_texts - content : entry=-736
UPDATE `trans_words` SET `content_loc3`='%s calls for his worgs!' WHERE `word_id` = 6411; -- creature_ai_texts - content : entry=-187
UPDATE `trans_words` SET `content_loc3`='%s shimmers and becomes intangible.' WHERE `word_id` = 6159; -- creature_ai_texts - content : entry=-830
UPDATE `trans_words` SET `content_loc3`='%s stares in silence at the graver marker before him.' WHERE `word_id` = 6127; -- creature_ai_texts - content : entry=-923
UPDATE `trans_words` SET `content_loc3`='%s strength fades!' WHERE `word_id` = 6423; -- creature_ai_texts - content : entry=-153
UPDATE `trans_words` SET `content_loc3`='%s whispers softley in reverent tones under her breath.' WHERE `word_id` = 6301; -- creature_ai_texts - content : entry=-339
UPDATE `trans_words` SET `content_loc3`='%s\'s remains fall on the ground.' WHERE `word_id` = 6670; -- creature_ai_texts - content : entry=-776
UPDATE `trans_words` SET `content_loc3`='...Go or I taunt you a second time!' WHERE `word_id` = 6586; -- creature_ai_texts - content : entry=-504
UPDATE `trans_words` SET `content_loc3`='..Marwyn..! Finish them..!' WHERE `word_id` = 6788; -- creature_ai_texts - content : entry=-1123
UPDATE `trans_words` SET `content_loc3`='<Angry roar>' WHERE `word_id` = 3077; -- creature_ai_texts - content : entry=-26
UPDATE `trans_words` SET `content_loc3`='A fitting punishment!' WHERE `word_id` = 6803; -- creature_ai_texts - content : entry=-1161
UPDATE `trans_words` SET `content_loc3`='Aah, quality materials!' WHERE `word_id` = 6711; -- creature_ai_texts - content : entry=-850
UPDATE `trans_words` SET `content_loc3`='Ahh, another powerful traveler. The nether can be dangerous; you\'ll want the most potent spells at your disposal. I carry the finest reagents, common and exotic. Come and buy - you won\'t be sorry!' WHERE `word_id` = 6302; -- creature_ai_texts - content : entry=-338
UPDATE `trans_words` SET `content_loc3`='All of your efforts have been in vain, for the draining of the World Tree has already begun! Soon, the heart of your world shall beat no more!' WHERE `word_id` = 6409; -- creature_ai_texts - content : entry=-216
UPDATE `trans_words` SET `content_loc3`='Alright, quiet down. We have a lot of work to do and very little time to do it in, people.' WHERE `word_id` = 6289; -- creature_ai_texts - content : entry=-382
UPDATE `trans_words` SET `content_loc3`='And if that weren\'t crazy enough, that big demon gets killed by a bunch of floating light things... Oh, I was also a female elf in that one... Yep...' WHERE `word_id` = 6231; -- creature_ai_texts - content : entry=-604
UPDATE `trans_words` SET `content_loc3`='And the Kirin Tor? What have they to say of this necromancy?' WHERE `word_id` = 6209; -- creature_ai_texts - content : entry=-626
UPDATE `trans_words` SET `content_loc3`='And then gnomes are even worse! They are always saying stuff like...' WHERE `word_id` = 6061; -- creature_ai_texts - content : entry=-1072
UPDATE `trans_words` SET `content_loc3`='And there came an end to the suffering that they endure from you. I swear by my name, I\'ll put an end to your life.' WHERE `word_id` = 6904; -- creature_ai_texts - content : entry=-224482
UPDATE `trans_words` SET `content_loc3`='Arak-ha!' WHERE `word_id` = 5976; -- creature_ai_texts - content : entry=-1240
UPDATE `trans_words` SET `content_loc3`='Archbishop Landrgren must know! Aaaaaaaagggghhh.....!' WHERE `word_id` = 6631; -- creature_ai_texts - content : entry=-653
UPDATE `trans_words` SET `content_loc3`='Arise, my brothers!' WHERE `word_id` = 6892; -- creature_ai_texts - content : entry=-243811
UPDATE `trans_words` SET `content_loc3`='As masters of blood, we are masters of life and death itself. Against us, even hope falls drained and lifeless.' WHERE `word_id` = 6656; -- creature_ai_texts - content : entry=-735
UPDATE `trans_words` SET `content_loc3`='As you can see, your people are now mine. I will now turn this city, household by household, until the flame of life has been snuffed out forever.' WHERE `word_id` = 6867; -- creature_ai_texts - content : entry=-869
UPDATE `trans_words` SET `content_loc3`='Ashes to ashes, dust to dust.' WHERE `word_id` = 6439; -- creature_ai_texts - content : entry=-129
UPDATE `trans_words` SET `content_loc3`='Avuun dares to oppose me? I will crush him! When I am done with the draenei, they\'ll wish that they were Lost Ones!' WHERE `word_id` = 6095; -- creature_ai_texts - content : entry=-979
UPDATE `trans_words` SET `content_loc3`='Azeroth has cowered too long under our shadow! Now, feel the power of the Burning Crusade, and despair!' WHERE `word_id` = 5998; -- creature_ai_texts - content : entry=-1206
UPDATE `trans_words` SET `content_loc3`='Band\'or shorel\'aran!' WHERE `word_id` = 6511; -- creature_ai_texts - content : entry=-38
UPDATE `trans_words` SET `content_loc3`='Big red bastards! Bigger than any orc I\'d ever seen. Muscles out to here, tusks out to here...' WHERE `word_id` = 6343; -- creature_ai_texts - content : entry=-291
UPDATE `trans_words` SET `content_loc3`='Bladespire clan not fight fair. Have Gronn to help dem. You go to Blade\'s Edge Mountains. Talk to Mog\'dorg the Wizened. Kill Gromm.' WHERE `word_id` = 6372; -- creature_ai_texts - content : entry=-261
UPDATE `trans_words` SET `content_loc3`='Bron! \'Ey Bron! \'Ey Bron! Hit me!' WHERE `word_id` = 6308; -- creature_ai_texts - content : entry=-332
UPDATE `trans_words` SET `content_loc3`='But it is in chains. There must also be a way to release her.' WHERE `word_id` = 6873; -- creature_ai_texts - content : entry=-50003
UPDATE `trans_words` SET `content_loc3`='But they should try, or else all will be lost. Drakkari and destroy themselves and their gods!' WHERE `word_id` = 6874; -- creature_ai_texts - content : entry=-50004
UPDATE `trans_words` SET `content_loc3`='Butcher! Die' WHERE `word_id` = 6768; -- creature_ai_texts - content : entry=-995
UPDATE `trans_words` SET `content_loc3`='C\'mere, $R. Ya don\'t want to be riskin\' yerself in a dungeon, do ya? Filthy work, and for what? Some worthless trinket? Nah, what ya need be one of my amulets. Guarenteed to work!' WHERE `word_id` = 6381; -- creature_ai_texts - content : entry=-252
UPDATE `trans_words` SET `content_loc3`='Cabal Summoner summons a Cabal Acolyte to his aid!' WHERE `word_id` = 5968; -- creature_ai_texts - content : entry=-1248
UPDATE `trans_words` SET `content_loc3`='Cabal Summoner summons a Cabal Deathsworn to his aid!' WHERE `word_id` = 5969; -- creature_ai_texts - content : entry=-1247
UPDATE `trans_words` SET `content_loc3`='Can I get a buff? I\'m dying up here!' WHERE `word_id` = 6035; -- creature_ai_texts - content : entry=-1099
UPDATE `trans_words` SET `content_loc3`='Can not be! Am I finally being free?' WHERE `word_id` = 6882; -- creature_ai_texts - content : entry=-332201
UPDATE `trans_words` SET `content_loc3`='Can\'t say I didn\'t warn you!' WHERE `word_id` = 6467; -- creature_ai_texts - content : entry=-92
UPDATE `trans_words` SET `content_loc3`='Chaos!' WHERE `word_id` = 2344; -- creature_ai_texts - content : entry=-790
UPDATE `trans_words` SET `content_loc3`='Cipher of Damnation belongs to us now!' WHERE `word_id` = 6528; -- creature_ai_texts - content : entry=-23
UPDATE `trans_words` SET `content_loc3`='Come Scourgebane, I\'ll show the Lich King which one of us is truly worthy of the title, champion!' WHERE `word_id` = 3804; -- creature_ai_texts - content : entry=-1137
UPDATE `trans_words` SET `content_loc3`='Come, citizen of Stratholme! Meet your saviors.' WHERE `word_id` = 6714; -- creature_ai_texts - content : entry=-853
UPDATE `trans_words` SET `content_loc3`='Cower, little worms! Your heroes are nothing! Your saviors will be our first feast!' WHERE `word_id` = 5996; -- creature_ai_texts - content : entry=-1208
UPDATE `trans_words` SET `content_loc3`='Damm those ogres. Damn them to the Nether. Won\'t someone save us from these savages! This is the fifth kidnapping is as many days.' WHERE `word_id` = 6321; -- creature_ai_texts - content : entry=-314
UPDATE `trans_words` SET `content_loc3`='Dangerous out there, innit? Know what ya need? Protection. I can help ya defy death itself! Ya wear this madstone \'round yer neck, see, and then ya be able to come back if ya find yerself in the spirit world! Just a quick jaunt to yer corpse and up ya com' WHERE `word_id` = 6380; -- creature_ai_texts - content : entry=-253
UPDATE `trans_words` SET `content_loc3`='De\'re be a bird!' WHERE `word_id` = 6777; -- creature_ai_texts - content : entry=-1018
UPDATE `trans_words` SET `content_loc3`='De\'re be a bug.' WHERE `word_id` = 6775; -- creature_ai_texts - content : entry=-1016
UPDATE `trans_words` SET `content_loc3`='Despair...so delicious' WHERE `word_id` = 6792; -- creature_ai_texts - content : entry=-1127
UPDATE `trans_words` SET `content_loc3`='Do I detect a hint of cinnamon? Or is that nutmeg? Whatever it is, one thing is for sure - nobody cooks donkey like you, Cookie.' WHERE `word_id` = 6340; -- creature_ai_texts - content : entry=-294
UPDATE `trans_words` SET `content_loc3`='DO IT, YE PANSEY!' WHERE `word_id` = 6310; -- creature_ai_texts - content : entry=-330
UPDATE `trans_words` SET `content_loc3`='Do you think that demons will play fair? These beasts are more savage than the orcs, more cunning than the undead. Do not attempt to engage Legion by normal standards of war.' WHERE `word_id` = 6306; -- creature_ai_texts - content : entry=-334
UPDATE `trans_words` SET `content_loc3`='Does anyone need any supplies to down the trolls? Any troll will do.' WHERE `word_id` = 6123; -- creature_ai_texts - content : entry=-939
UPDATE `trans_words` SET `content_loc3`='Don\'t feel.....so good.....' WHERE `word_id` = 6245; -- creature_ai_texts - content : entry=-589
UPDATE `trans_words` SET `content_loc3`='Don\'t worry, I\'ll make good use of you.' WHERE `word_id` = 6712; -- creature_ai_texts - content : entry=-851
UPDATE `trans_words` SET `content_loc3`='Dragonhawk incoming from the west! Shoot that druid down!' WHERE `word_id` = 6269; -- creature_ai_texts - content : entry=-403
UPDATE `trans_words` SET `content_loc3`='Enough! I will erase your very existence!' WHERE `word_id` = 5955; -- creature_ai_texts - content : entry=-1261
UPDATE `trans_words` SET `content_loc3`='Farunn goes on land to the north of the place that you people call a sweet waterfall waves. You\'ll find him one, but saw him, you will realize that he needs no defenders.' WHERE `word_id` = 6877; -- creature_ai_texts - content : entry=-50007
UPDATE `trans_words` SET `content_loc3`='Fear...so exhilarating!' WHERE `word_id` = 6791; -- creature_ai_texts - content : entry=-1126
UPDATE `trans_words` SET `content_loc3`='Five seconds! I\'m not kidding!' WHERE `word_id` = 6497; -- creature_ai_texts - content : entry=-56
UPDATE `trans_words` SET `content_loc3`='Follow me to the mountains and do the will of our Lord!' WHERE `word_id` = 6894; -- creature_ai_texts - content : entry=-243813
UPDATE `trans_words` SET `content_loc3`='Fools! You deny the existence of my father? Die, mortal!' WHERE `word_id` = 6919; -- creature_ai_texts - content : entry=-170001
UPDATE `trans_words` SET `content_loc3`='Gather \'round...' WHERE `word_id` = 6799; -- creature_ai_texts - content : entry=-1155
UPDATE `trans_words` SET `content_loc3`='Go ahead, gimme your best shot. I can take it!' WHERE `word_id` = 6469; -- creature_ai_texts - content : entry=-90
UPDATE `trans_words` SET `content_loc3`='GOOO!' WHERE `word_id` = 6627; -- creature_ai_texts - content : entry=-633
UPDATE `trans_words` SET `content_loc3`='Grek get a drink.' WHERE `word_id` = 6386; -- creature_ai_texts - content : entry=-247
UPDATE `trans_words` SET `content_loc3`='Grrrrr!' WHERE `word_id` = 6634; -- creature_ai_texts - content : entry=-689
UPDATE `trans_words` SET `content_loc3`='Guards! Come and kill these intruders!' WHERE `word_id` = 6510; -- creature_ai_texts - content : entry=-39
UPDATE `trans_words` SET `content_loc3`='Guards! Urgh..Guards..!' WHERE `word_id` = 5963; -- creature_ai_texts - content : entry=-1253
UPDATE `trans_words` SET `content_loc3`='Ha! The Thunderspike my! Die!' WHERE `word_id` = 6900; -- creature_ai_texts - content : entry=-213192
UPDATE `trans_words` SET `content_loc3`='Ha! This place is not yet worthy of my infliction.' WHERE `word_id` = 5992; -- creature_ai_texts - content : entry=-1212
UPDATE `trans_words` SET `content_loc3`='Hal...' WHERE `word_id` = 6244; -- creature_ai_texts - content : entry=-590
UPDATE `trans_words` SET `content_loc3`='Halt!' WHERE `word_id` = 5944; -- creature_ai_texts - content : entry=-1276
UPDATE `trans_words` SET `content_loc3`='He asked if the imp could join in... can you believe it? Actually, it wasn\'t half bad...' WHERE `word_id` = 6495; -- creature_ai_texts - content : entry=-58
UPDATE `trans_words` SET `content_loc3`='Hey Hey Hey! It\'s Raliq the drunk... His momma\'s so fat she didn\'t just make the front cover of Ogre Today...' WHERE `word_id` = 6057; -- creature_ai_texts - content : entry=-1077
UPDATE `trans_words` SET `content_loc3`='HEY YOU! DRINK OGRE BREWS! MAKE YOU BIG AND STRONG!' WHERE `word_id` = 6165; -- creature_ai_texts - content : entry=-718
UPDATE `trans_words` SET `content_loc3`='Hey! Hey, $R! I be havin\' just the thing for ya. Ya ever see a Tikbalang? Frightenin\' creatures. Prone to stealin\' ya away. What ya need is my tikbaland wards. Guaranteed to ward away all tikbalangs!' WHERE `word_id` = 6375; -- creature_ai_texts - content : entry=-258
UPDATE `trans_words` SET `content_loc3`='Hey, harbringer, how\'s that research coming along? There might be an Ultra-Kinetic Waffle Iron in it for you if you\'re prompt with the results!' WHERE `word_id` = 6158; -- creature_ai_texts - content : entry=-831
UPDATE `trans_words` SET `content_loc3`='Hey, hey sweet thing! Looking good!' WHERE `word_id` = 6078; -- creature_ai_texts - content : entry=-1007
UPDATE `trans_words` SET `content_loc3`='Hey, hey! Nice build you got there honey!' WHERE `word_id` = 6077; -- creature_ai_texts - content : entry=-1008
UPDATE `trans_words` SET `content_loc3`='Hey, it\'s Raliq the drunk... His momma\'s so fat, when she flies to Blade\'s Edge they charged her by the pound!' WHERE `word_id` = 6039; -- creature_ai_texts - content : entry=-1095
UPDATE `trans_words` SET `content_loc3`='Hold them back while I release the warhounds!' WHERE `word_id` = 6414; -- creature_ai_texts - content : entry=-179
UPDATE `trans_words` SET `content_loc3`='I am the Keymaster. Are you the Gatekeeper?' WHERE `word_id` = 6579; -- creature_ai_texts - content : entry=-495
UPDATE `trans_words` SET `content_loc3`='I can\'t belive that Papa Wheeler thinks he\'s going to dupe anyone into going out to Manaforge B\'naar!' WHERE `word_id` = 6014; -- creature_ai_texts - content : entry=-1130
UPDATE `trans_words` SET `content_loc3`='I can\'t even believe this one... You know two loudmouthed ruffians, Foror and Tigule?' WHERE `word_id` = 6224; -- creature_ai_texts - content : entry=-611
UPDATE `trans_words` SET `content_loc3`='I could have sworn I had more apples. Grok!' WHERE `word_id` = 6378; -- creature_ai_texts - content : entry=-255
UPDATE `trans_words` SET `content_loc3`='I don\'t see why we ally with filthy stinking trolls? The only good troll is a dead troll.' WHERE `word_id` = 6122; -- creature_ai_texts - content : entry=-940
UPDATE `trans_words` SET `content_loc3`='I feel that war is fast approaching. The fruit vendor has enlisted to help an ogre. I shall have to enlist help as well.' WHERE `word_id` = 6369; -- creature_ai_texts - content : entry=-264
UPDATE `trans_words` SET `content_loc3`='I have all of you will break!' WHERE `word_id` = 6896; -- creature_ai_texts - content : entry=-296471
UPDATE `trans_words` SET `content_loc3`='I have no equal.' WHERE `word_id` = 1720; -- creature_ai_texts - content : entry=-1269
UPDATE `trans_words` SET `content_loc3`='I hope you die! Painfully!' WHERE `word_id` = 6517; -- creature_ai_texts - content : entry=-20
UPDATE `trans_words` SET `content_loc3`='I know very little else... The High General chooses who may go and who must stay behind. There\'s nothing else... You must believe me!' WHERE `word_id` = 6614; -- creature_ai_texts - content : entry=-558
UPDATE `trans_words` SET `content_loc3`='I know why you\'ve come - one of those foolish Magnataur on the plains meddled and managed to get the dragons involved. Do you enjoy serving them like dogs?' WHERE `word_id` = 6749; -- creature_ai_texts - content : entry=-892
UPDATE `trans_words` SET `content_loc3`='I love blood elf women. Especially when they say stuff like this...' WHERE `word_id` = 6053; -- creature_ai_texts - content : entry=-1081
UPDATE `trans_words` SET `content_loc3`='I love night elf women. Especially when they say stuff like this...' WHERE `word_id` = 6021; -- creature_ai_texts - content : entry=-1113
UPDATE `trans_words` SET `content_loc3`='I miss my dog so much...' WHERE `word_id` = 6425; -- creature_ai_texts - content : entry=-151
UPDATE `trans_words` SET `content_loc3`='I Rexxar son Mokh\'Natala, defender of the Horde' WHERE `word_id` = 6903; -- creature_ai_texts - content : entry=-224481
UPDATE `trans_words` SET `content_loc3`='I see you, insect! Come closer' WHERE `word_id` = 6567; -- creature_ai_texts - content : entry=-479
UPDATE `trans_words` SET `content_loc3`='I will end this quickly...' WHERE `word_id` = 6261; -- creature_ai_texts - content : entry=-463
UPDATE `trans_words` SET `content_loc3`='I will not lie down quietly and wait until you can not kill me! You\'ll have to bet for the right to take another breath, if you want to kill me, mortal!' WHERE `word_id` = 6918; -- creature_ai_texts - content : entry=-284161
UPDATE `trans_words` SET `content_loc3`='I... Deserve this.' WHERE `word_id` = 6461; -- creature_ai_texts - content : entry=-98
UPDATE `trans_words` SET `content_loc3`='I\'ll eat you whole!' WHERE `word_id` = 6898; -- creature_ai_texts - content : entry=-296473
UPDATE `trans_words` SET `content_loc3`='I\'m flesh and blood again! Thank you!' WHERE `word_id` = 6744; -- creature_ai_texts - content : entry=-887
UPDATE `trans_words` SET `content_loc3`='I\'m gonna cook ya, and then i\'m going to eat ya!' WHERE `word_id` = 6518; -- creature_ai_texts - content : entry=-19
UPDATE `trans_words` SET `content_loc3`='I\'m not gonna lie to you, soldiers. We\'re getting our butts out there! Now which one of you is orc enough to do something about it?' WHERE `word_id` = 6015; -- creature_ai_texts - content : entry=-1129
UPDATE `trans_words` SET `content_loc3`='If my division is correct you should be quite dead.' WHERE `word_id` = 6474; -- creature_ai_texts - content : entry=-85
UPDATE `trans_words` SET `content_loc3`='If no one help. Grok smash!' WHERE `word_id` = 6377; -- creature_ai_texts - content : entry=-256
UPDATE `trans_words` SET `content_loc3`='If none of you ladies have any questions, you can get further instruction and assignments from your squad leaders. That\'s it. Good luck!' WHERE `word_id` = 6284; -- creature_ai_texts - content : entry=-387
UPDATE `trans_words` SET `content_loc3`='If that weren\'t crazy enough, they decided to quit the ice-cream business and become adventurers... They travel all over the place and finally disappears into some portal. I woke up in a cold sweat after that one...' WHERE `word_id` = 6222; -- creature_ai_texts - content : entry=-613
UPDATE `trans_words` SET `content_loc3`='Illidan reigns!' WHERE `word_id` = 6422; -- creature_ai_texts - content : entry=-154
UPDATE `trans_words` SET `content_loc3`='Impersonation time!! I call this, "The Silly Tauren."' WHERE `word_id` = 6068; -- creature_ai_texts - content : entry=-1065
UPDATE `trans_words` SET `content_loc3`='Intruder detected! Neutralizing threat immediately!' WHERE `word_id` = 6114; -- creature_ai_texts - content : entry=-959
UPDATE `trans_words` SET `content_loc3`='Is that all you\'ve... got?' WHERE `word_id` = 6624; -- creature_ai_texts - content : entry=-630
UPDATE `trans_words` SET `content_loc3`='Iskalder? You fool! Have you no idea who that is? He\'s only the greatest vrykul warrior who ever lived!' WHERE `word_id` = 6921; -- creature_ai_texts - content : entry=-308364
UPDATE `trans_words` SET `content_loc3`='It had to be done.' WHERE `word_id` = 6463; -- creature_ai_texts - content : entry=-96
UPDATE `trans_words` SET `content_loc3`='It is Prince Arthas I want, not you.' WHERE `word_id` = 6733; -- creature_ai_texts - content : entry=-876
UPDATE `trans_words` SET `content_loc3`='It seems my freedom must be bought... with blood.' WHERE `word_id` = 6697; -- creature_ai_texts - content : entry=-811
UPDATE `trans_words` SET `content_loc3`='It\'s all... coming back to me.' WHERE `word_id` = 6490; -- creature_ai_texts - content : entry=-63
UPDATE `trans_words` SET `content_loc3`='It\'s too bad they don\'t stay cute. There must be some right of passage in the Barrens called, "Climb ugly tree and fall out."' WHERE `word_id` = 6043; -- creature_ai_texts - content : entry=-1091
UPDATE `trans_words` SET `content_loc3`='Kada nu batteka, oht!' WHERE `word_id` = 6594; -- creature_ai_texts - content : entry=-512
UPDATE `trans_words` SET `content_loc3`='Kaganishu!' WHERE `word_id` = 6592; -- creature_ai_texts - content : entry=-510
UPDATE `trans_words` SET `content_loc3`='King Dred calls for a raptor!' WHERE `word_id` = 6640; -- creature_ai_texts - content : entry=-697
UPDATE `trans_words` SET `content_loc3`='King Dred raises his talon menacingly!' WHERE `word_id` = 6639; -- creature_ai_texts - content : entry=-696
UPDATE `trans_words` SET `content_loc3`='Krypta!' WHERE `word_id` = 288072; -- creature_ai_texts - content : entry=-467
UPDATE `trans_words` SET `content_loc3`='Last time someone went out to try and collect the bounty on Netherlock, all we got back was a compressed layer of foolhardy adventurer!' WHERE `word_id` = 6317; -- creature_ai_texts - content : entry=-318
UPDATE `trans_words` SET `content_loc3`='Little- $R is not able to raise a spear. Gore to raise the spear!' WHERE `word_id` = 6899; -- creature_ai_texts - content : entry=-213191
UPDATE `trans_words` SET `content_loc3`='Lok Narash!' WHERE `word_id` = 6419; -- creature_ai_texts - content : entry=-157
UPDATE `trans_words` SET `content_loc3`='Lok\'tar Illidari!' WHERE `word_id` = 6417; -- creature_ai_texts - content : entry=-159
UPDATE `trans_words` SET `content_loc3`='Look over here, $C! I got somethin\' for ya. Just what ya need. It\'s soap, right... and it\'s on a rope! No offense, man, but yer a little ripe, you know what I\'m sayin\'?' WHERE `word_id` = 6376; -- creature_ai_texts - content : entry=-257
UPDATE `trans_words` SET `content_loc3`='Looks like today was the wrong day to quit mana tapping...' WHERE `word_id` = 6110; -- creature_ai_texts - content : entry=-963
UPDATE `trans_words` SET `content_loc3`='Low tech yet quite effective!' WHERE `word_id` = 5989; -- creature_ai_texts - content : entry=-1215
UPDATE `trans_words` SET `content_loc3`='Me hungry. Fruit look tasty.' WHERE `word_id` = 6367; -- creature_ai_texts - content : entry=-266
UPDATE `trans_words` SET `content_loc3`='Measure twice, cut once.' WHERE `word_id` = 6475; -- creature_ai_texts - content : entry=-84
UPDATE `trans_words` SET `content_loc3`='Men... Women... and Children. None were spared the Master\'s wrath. Your death will be no different.' WHERE `word_id` = 6787; -- creature_ai_texts - content : entry=-1122
UPDATE `trans_words` SET `content_loc3`='Mission accomplished.' WHERE `word_id` = 6516; -- creature_ai_texts - content : entry=-21
UPDATE `trans_words` SET `content_loc3`='M-mistress... did you n-need more corpse dust, p-perhaps... ?' WHERE `word_id` = 6644; -- creature_ai_texts - content : entry=-723
UPDATE `trans_words` SET `content_loc3`='M-mistress... may I p-polish your armor ...?' WHERE `word_id` = 6645; -- creature_ai_texts - content : entry=-724
UPDATE `trans_words` SET `content_loc3`='M-mistress... Might I brush your mighty steed?' WHERE `word_id` = 6646; -- creature_ai_texts - content : entry=-725
UPDATE `trans_words` SET `content_loc3`='Move along, $C.' WHERE `word_id` = 6125; -- creature_ai_texts - content : entry=-937
UPDATE `trans_words` SET `content_loc3`='Mrmrmrmrmrmrm... mrmrmrmr?' WHERE `word_id` = 6929; -- creature_ai_texts - content : entry=-298592
UPDATE `trans_words` SET `content_loc3`='Mrrfrmrfrmrrrrr!' WHERE `word_id` = 6928; -- creature_ai_texts - content : entry=-298591
UPDATE `trans_words` SET `content_loc3`='My friends, please join me in humble supplication the the Light.' WHERE `word_id` = 6355; -- creature_ai_texts - content : entry=-279
UPDATE `trans_words` SET `content_loc3`='My minions...$B$BSoon your thirst for destruction will be quenched. The rebels of Lordaeron are small, and weak, and know not the joy of serving our Lich King. Prepar yourselves, for we will soon launch an assault agianst they who called themselves "The Forsaken." Theese undead rabble, and their dead-elf queen, will fall! Death, and praise the Lich King!' WHERE `word_id` = 268210; -- creature_ai_texts - content : entry=-10000
UPDATE `trans_words` SET `content_loc3`='My minions...$B$BThe time for conquest approaches quickly. The rebels of Lordaeron are small, and weak, and know not the joy of serving our Lich King. Make ready for battle, my creations. We will drive our foes from Silverpine, then bring the very tides of war to their very capital! Death, and praise the Lich King!' WHERE `word_id` = 268211; -- creature_ai_texts - content : entry=-10001
UPDATE `trans_words` SET `content_loc3`='My pets are hungry and they will dine on your flesh!' WHERE `word_id` = 6413; -- creature_ai_texts - content : entry=-180
UPDATE `trans_words` SET `content_loc3`='Never underestimate the other ethereal\'s greed.' WHERE `word_id` = 6162; -- creature_ai_texts - content : entry=-816
UPDATE `trans_words` SET `content_loc3`='No more middling for you.' WHERE `word_id` = 5960; -- creature_ai_texts - content : entry=-1256
UPDATE `trans_words` SET `content_loc3`='NO! I will kill you all!' WHERE `word_id` = 6762; -- creature_ai_texts - content : entry=-954
UPDATE `trans_words` SET `content_loc3`='No!...The master... will not... be pleased.' WHERE `word_id` = 5949; -- creature_ai_texts - content : entry=-1267
UPDATE `trans_words` SET `content_loc3`='Nothing personal...' WHERE `word_id` = 6698; -- creature_ai_texts - content : entry=-812
UPDATE `trans_words` SET `content_loc3`='Now we$B$Be getting someplace!' WHERE `word_id` = 6623; -- creature_ai_texts - content : entry=-629
UPDATE `trans_words` SET `content_loc3`='Observed to be caught. Their fates are intertwined.' WHERE `word_id` = 6871; -- creature_ai_texts - content : entry=-50001
UPDATE `trans_words` SET `content_loc3`='Off with you, $N.' WHERE `word_id` = 6126; -- creature_ai_texts - content : entry=-936
UPDATE `trans_words` SET `content_loc3`='Oh stop your whimpering.' WHERE `word_id` = 6514; -- creature_ai_texts - content : entry=-35
UPDATE `trans_words` SET `content_loc3`='Oh, would you please stop checking your nails and spanking yourself, for one moment? Really, no one cares!' WHERE `word_id` = 6098; -- creature_ai_texts - content : entry=-976
UPDATE `trans_words` SET `content_loc3`='Ooh what a dreadful job! All day, surrounded by the stench of bad feet.' WHERE `word_id` = 6119; -- creature_ai_texts - content : entry=-943
UPDATE `trans_words` SET `content_loc3`='Our iron masters is for us the job!' WHERE `word_id` = 6893; -- creature_ai_texts - content : entry=-243812
UPDATE `trans_words` SET `content_loc3`='Our job is to clear out as much of the fodder as we can, while supporting the specialists that the powers-that-be are having brought in.' WHERE `word_id` = 6274; -- creature_ai_texts - content : entry=-398
UPDATE `trans_words` SET `content_loc3`='Perhaps... you were right... Crok.' WHERE `word_id` = 3807; -- creature_ai_texts - content : entry=-1149
UPDATE `trans_words` SET `content_loc3`='Perish, mortal.' WHERE `word_id` = 1721; -- creature_ai_texts - content : entry=-1270
UPDATE `trans_words` SET `content_loc3`='Profit!' WHERE `word_id` = 6700; -- creature_ai_texts - content : entry=-814
UPDATE `trans_words` SET `content_loc3`='PROPHET!' WHERE `word_id` = 6763; -- creature_ai_texts - content : entry=-955
UPDATE `trans_words` SET `content_loc3`='Reesh, hokta!' WHERE `word_id` = 6449; -- creature_ai_texts - content : entry=-118
UPDATE `trans_words` SET `content_loc3`='Return to the satellite. Tell him that he went to Farunn and got him his reward.' WHERE `word_id` = 6878; -- creature_ai_texts - content : entry=-50008
UPDATE `trans_words` SET `content_loc3`='Rise, and fight once more!' WHERE `word_id` = 6666; -- creature_ai_texts - content : entry=-771
UPDATE `trans_words` SET `content_loc3`='said a deep, chilling voice ...' WHERE `word_id` = 6906; -- creature_ai_texts - content : entry=-211341
UPDATE `trans_words` SET `content_loc3`='Scream for me!' WHERE `word_id` = 6406; -- creature_ai_texts - content : entry=-219
UPDATE `trans_words` SET `content_loc3`='Sentence: executed!' WHERE `word_id` = 6804; -- creature_ai_texts - content : entry=-1162
UPDATE `trans_words` SET `content_loc3`='Shattered Sun scum! Fire at will!' WHERE `word_id` = 6271; -- creature_ai_texts - content : entry=-401
UPDATE `trans_words` SET `content_loc3`='Shaza-Kiel!' WHERE `word_id` = 6247; -- creature_ai_texts - content : entry=-575
UPDATE `trans_words` SET `content_loc3`='Showers fell Pal\'ea not calm down, son. Find a naga priestess!' WHERE `word_id` = 6870; -- creature_ai_texts - content : entry=-50000
UPDATE `trans_words` SET `content_loc3`='Shur\'nab... shur\'nab... Yogg-Saron!' WHERE `word_id` = 6696; -- creature_ai_texts - content : entry=-810
UPDATE `trans_words` SET `content_loc3`='Skywing! I will free you from your curse over my dead body!' WHERE `word_id` = 5984; -- creature_ai_texts - content : entry=-1220
UPDATE `trans_words` SET `content_loc3`='So can you teach me this... this...' WHERE `word_id` = 6210; -- creature_ai_texts - content : entry=-625
UPDATE `trans_words` SET `content_loc3`='So ends your defiance of the Spell-Weaver!' WHERE `word_id` = 6811; -- creature_ai_texts - content : entry=-1179
UPDATE `trans_words` SET `content_loc3`='So this gnome tells a tauren he\'s been to Molten Core.' WHERE `word_id` = 6027; -- creature_ai_texts - content : entry=-1107
UPDATE `trans_words` SET `content_loc3`='So, the Blood Elves think they\'re one step away from ruling the world...' WHERE `word_id` = 6032; -- creature_ai_texts - content : entry=-1102
UPDATE `trans_words` SET `content_loc3`='So, the oracle has decided to help you. Very good, I tell you what I know.' WHERE `word_id` = 6875; -- creature_ai_texts - content : entry=-50005
UPDATE `trans_words` SET `content_loc3`='Someone come read this wanted poster to Grek. Grek can\'t read.' WHERE `word_id` = 6389; -- creature_ai_texts - content : entry=-244
UPDATE `trans_words` SET `content_loc3`='Spare a copper, madame?' WHERE `word_id` = 6151; -- creature_ai_texts - content : entry=-838
UPDATE `trans_words` SET `content_loc3`='Speak, filthy refugee! What was your caravan doing in the Bone Wastes?' WHERE `word_id` = 6009; -- creature_ai_texts - content : entry=-1136
UPDATE `trans_words` SET `content_loc3`='Ssssekk-sara Rith-nealaak!' WHERE `word_id` = 5973; -- creature_ai_texts - content : entry=-1243
UPDATE `trans_words` SET `content_loc3`='Step forward! I will see that you are properly welcomed.' WHERE `word_id` = 6515; -- creature_ai_texts - content : entry=-34
UPDATE `trans_words` SET `content_loc3`='Stripping energy from our foes, both fighting and fallen, allows us to persevere where lesser beigns falls exhausted.' WHERE `word_id` = 6651; -- creature_ai_texts - content : entry=-730
UPDATE `trans_words` SET `content_loc3`='Struggle as much as you like!' WHERE `word_id` = 5950; -- creature_ai_texts - content : entry=-1266
UPDATE `trans_words` SET `content_loc3`='Succumb to the icy chill... of death!' WHERE `word_id` = 6442; -- creature_ai_texts - content : entry=-126
UPDATE `trans_words` SET `content_loc3`='Such a waste.' WHERE `word_id` = 3078; -- creature_ai_texts - content : entry=-27
UPDATE `trans_words` SET `content_loc3`='Suffer you despicable insect!' WHERE `word_id` = 6410; -- creature_ai_texts - content : entry=-199
UPDATE `trans_words` SET `content_loc3`='Sure enough, scount came runnin\' back, talkin\' bout some orcs down the path. They hadn\'t seen us yet so we figured we\'d go get aquainted.' WHERE `word_id` = 6342; -- creature_ai_texts - content : entry=-292
UPDATE `trans_words` SET `content_loc3`='Sweet dreams...' WHERE `word_id` = 6400; -- creature_ai_texts - content : entry=-225
UPDATE `trans_words` SET `content_loc3`='Take heart! Your friends will not long mourn your passing!' WHERE `word_id` = 6457; -- creature_ai_texts - content : entry=-110
UPDATE `trans_words` SET `content_loc3`='Thank you all. Ancient Druids took the wise decision to destroy Fordrassil, because it is deeply rooted in the land, where dwelt an ancient evil.' WHERE `word_id` = 6880; -- creature_ai_texts - content : entry=-50012
UPDATE `trans_words` SET `content_loc3`='Thank you everyone! And keep clapping, there is a fly in here and one of you are bound to get it! Good night!' WHERE `word_id` = 6036; -- creature_ai_texts - content : entry=-1098
UPDATE `trans_words` SET `content_loc3`='That one where thousands of people are all watching us up from the sky...' WHERE `word_id` = 6237; -- creature_ai_texts - content : entry=-598
UPDATE `trans_words` SET `content_loc3`='The %s doen\'t look like it minds the crystal\'s effect.' WHERE `word_id` = 6141; -- creature_ai_texts - content : entry=-909
UPDATE `trans_words` SET `content_loc3`='The blood is our power!' WHERE `word_id` = 6420; -- creature_ai_texts - content : entry=-156
UPDATE `trans_words` SET `content_loc3`='The Brotherhood will prevail!' WHERE `word_id` = 6864; -- creature_ai_texts - content : entry=-173
UPDATE `trans_words` SET `content_loc3`='The comedian impersonates a female dwarf.' WHERE `word_id` = 6028; -- creature_ai_texts - content : entry=-1106
UPDATE `trans_words` SET `content_loc3`='The comedian impersonates a female tauren.' WHERE `word_id` = 6042; -- creature_ai_texts - content : entry=-1092
UPDATE `trans_words` SET `content_loc3`='The comedian impersonates a night elf.' WHERE `word_id` = 6020; -- creature_ai_texts - content : entry=-1114
UPDATE `trans_words` SET `content_loc3`='The comedian impersonates an undead.' WHERE `word_id` = 6019; -- creature_ai_texts - content : entry=-1115
UPDATE `trans_words` SET `content_loc3`='The creatures of this place are strong, wayfarer. You\'ll need ample ammunition if you hope to survive. You\'re in luck - I am well-stocked with fine arrows, bullets, and throwing weapons. The price is reasonable, considering the circumstances.' WHERE `word_id` = 6303; -- creature_ai_texts - content : entry=-337
UPDATE `trans_words` SET `content_loc3`='The Dark Lady fought as many as she could, but in the end... I hope she survived. Please help!' WHERE `word_id` = 6770; -- creature_ai_texts - content : entry=-1011
UPDATE `trans_words` SET `content_loc3`='The falcon is vaniquished, doomed never to rise again! Your quest is futile!' WHERE `word_id` = 6552; -- creature_ai_texts - content : entry=-242
UPDATE `trans_words` SET `content_loc3`='The flesh is weak. We will make you better, stronger...faster.' WHERE `word_id` = 6606; -- creature_ai_texts - content : entry=-534
UPDATE `trans_words` SET `content_loc3`='The Light that guides us. The movement was set in motion before you came... We... We do as we are told. It is what must be done.' WHERE `word_id` = 6613; -- creature_ai_texts - content : entry=-557
UPDATE `trans_words` SET `content_loc3`='The master... will be angry...' WHERE `word_id` = 6506; -- creature_ai_texts - content : entry=-45
UPDATE `trans_words` SET `content_loc3`='The mojo of Sseratus is ours. Now all will be crushed under the might of the Drakkari!!' WHERE `word_id` = 6574; -- creature_ai_texts - content : entry=-486
UPDATE `trans_words` SET `content_loc3`='The prisoners shall not go free. The word of Malygos is law!' WHERE `word_id` = 6797; -- creature_ai_texts - content : entry=-1153
UPDATE `trans_words` SET `content_loc3`='The processing will continue a schedule!' WHERE `word_id` = 5987; -- creature_ai_texts - content : entry=-1217
UPDATE `trans_words` SET `content_loc3`='The soldiers are spreading panic with rumors of bad food. Neighbors are accusing one another of poison. The city will fall into bedlam!' WHERE `word_id` = 6735; -- creature_ai_texts - content : entry=-878
UPDATE `trans_words` SET `content_loc3`='The swarm is eager to feed!' WHERE `word_id` = 6403; -- creature_ai_texts - content : entry=-222
UPDATE `trans_words` SET `content_loc3`='The time of the Raven is night, but yours will end here!' WHERE `word_id` = 6392; -- creature_ai_texts - content : entry=-239
UPDATE `trans_words` SET `content_loc3`='The void...beckons.' WHERE `word_id` = 6202; -- creature_ai_texts - content : entry=-639
UPDATE `trans_words` SET `content_loc3`='The work must continue.' WHERE `word_id` = 6466; -- creature_ai_texts - content : entry=-93
UPDATE `trans_words` SET `content_loc3`='Then give him that he left this earth in peace. Do not place it here.' WHERE `word_id` = 6879; -- creature_ai_texts - content : entry=-50009
UPDATE `trans_words` SET `content_loc3`='They dont\'t know where to store the leftovers!' WHERE `word_id` = 6017; -- creature_ai_texts - content : entry=-1117
UPDATE `trans_words` SET `content_loc3`='Think you can hurt me, huh? Think I\'m afraid of you?!' WHERE `word_id` = 6468; -- creature_ai_texts - content : entry=-91
UPDATE `trans_words` SET `content_loc3`='This death should go to the creation of the altar. Their task will be easy. And might be even impossible.' WHERE `word_id` = 6872; -- creature_ai_texts - content : entry=-50002
UPDATE `trans_words` SET `content_loc3`='This one\'s real grim... So the king\'s kid Arthas...Well he goes out to battle evil, along with Uther *Nat pats his brow dry*' WHERE `word_id` = 6227; -- creature_ai_texts - content : entry=-608
UPDATE `trans_words` SET `content_loc3`='This vessel... is empty.' WHERE `word_id` = 6204; -- creature_ai_texts - content : entry=-637
UPDATE `trans_words` SET `content_loc3`='This war - and don\'t mistake this for anything but war - is not going to win itself. If we do not fight, scratch, claw, and kick for every speck of land on this shattered world, all will be lost.' WHERE `word_id` = 6304; -- creature_ai_texts - content : entry=-336
UPDATE `trans_words` SET `content_loc3`='This... is an unrecoverable... loss.' WHERE `word_id` = 6701; -- creature_ai_texts - content : entry=-815
UPDATE `trans_words` SET `content_loc3`='Time to move on...' WHERE `word_id` = 6487; -- creature_ai_texts - content : entry=-66
UPDATE `trans_words` SET `content_loc3`='TIMMY!' WHERE `word_id` = 5561; -- creature_ai_texts - content : entry=-1197
UPDATE `trans_words` SET `content_loc3`='To you it is well known under the name of the ancient gods. Beware Yogg-Saron, a beast with a thousand paste. His evil has spread far beyond the roots Fordrassila.' WHERE `word_id` = 6881; -- creature_ai_texts - content : entry=-50013
UPDATE `trans_words` SET `content_loc3`='Turn your back while you can!' WHERE `word_id` = 6482; -- creature_ai_texts - content : entry=-71
UPDATE `trans_words` SET `content_loc3`='Uuuuhhhhhhhhhh......' WHERE `word_id` = 6816; -- creature_ai_texts - content : entry=-1184
UPDATE `trans_words` SET `content_loc3`='Very well, kitten. I see no need to delay your inevitable demise. I look forward to dealing with you just as soon as I finish off these simpletons!' WHERE `word_id` = 6761; -- creature_ai_texts - content : entry=-953
UPDATE `trans_words` SET `content_loc3`='Wa\'re da ship! A harpy! ...wait, dat be another bird.' WHERE `word_id` = 6776; -- creature_ai_texts - content : entry=-1017
UPDATE `trans_words` SET `content_loc3`='Wait for me orders. I handle dis myself!' WHERE `word_id` = 6795; -- creature_ai_texts - content : entry=-1151
UPDATE `trans_words` SET `content_loc3`='Wait... No! No!' WHERE `word_id` = 6504; -- creature_ai_texts - content : entry=-49
UPDATE `trans_words` SET `content_loc3`='Wait... WAIT! What is it that you want to know? I know you\'re the $C named $N.' WHERE `word_id` = 6692; -- creature_ai_texts - content : entry=-803
UPDATE `trans_words` SET `content_loc3`='Was... Was it all a dream? Azuremyst, Bloodymyst, Zangarmarsh, Shadowmoon... even Zul\'Aman... Jane! Jane where are you!' WHERE `word_id` = 6118; -- creature_ai_texts - content : entry=-944
UPDATE `trans_words` SET `content_loc3`='We are Mechagnome...resistance is futile.' WHERE `word_id` = 6605; -- creature_ai_texts - content : entry=-533
UPDATE `trans_words` SET `content_loc3`='we can decurse you, we have the technology' WHERE `word_id` = 6607; -- creature_ai_texts - content : entry=-535
UPDATE `trans_words` SET `content_loc3`='We know... that you don\'t... know why we\'re immune... to your so-called blight. Grand Admiral Westwind somehow gave the high abbot that prayer. I beg you... no more... please?' WHERE `word_id` = 6694; -- creature_ai_texts - content : entry=-805
UPDATE `trans_words` SET `content_loc3`='We will find what the Master is looking for! Failure is not an option!' WHERE `word_id` = 6010; -- creature_ai_texts - content : entry=-1134
UPDATE `trans_words` SET `content_loc3`='We will not surrender!' WHERE `word_id` = 6895; -- creature_ai_texts - content : entry=-243814
UPDATE `trans_words` SET `content_loc3`='We... We have only been told that the "Crimson Dawn" is an awakening. You see, the Light speaks to the High General. It is the Light...' WHERE `word_id` = 6612; -- creature_ai_texts - content : entry=-556
UPDATE `trans_words` SET `content_loc3`='We\'re here as support for the so-called \'adventurers\' that the brass called in. We\'ll help them hold the key points on the island, and keep the heat off so that they can do their jobs.' WHERE `word_id` = 6285; -- creature_ai_texts - content : entry=-386
UPDATE `trans_words` SET `content_loc3`='Welcome to the world of the unliving!' WHERE `word_id` = 6747; -- creature_ai_texts - content : entry=-890
UPDATE `trans_words` SET `content_loc3`='Well, he comes back to the king all pretendin\' to be nice, draws his sword, and runs the king through, elbow to... well you know... kills him on the spot...' WHERE `word_id` = 6225; -- creature_ai_texts - content : entry=-610
UPDATE `trans_words` SET `content_loc3`='What a pitiful choice of an ally Crok.' WHERE `word_id` = 3806; -- creature_ai_texts - content : entry=-1138
UPDATE `trans_words` SET `content_loc3`='What do you put in that pipe of yours Nat?' WHERE `word_id` = 6216; -- creature_ai_texts - content : entry=-619
UPDATE `trans_words` SET `content_loc3`='What is this? Mag thorin Kar! Kill them!' WHERE `word_id` = 6625; -- creature_ai_texts - content : entry=-631
UPDATE `trans_words` SET `content_loc3`='What is this?! Didn\'t mommy and daddy teach you anything?' WHERE `word_id` = 6174; -- creature_ai_texts - content : entry=-685
UPDATE `trans_words` SET `content_loc3`='What will become of...' WHERE `word_id` = 6508; -- creature_ai_texts - content : entry=-41
UPDATE `trans_words` SET `content_loc3`='What? HAR\'KOA?' WHERE `word_id` = 6760; -- creature_ai_texts - content : entry=-952
UPDATE `trans_words` SET `content_loc3`='What? Oh, not this again!' WHERE `word_id` = 6924; -- creature_ai_texts - content : entry=-159411
UPDATE `trans_words` SET `content_loc3`='What? Where in a..? Don\'t just stand around lads KILL SOMEBODY!' WHERE `word_id` = 6622; -- creature_ai_texts - content : entry=-628
UPDATE `trans_words` SET `content_loc3`='When do we eat again?' WHERE `word_id` = 6246; -- creature_ai_texts - content : entry=-588
UPDATE `trans_words` SET `content_loc3`='Where am I? What...' WHERE `word_id` = 6501; -- creature_ai_texts - content : entry=-52
UPDATE `trans_words` SET `content_loc3`='Where? Where are the Shards! You cannot hide them from us!' WHERE `word_id` = 5995; -- creature_ai_texts - content : entry=-1209
UPDATE `trans_words` SET `content_loc3`='Who dares to awaken from its Goc\'s sleep?' WHERE `word_id` = 6902; -- creature_ai_texts - content : entry=-205552
UPDATE `trans_words` SET `content_loc3`='Who dares?' WHERE `word_id` = 6582; -- creature_ai_texts - content : entry=-498
UPDATE `trans_words` SET `content_loc3`='Who offended altar Goc!' WHERE `word_id` = 6901; -- creature_ai_texts - content : entry=-205551
UPDATE `trans_words` SET `content_loc3`='Whoah! Walk by again girl!' WHERE `word_id` = 6080; -- creature_ai_texts - content : entry=-1005
UPDATE `trans_words` SET `content_loc3`='Why couldn\'t mother have chosen something else to dedicate herself to? Cakes, pastries, even bread - anything but cheese!' WHERE `word_id` = 6120; -- creature_ai_texts - content : entry=-942
UPDATE `trans_words` SET `content_loc3`='Why, Luhanaa? Why?' WHERE `word_id` = 6133; -- creature_ai_texts - content : entry=-917
UPDATE `trans_words` SET `content_loc3`='Will you help me find my dog...?' WHERE `word_id` = 6426; -- creature_ai_texts - content : entry=-150
UPDATE `trans_words` SET `content_loc3`='Wow! The laughs dont\'t drop very often here, do they?' WHERE `word_id` = 6016; -- creature_ai_texts - content : entry=-1118
UPDATE `trans_words` SET `content_loc3`='Ya look lovesick. Special someone be gettin\' ya down, eh? No worries, no worries. Ya get this medallion from me, ya wear it when ya see \'em and they be all over ya, sweetheart!' WHERE `word_id` = 6368; -- creature_ai_texts - content : entry=-265
UPDATE `trans_words` SET `content_loc3`='Ya look tired, $C. I be havin\' somethin\' for ya. These amulets, they can help ya leap obstacles and swim through the rivers like ya be born to it. They energize the food ya be eatin\'. Makin\' yer wounds close before yer eyes!' WHERE `word_id` = 6371; -- creature_ai_texts - content : entry=-262
UPDATE `trans_words` SET `content_loc3`='Yea, that hit the spot. Muffins for sale! Get your fresh muffins right here!' WHERE `word_id` = 6363; -- creature_ai_texts - content : entry=-270
UPDATE `trans_words` SET `content_loc3`='Yes, YES! Ahahah!' WHERE `word_id` = 1722; -- creature_ai_texts - content : entry=-1271
UPDATE `trans_words` SET `content_loc3`='Yes... I think I remember now...' WHERE `word_id` = 6491; -- creature_ai_texts - content : entry=-62
UPDATE `trans_words` SET `content_loc3`='You are no longer dealing with some underling.' WHERE `word_id` = 6512; -- creature_ai_texts - content : entry=-37
UPDATE `trans_words` SET `content_loc3`='You are spotted by the eye of Grillok!' WHERE `word_id` = 6505; -- creature_ai_texts - content : entry=-48
UPDATE `trans_words` SET `content_loc3`='You are...irrelevant.' WHERE `word_id` = 5953; -- creature_ai_texts - content : entry=-1263
UPDATE `trans_words` SET `content_loc3`='You brought this on yourselves.' WHERE `word_id` = 6464; -- creature_ai_texts - content : entry=-95
UPDATE `trans_words` SET `content_loc3`='You came for the drawings doctor! Death - that\'s all you get here!' WHERE `word_id` = 6917; -- creature_ai_texts - content : entry=-304091
UPDATE `trans_words` SET `content_loc3`='You dare to challenge Drottin Hrothgar, king of the seas?' WHERE `word_id` = 6687; -- creature_ai_texts - content : entry=-796
UPDATE `trans_words` SET `content_loc3`='You dare? Where is Baron Sliver? I would have words with him!' WHERE `word_id` = 6927; -- creature_ai_texts - content : entry=-298582
UPDATE `trans_words` SET `content_loc3`='You don\'t worry me, boy. Just the opposite - I look forward to killing you and your friends. Nothing will stand between me and Zim\'Torga now!' WHERE `word_id` = 6757; -- creature_ai_texts - content : entry=-949
UPDATE `trans_words` SET `content_loc3`='You have no right to take the talisman, $N! You will pay for their sins.' WHERE `word_id` = 6909; -- creature_ai_texts - content : entry=-262251
UPDATE `trans_words` SET `content_loc3`='YOU KEEP YOUR FILTHY DRAKKARI HANDS OFF THEM!' WHERE `word_id` = 6764; -- creature_ai_texts - content : entry=-956
UPDATE `trans_words` SET `content_loc3`='You look tired...' WHERE `word_id` = 6401; -- creature_ai_texts - content : entry=-224
UPDATE `trans_words` SET `content_loc3`='You must not approach the Frost Queen, quickly... stop them!' WHERE `word_id` = 6794; -- creature_ai_texts - content : entry=-1150
UPDATE `trans_words` SET `content_loc3`='You no take...me!' WHERE `word_id` = 6638; -- creature_ai_texts - content : entry=-693
UPDATE `trans_words` SET `content_loc3`='You seek their leader... little things, you wage war against the clans of Grom\'thar the Thunderbringer himself. Don\'t be so eager to rush to your deaths.' WHERE `word_id` = 6750; -- creature_ai_texts - content : entry=-893
UPDATE `trans_words` SET `content_loc3`='You should not have come.' WHERE `word_id` = 6462; -- creature_ai_texts - content : entry=-97
UPDATE `trans_words` SET `content_loc3`='YOU WANT DRINK? WE GOT DRINK!' WHERE `word_id` = 6164; -- creature_ai_texts - content : entry=-719
UPDATE `trans_words` SET `content_loc3`='You will die for your hubris, druid!' WHERE `word_id` = 6390; -- creature_ai_texts - content : entry=-241
UPDATE `trans_words` SET `content_loc3`='You would destined to fail.' WHERE `word_id` = 6727; -- creature_ai_texts - content : entry=-867
UPDATE `trans_words` SET `content_loc3`='You... are nothing!' WHERE `word_id` = 6249; -- creature_ai_texts - content : entry=-573
UPDATE `trans_words` SET `content_loc3`='You... will... pay...' WHERE `word_id` = 6499; -- creature_ai_texts - content : entry=-54
UPDATE `trans_words` SET `content_loc3`='You\'ll have to kill me, monster! I will tell you NOTHING!' WHERE `word_id` = 6617; -- creature_ai_texts - content : entry=-561
UPDATE `trans_words` SET `content_loc3`='You\'re a slave. That\'s all you\'ll ever be.' WHERE `word_id` = 5967; -- creature_ai_texts - content : entry=-1249
UPDATE `trans_words` SET `content_loc3`='You\'ve meddled in affairs that were none of your business. You are nothing but foreign invaders. Prepare to die!' WHERE `word_id` = 6759; -- creature_ai_texts - content : entry=-951
UPDATE `trans_words` SET `content_loc3`='Your companion is looking for a patriarch shardhorn Farunn, which keeps the dismissal of their colleagues.' WHERE `word_id` = 6876; -- creature_ai_texts - content : entry=-50006
UPDATE `trans_words` SET `content_loc3`='Your corpse will nourish the soil!' WHERE `word_id` = 3070; -- creature_ai_texts - content : entry=-428
UPDATE `trans_words` SET `content_loc3`='Your fate is sealed, Azeroth! I will find the Aspect Shards, and then you will not stand against our might!' WHERE `word_id` = 5997; -- creature_ai_texts - content : entry=-1207
UPDATE `trans_words` SET `content_loc3`='Your journey has just begun, young prince. Gather your forces, and meet me in the arctic land of Northrend. It is there we shall settle the score between us. It is there that your true destiny will unfold.' WHERE `word_id` = 6868; -- creature_ai_texts - content : entry=-870
UPDATE `trans_words` SET `content_loc3`='Your mother was a wench and your father smelt of seaforium!' WHERE `word_id` = 6660; -- creature_ai_texts - content : entry=-739
UPDATE `trans_words` SET `content_loc3`='Your own strength feeds me!' WHERE `word_id` = 5993; -- creature_ai_texts - content : entry=-1211
UPDATE `trans_words` SET `content_loc3`='Your pathetic attempt to escape will be short lived, Gorefiend. Let the boy go and submit! Even with your armour and weapons, you cannot defeat the ancients!' WHERE `word_id` = 6536; -- creature_ai_texts - content : entry=-1320
UPDATE `trans_words` SET `content_loc3`='Your torture only increased my fury!' WHERE `word_id` = 6897; -- creature_ai_texts - content : entry=-296472
UPDATE `trans_words` SET `content_loc3`='Your world is ours now.' WHERE `word_id` = 6455; -- creature_ai_texts - content : entry=-112
UPDATE `trans_words` SET `content_loc3`='Your world will die, mortals! Your doom is now at hand!' WHERE `word_id` = 5994; -- creature_ai_texts - content : entry=-1210

SET NAMES 'latin1';
