-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc3`='"Hi, are you here to learn about the Bloodmyst conflict?"' WHERE `word_id` = 195544; -- locales_npc_text - Text0_1 : entry=9172
UPDATE `trans_words` SET `content_loc3`='"Hi, are you here to learn about the Bloodmyst conflict?"' WHERE `word_id` = 279539; -- locales_npc_text - Text1_0 : entry=9172
UPDATE `trans_words` SET `content_loc3`='"I really envy you,$N. You performed$G: performed; the work is just awesome."' WHERE `word_id` = 214237; -- locales_npc_text - Text0_1 : entry=5940
UPDATE `trans_words` SET `content_loc3`='"I was at Velgar\'s site a couple of days ago to ... help free ... some relics of the titans from the bones of the dead dinosaurs, and I saw him there! Zarlozub is alive!$B$BWell, he is undead, that is, he is not quite alive, but he is not dead! Zarolozub exists!"' WHERE `word_id` = 280136; -- locales_npc_text - Text3_0 : entry=16528
UPDATE `trans_words` SET `content_loc3`='"If you need robbers, head to the Old Town. It is in the northeast of Stormwind."' WHERE `word_id` = 276845; -- locales_npc_text - Text2_1 : entry=900
UPDATE `trans_words` SET `content_loc3`='"It\'s a great honor to see you again,$N."' WHERE `word_id` = 279605; -- locales_npc_text - Text1_0 : entry=5935
UPDATE `trans_words` SET `content_loc3`='"Many entered this sanctuary, but few left it."' WHERE `word_id` = 278038; -- locales_npc_text - Text2_1 : entry=6911
UPDATE `trans_words` SET `content_loc3`='"On the way here from Dun Algaz, I saw a gnoll hunting for hard-toothed in the middle of the lake. Have you ever seen a dog with a spear? That was a sight!"' WHERE `word_id` = 279674; -- locales_npc_text - Text0_1 : entry=16528
UPDATE `trans_words` SET `content_loc3`='"Piastres! Stir, land rats!"' WHERE `word_id` = 214385; -- locales_npc_text - Text3_0 : entry=13058
UPDATE `trans_words` SET `content_loc3`='"Will you bring me something to drink? I myself would go, but sunbathe."' WHERE `word_id` = 280302; -- locales_npc_text - Text2_1 : entry=17850
UPDATE `trans_words` SET `content_loc3`='A Rut\'theran Ferry leaves for Auberdine from Rut\'theran Village at the base of Teldrassil. The portal in Darnassus will allow you to reach Rut\'theran safely.' WHERE `word_id` = 193360; -- locales_npc_text - Text1_0 : entry=4318
UPDATE `trans_words` SET `content_loc3`='Brggl-brggl Mrgl-Mrgl! Gluk!' WHERE `word_id` = 197209; -- locales_npc_text - Text3_0 : entry=12362
UPDATE `trans_words` SET `content_loc3`='Darkmoon Cards? This is to the professor. And I deal with antiquities and artifacts.' WHERE `word_id` = 194586; -- locales_npc_text - Text0_1 : entry=7389
UPDATE `trans_words` SET `content_loc3`='Darkmoon Cards? This is to the professor. And I deal with antiquities and artifacts.' WHERE `word_id` = 279505; -- locales_npc_text - Text1_0 : entry=7389
UPDATE `trans_words` SET `content_loc3`='Darkmoon Faire Cards?  See the Professor here for those. Come see me if you are a dealer in hard to come by antiquities and artifacts.' WHERE `word_id` = 194587; -- locales_npc_text - Text1_1 : entry=7389
UPDATE `trans_words` SET `content_loc3`='Free Wind Outpost is lost. Thousands of Needles are gone.' WHERE `word_id` = 280065; -- locales_npc_text - Text4_1 : entry=15837
UPDATE `trans_words` SET `content_loc3`='Gryphons, eh? Never really cared for the beasts but to each their own.$B$BYou can find Dungar Longdrink on the rampart in the Trade District.' WHERE `word_id` = 192106; -- locales_npc_text - Text3_0 : entry=879
UPDATE `trans_words` SET `content_loc3`='Have you seen what prices are going up here? Horror!' WHERE `word_id` = 280300; -- locales_npc_text - Text0_1 : entry=17850
UPDATE `trans_words` SET `content_loc3`='How are we going to get out of here?' WHERE `word_id` = 279642; -- locales_npc_text - Text3_0 : entry=15904
UPDATE `trans_words` SET `content_loc3`='I have so much to do... so much before the plague comes...' WHERE `word_id` = 193002; -- locales_npc_text - Text1_1 : entry=3668
UPDATE `trans_words` SET `content_loc3`='I will mark this place on your map.' WHERE `word_id` = 199437; -- locales_npc_text - Text0_1 : entry=13888
UPDATE `trans_words` SET `content_loc3`='I will mark this place on your map.' WHERE `word_id` = 279469; -- locales_npc_text - Text1_0 : entry=13888
UPDATE `trans_words` SET `content_loc3`='Ironforge is going to be your best bet for leatherworkers. If memory servers, there\'s a shop by The Great Forge that should meet yer needs.' WHERE `word_id` = 193349; -- locales_npc_text - Text1_0 : entry=4310
UPDATE `trans_words` SET `content_loc3`='It is only a matter of time for the nagas to find us here.$B$BWhat should we fight against them?' WHERE `word_id` = 279643; -- locales_npc_text - Text5_0 : entry=15904
UPDATE `trans_words` SET `content_loc3`='Mawurrgggl, gurgl lur!' WHERE `word_id` = 197207; -- locales_npc_text - Text1_0 : entry=12362
UPDATE `trans_words` SET `content_loc3`='May Mother Earth protect us.' WHERE `word_id` = 280064; -- locales_npc_text - Text3_0 : entry=15837
UPDATE `trans_words` SET `content_loc3`='Mhrrumph rummrhum phurr!' WHERE `word_id` = 199285; -- locales_npc_text - Text3_0 : entry=13326
UPDATE `trans_words` SET `content_loc3`='Mrglmrgl Glrggl!' WHERE `word_id` = 197213; -- locales_npc_text - Text7_0 : entry=12362
UPDATE `trans_words` SET `content_loc3`='Nana always said there was no greater thing in the whole world than a warm, toasty slice of fresh, home made cherry pie.' WHERE `word_id` = 192480; -- locales_npc_text - Text1_0 : entry=2355
UPDATE `trans_words` SET `content_loc3`='No better place to learn First Aid than under the watchful eye of Shaina Fuller at the Cathedral of Light. $B$BTo get there, just look for the yellow rooftops, or the towering spire of the Cathedral itself which you can see from almost anywhere in the city.' WHERE `word_id` = 192143; -- locales_npc_text - Text1_0 : entry=923
UPDATE `trans_words` SET `content_loc3`='Rmmurphum mmph hmrphum!' WHERE `word_id` = 199283; -- locales_npc_text - Text1_0 : entry=13326
UPDATE `trans_words` SET `content_loc3`='Squid guts! Squid Rryi!' WHERE `word_id` = 214383; -- locales_npc_text - Text1_0 : entry=13058
UPDATE `trans_words` SET `content_loc3`='The kid bites and hits with the paw of an invisible adversary: ​​he is impatient to evaluate his hunting skills.' WHERE `word_id` = 280297; -- locales_npc_text - Text3_0 : entry=17839
UPDATE `trans_words` SET `content_loc3`='The kid tries to hit the tiny fly with his paw and pays attention to you only after his toy flies away.' WHERE `word_id` = 280295; -- locales_npc_text - Text1_0 : entry=17839
UPDATE `trans_words` SET `content_loc3`='The Leader of the Horn of the Spirit should soon send help to the Free Wind Outpost.' WHERE `word_id` = 280067; -- locales_npc_text - Text6_1 : entry=15837
UPDATE `trans_words` SET `content_loc3`='The power of Elune compels you!  The power of Elune compels you!  $B$BGo now!  Seek out Jandria in the central hall of the Temple of the Moon in the southern section of Darnassus!' WHERE `word_id` = 192741; -- locales_npc_text - Text1_0 : entry=3025
UPDATE `trans_words` SET `content_loc3`='The Stormpike Guard is in need of your assistance in the fight against the Frostwolf Clan, $N. Speak to Brogun Stoneshield on the Warrior\'s Terrace and he will help you find your way to Alterac Valley.' WHERE `word_id` = 194630; -- locales_npc_text - Text1_1 : entry=7496
UPDATE `trans_words` SET `content_loc3`='This is called a cataclysm. What led to such destruction? Why us' WHERE `word_id` = 280068; -- locales_npc_text - Text7_0 : entry=15837
UPDATE `trans_words` SET `content_loc3`='UDB Missing US text' WHERE `word_id` = 197021; -- locales_npc_text - Text1_0 : entry=14536
UPDATE `trans_words` SET `content_loc3`='Water gushed and flooded everything!' WHERE `word_id` = 280061; -- locales_npc_text - Text0_1 : entry=15837
UPDATE `trans_words` SET `content_loc3`='We are here to protect the Blood Outpost from the Solar Hawks.' WHERE `word_id` = 195572; -- locales_npc_text - Text0_1 : entry=9206
UPDATE `trans_words` SET `content_loc3`='We are here to protect the Blood Outpost from the Solar Hawks.' WHERE `word_id` = 279542; -- locales_npc_text - Text1_0 : entry=9206
UPDATE `trans_words` SET `content_loc3`='We unquestioningly serve the Light. Perhaps you have aroused curiosity and want to know more about our goals?' WHERE `word_id` = 279541; -- locales_npc_text - Text3_0 : entry=9172
UPDATE `trans_words` SET `content_loc3`='Well well!  You\'ve come to the right place to learn Mining, $Gboyo : girlie;!  Geofram Bouldertoe himself resides at the Deepmountain Mining Guild. Ye couldn\'t ask for a better instructor than him.' WHERE `word_id` = 192677; -- locales_npc_text - Text0_1 : entry=2804
UPDATE `trans_words` SET `content_loc3`='When I was wandering the crater after I crashed here, I remembered something that I once was told... Go up, up the mountain ahead, said the voice in my head.$B$BListening to it is how I ended up here, $N!' WHERE `word_id` = 192571; -- locales_npc_text - Text3_0 : entry=2634
UPDATE `trans_words` SET `content_loc3`='Where do you want to go?' WHERE `word_id` = 200292; -- locales_npc_text - Text0_1 : entry=13310
UPDATE `trans_words` SET `content_loc3`='Why did Mother Earth not save us?' WHERE `word_id` = 280066; -- locales_npc_text - Text5_0 : entry=15837
UPDATE `trans_words` SET `content_loc3`='You know, I could run an orc through or slice up a troll, I could even carve my initials in an ogre\'s flank, but I just can\'t stand to skin an animal. Go figure, eh. $B$BWell, if you have the stomach for it, then go see Maris Granger at the Protective Hide in Old Town.' WHERE `word_id` = 192151; -- locales_npc_text - Text1_0 : entry=928
UPDATE `trans_words` SET `content_loc3`='You need something fixed? Use the Vend-O-Matic.' WHERE `word_id` = 196782; -- locales_npc_text - Text1_0 : entry=12332
UPDATE `trans_words` SET `content_loc3`='You saw$G: saw; what is it huge to ?!' WHERE `word_id` = 214407; -- locales_npc_text - Text1_0 : entry=15904
UPDATE `trans_words` SET `content_loc3`='You$G owe: must; go to the Thousand Needles and provide assistance. You are welcome!' WHERE `word_id` = 280063; -- locales_npc_text - Text2_1 : entry=15837

SET NAMES 'latin1';
